<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
/**
 * @var mixed[] $object
 */
$object = $this->object;
?>
<div class="row">
<div class="col-md-3">
<?php if (isset($object['publicationId']) &&
        file_exists(sprintf('public/covers/%s-200px.jpg', $object['publicationId']))) : ?>
    <a href="<?php echo $this->basePath() . sprintf("/covers/%s.jpg", $object['publicationId']); ?>">
    <img src="<?php echo $this->basePath() . sprintf("/covers/%s-200px.jpg", $object['publicationId']); ?>"
    height="200px" alt="<?php echo $this->escapeHtmlAttr($object['title']);?>"></a>
<?php endif;?>
</div>
<div class="col-md-9">
<div class="panel panel-default" id="infoPanel">
    <div class="panel-heading">
        <div class="row">
        <div class="col-xs-6">
            <h3 class="panel-title"><?php echo $this->escapeHtml($this->translate('Book Info')); ?></h3>
        </div>
        <div class="col-xs-6">
            <?php if ($this->isAllowed($object['resourceId'], 'administrate')): ?>
                <span class="pull-right"><a class="btn btn-primary btn-sm" href="<?php
                    echo $this->url('books/book/edit', [], [], true);?>">
                    <?php echo $this->translate('Edit book')?></a>
                </span>
            <?php endif;?>
        </div>
        </div>
    </div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
        <p><strong><?php echo $this->translate('Library');?>:</strong> <?php
            echo $this->formatEntity('library', $object['library']);?></p>
        <?php 
        echo $this->formatField('Call number', $object['callNumber']);
        echo $this->formatField('Pending call number', $object['newCallNumber'], ['displayOnlyIfNotNull' => true]);
        if (isset($object['collectionId']) && isset($object['library']['options']) && isset($object['library']['options']->collections[$object['collectionId']])) {
            echo $this->formatField('Collection', $object['library']['options']->collections[$object['collectionId']]->name, ['displayOnlyIfNotNull' => true]);
        }
        echo $this->formatField('Barcode', $object['withinLibraryId']);
        echo $this->formatField('Author(s)', $object['authorsPrettyText']);?>
    </div> <!-- info 1 column -->

    <div class="col-md-6">
        <?php
        echo $this->formatField('Language', $object['inLanguage']);
        echo $this->formatField('Category', $object['category']); //make this a link to search involving all books of this category
        echo $this->formatField('ISBN', $object['isbn'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Edition', $object['bookEdition'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Number of pages', $object['numberOfPages'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Year published', $object['publishedYear'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Publisher', $object['publisher'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Publishing place', $object['publishingPlace'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Keywords', $object['keywords'], ['displayOnlyIfNotNull' => true, 'translateLabel' => false]);
        echo $this->formatField('Admin tags', $object['adminTags'], ['displayOnlyIfNotNull' => true, 'translateLabel' => false,
            'displayOnlyWithPermission' => $object['resourceId']]);
        if (isset($this->borrowers[$object['currentCheckout']['personId']])) {
            echo $this->formatField('Checked out by', $this->borrowers[$object['currentCheckout']['personId']], ['displayOnlyIfNotNull' => true,
                'displayOnlyWithPermission' => 'view_checkout_person']);
        }
        echo $this->formatField('Due on', $object['currentCheckout']['dueOn'], ['displayOnlyIfNotNull' => true,
            'displayOnlyWithPermission' => 'view_checkout_person']);
        echo $this->formatField('Inactivation reason', $object['inactivationReason'], ['displayOnlyIfNotNull' => true,
            'displayOnlyWithPermission' => 'route/libraries/library/inactivate-books']);
        ?>
    </div> <!-- info 2 column -->
    </div></div> <!-- contact info panel body -->
</div> <!-- course info 1 panel -->
</div> <!-- info 1 column -->
</div> <!-- Info row -->

  <?php if (isset($object['publicNotes'])):?>
<div class="row"> <!-- notes row -->
<div class="col-md-12">
<div class="panel panel-default" id="notesPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Notes'); ?></h3>
    </div>
    <div class="panel-body">
    <div><?php echo $this->markdown($object['publicNotes']);?>
    </div>
    </div> <!-- notes panel body -->
</div> <!-- notes panel -->
</div> <!-- notes column 12 -->
</div> <!-- notes row -->
<?php endif;
// @todo Add checkout history for admins
if (isset($object['adminNotes']) &&
          $this->isAllowed($object['resourceId'], 'show-admin-info')):?>
<div class="row"> <!-- notes row -->
<div class="col-md-12">
<div class="panel panel-default" id="adminNotesPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Admin notes'); ?></h3>
    </div>
    <div class="panel-body">
    <div><?php echo $this->markdown($object['adminNotes']);?>
    </div>
    </div> <!-- notes panel body -->
</div> <!-- notes panel -->
</div> <!-- notes column 12 -->
</div> <!-- notes row -->
<?php endif;
?>