<?php
$headText = 'Add new library book';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$this->formSelect()->setTranslatorEnabled(false);
$form->setAttribute('action', $this->url('books/create', [], [], true));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', $this->vars);
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
