<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-selectize-markdown-jquery-ui.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . "/js/gen-validate-selectize-markdown-$lang.js");

/** @var \Books\Form\BookForm $form */
$form = $this->form;
$libraryOptions = $form->getLibraryOptions();
echo $this->formRow($form->get('withinLibraryId'));
echo $this->formButton($form->get('nextWithinLibraryId'));
echo $this->formRow($form->get('title'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('authors'));
echo $this->formRow($form->get('collectionId'));
echo $this->formRow($form->get('callNumber'));
echo $this->formRow($form->get('newCallNumber'));
echo $this->formRow($form->get('inLanguage'));
echo $this->formRow($form->get('category'));
echo $this->formRow($form->get('isbn'));
echo $this->formRow($form->get('bookEdition'));
echo $this->formRow($form->get('numberOfPages'));
echo $this->formRow($form->get('publishedYear'));
echo $this->formRow($form->get('publisher'));
echo $this->formRow($form->get('publishingPlace'));
echo $this->formRow($form->get('publicationId'));
echo $this->formRow($form->get('keywords'));?>
<div class="pull-right commonmark-help"><a href="http://commonmark.org/help/" class="btn btn-default"> <?php echo $this->translate("Learn Markdown in 60 seconds");?></a></div>
<?php
echo $this->formRow($form->get('publicNotes'));
echo $this->formRow($form->get('adminNotes'));
echo $this->formRow($form->get('adminTags'));
echo $this->formRow($form->get('isActive'));
echo $this->formRow($form->get('inactivationReason'));
echo $this->formRow($form->get('security'));
$nextWithinLibraryId = $libraryOptions->nextWithinLibraryId;
$jsScript = <<<JS
$("select[name='authors[]']").selectize({
    create: true,
    sortField: 'text',
    delimiter: ';'
});
$("select[name='inLanguage[]']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='publisher']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='publicationId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='keywords[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='adminTags[]']").selectize({
    create: true,
    sortField: 'text'
});
$("#nextWithinLibraryId").click(function() {
    $("input[name='withinLibraryId']").val($nextWithinLibraryId);
});

//use the following function with JqueryUI to validate the ISBN
function validateIsbn(a){var b=i=r=0,t=10,l=a.length;if(l==t){for(i;i<9;i++)b+=a[i]*(t-i);r=(b+(a[9]=='X'?t:a[9]))%11==0}if(l==13){for(i;i<12;i++)b+=(i+1)%2?+a[i]:a[i]*3;r=b%t==t-(+a[12]||t)}return r?a:0}


$("#book").validate({
//   debug: true,
  ignore: ':hidden:not([class~=selectized]),:hidden > .selectized, .selectize-control .selectize-input input'
});
$.validator.addMethod("isbn", function(value, element) {
  return this.optional( element ) || validateIsbn( value );
}, 'Please enter a valid ISBN number.');
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();

?>
