<?php
$object = $this->entity;
//@todo add edition information and author into meta description
$this->headMeta()->appendName('description', $object['title']);
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($object['title']);?>
<h1><?php echo $this->escapeHtml($this->entity['title']);?></h1>
<?php
echo $this->partial('book-info', ['object' => $this->entity]);
if (isset($this->entity['publication'])) {
    echo $this->partial('publication-info', ['object' => $this->entity]);
}

if ($this->isAllowed('route/books/book/inactivate')):?>
<p><a class="btn btn-default" href="<?php echo $this->url('books/book/inactivate', [], [], true);?>"><?php
echo $this->translate('Add another edition');?></a></p>
<?php endif;
if ($this->isAllowed('route/books/book/edit')) {
    echo $this->partial('sion-model/sion-model/entity-changes-panel', [
        'changes' => $this->changes,
        'panelTitle' => 'Change log'
    ]);
}?>
