<?php
$object = $this->entity;
//@todo add edition information and author into meta description
$this->headMeta()->appendName('description', $object['title']);
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($object['title']);?>
<h1><?php echo $this->escapeHtml($this->entity['title']);?><?php 
if (!$object['isActive']) { echo sprintf("&nbsp;<span class=\"label label-warning\">%s</span>", $this->translate("Inactive"));}
?></h1>
<?php
echo $this->partial('book-info', ['object' => $this->entity, 'borrowers' => $this->borrowers]);
if (isset($this->entity['publication'])) {
    echo $this->partial('books/publications/publication-info', ['object' => $this->entity['publication'], 'options' => [
        'showCover' => false,
        'panelTitle' => 'book-title-and-link',
    ]]);
}

//@todo "Add another copy" button
if ($this->isAllowed($object['resourceId'], 'administrate')):?>
<!-- <p><a class="btn btn-default" href="<?php // echo $this->url('books/book/inactivate', [], [], true);?>"><?php
//echo $this->translate('Add another edition');?></a></p> -->
<?php endif;
if ($this->isAllowed($object['resourceId'], 'administrate')) {
    echo $this->partial('sion-model/sion-model/entity-changes-panel', [
        'changes' => $this->changes,
        'panelTitle' => 'Change log'
    ]);
}?>
