-- The application's schema, with no rows in it.
--
-- Generated by tools/schema-dump.sh from the capsule; `./tools/schema-dump.sh --check`
-- fails when it no longer matches. Do not hand-edit: a schema change belongs in a
-- database/*.sql migration, and this file is regenerated after that migration runs.
--
-- AUTO_INCREMENT counters and the dump's server/host header are stripped on purpose, so a
-- diff here is a schema change and nothing else. `sch_migration` is absent because
-- tools/migrate.sh creates the ledger itself and what an environment has applied is its
-- own state.

--
-- ------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `b_bibprim_edition`
--

DROP TABLE IF EXISTS `b_bibprim_edition`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `b_bibprim_edition` (
  `ed_id` int(11) NOT NULL AUTO_INCREMENT,
  `ed_evid` int(11) NOT NULL DEFAULT 0,
  `ed_title` varchar(255) NOT NULL DEFAULT '',
  `ed_remark` longtext NOT NULL,
  `ed_location` text NOT NULL,
  `ed_lang` enum('deu','engl','esp','port','fran','other') NOT NULL DEFAULT 'deu',
  `ed_internpatres` enum('no','yes') NOT NULL DEFAULT 'no',
  `ed_quality` varchar(255) NOT NULL DEFAULT '',
  `ed_qualityremark` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ed_id`),
  FULLTEXT KEY `ed_title` (`ed_title`),
  FULLTEXT KEY `ed_remark` (`ed_remark`),
  FULLTEXT KEY `ed_quality` (`ed_quality`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `b_bibprim_epoche`
--

DROP TABLE IF EXISTS `b_bibprim_epoche`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `b_bibprim_epoche` (
  `epoche_id` int(11) NOT NULL AUTO_INCREMENT,
  `epoche_name` varchar(50) NOT NULL DEFAULT '',
  `epoche_text` longtext NOT NULL,
  `epoche_lang` varchar(10) NOT NULL DEFAULT '',
  `epoche_datestart` int(8) NOT NULL DEFAULT 0,
  `epoche_dateend` int(8) NOT NULL DEFAULT 0,
  PRIMARY KEY (`epoche_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `b_bibprim_event`
--

DROP TABLE IF EXISTS `b_bibprim_event`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `b_bibprim_event` (
  `ev_id` int(11) NOT NULL AUTO_INCREMENT,
  `ev_kuerzelvaut` varchar(255) NOT NULL DEFAULT '',
  `ev_shortname` varchar(255) NOT NULL DEFAULT '',
  `ev_name` varchar(255) NOT NULL DEFAULT '',
  `ev_datestart` int(255) NOT NULL DEFAULT 0,
  `ev_dateend` int(255) NOT NULL DEFAULT 0,
  `ev_dateremark` varchar(255) NOT NULL DEFAULT '',
  `ev_intern` enum('no','yes') NOT NULL DEFAULT 'no',
  `ev_keywords` text NOT NULL,
  PRIMARY KEY (`ev_id`),
  FULLTEXT KEY `ev_shortname` (`ev_shortname`),
  FULLTEXT KEY `ev_keywords` (`ev_keywords`),
  FULLTEXT KEY `ev_name` (`ev_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `b_bibprim_join`
--

DROP TABLE IF EXISTS `b_bibprim_join`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `b_bibprim_join` (
  `join_id` int(11) NOT NULL AUTO_INCREMENT,
  `join_id_ev` int(4) NOT NULL DEFAULT 0,
  `join_id_comm` int(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`join_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `b_bibsek`
--

DROP TABLE IF EXISTS `b_bibsek`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `b_bibsek` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '',
  `vorname` varchar(50) NOT NULL DEFAULT '',
  `mitauthoren` text NOT NULL,
  `titel` text NOT NULL,
  `ort` varchar(100) NOT NULL DEFAULT '',
  `verlag` varchar(100) NOT NULL DEFAULT '',
  `auflage` varchar(20) NOT NULL DEFAULT '',
  `jahr` varchar(10) NOT NULL DEFAULT '',
  `umfang` varchar(50) NOT NULL DEFAULT '',
  `NameZeitschrift` varchar(255) NOT NULL DEFAULT '',
  `ISBN_ZeitschriftNr` varchar(50) NOT NULL DEFAULT '',
  `Reihe` varchar(255) NOT NULL DEFAULT '',
  `BandNr` varchar(20) NOT NULL DEFAULT '',
  `sprache` enum('deu','engl','esp','port','fran','other') NOT NULL DEFAULT 'deu',
  `art` enum('scientific','non scientific') NOT NULL DEFAULT 'non scientific',
  `herausgabe` enum('manuscript','self edition','official edition','digital') NOT NULL DEFAULT 'official edition',
  `kategorie` enum('Pallotti','theology','biography','pastoral','history of Schoenstatt','youth','Schoenstatt','spirituality','sociology','prayer','pedagogic','Maria','Kentenich','document','covenant of love','family','ecclesiology','other') NOT NULL DEFAULT 'pastoral',
  `Stichworte` text NOT NULL,
  `Inhalt` longtext NOT NULL,
  `download` varchar(255) NOT NULL DEFAULT '',
  `quelle` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bib_book_abbreviations`
--

DROP TABLE IF EXISTS `bib_book_abbreviations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bib_book_abbreviations` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Abbreviation ID',
  `abbreviation` varchar(255) NOT NULL,
  `book_id` int(11) NOT NULL COMMENT 'ID of book that is abbreviated',
  `language` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'en',
  `is_preferred` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Whether an abbreviation is the primary one for the book',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='A table mapping book abbreviations to the book they refer to';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bib_books`
--

DROP TABLE IF EXISTS `bib_books`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bib_books` (
  `book_id` int(11) NOT NULL,
  `name_en` varchar(100) NOT NULL,
  `name_es` varchar(100) DEFAULT NULL,
  `name_de` varchar(100) DEFAULT NULL,
  `name_pt` varchar(100) DEFAULT NULL,
  `name_fr` varchar(100) DEFAULT NULL,
  `order_jerusalem_en` int(11) NOT NULL DEFAULT 100,
  `order_jerusalem_es` int(11) NOT NULL DEFAULT 100,
  `is_new_testament` bit(1) DEFAULT NULL,
  `genre_id` tinyint(4) DEFAULT NULL,
  `is_canonical` bit(1) NOT NULL DEFAULT b'0',
  `chapter_count` smallint(6) DEFAULT NULL,
  `old_book_id` varchar(3) DEFAULT NULL,
  `testament` varchar(2) DEFAULT NULL,
  `alt_id_jeresp` int(11) DEFAULT NULL,
  `alt_id_njb` int(11) DEFAULT NULL,
  `alt_id_septnt` int(11) DEFAULT NULL,
  `alt_id_pueblo` int(11) DEFAULT NULL,
  `abbreviation_jerusalem_es` varchar(10) DEFAULT NULL,
  `abbreviation_jerusalem_en` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bib_dh_page`
--

DROP TABLE IF EXISTS `bib_dh_page`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bib_dh_page` (
  `PageNumber` int(11) NOT NULL,
  `FileName` varchar(50) NOT NULL,
  `ReferenceNumber` int(11) DEFAULT NULL,
  `StartDhNumber` int(11) DEFAULT NULL,
  `EndDhNumber` int(11) DEFAULT NULL,
  `HeaderText` varchar(500) DEFAULT NULL,
  `WidthInPixels` int(11) DEFAULT NULL,
  `HeightInPixels` int(11) DEFAULT NULL,
  `FullTextFileName` varchar(255) DEFAULT NULL,
  `FullTextOCR` text DEFAULT NULL,
  PRIMARY KEY (`PageNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bib_greek_root_words`
--

DROP TABLE IF EXISTS `bib_greek_root_words`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bib_greek_root_words` (
  `root_id` int(11) NOT NULL AUTO_INCREMENT,
  `root` varchar(100) NOT NULL,
  `part_of_speech` varchar(50) DEFAULT NULL,
  `first_verse_occurrence` int(8) unsigned zerofill DEFAULT NULL,
  `occurrence_count` int(11) DEFAULT NULL,
  `gender` enum('m','f','n') DEFAULT NULL COMMENT 'Only for nouns',
  `paradigm_part_1` varchar(100) DEFAULT NULL,
  `paradigm_part_2` varchar(100) DEFAULT NULL,
  `paradigm_part_3` varchar(100) DEFAULT NULL,
  `paradigm_part_4` varchar(100) DEFAULT NULL,
  `forms_available` varchar(700) DEFAULT NULL COMMENT 'pipe-separated list of forms',
  `dictionary_entry_id` int(11) DEFAULT NULL,
  `john_occurrence_count` int(11) NOT NULL DEFAULT 0,
  `john_first_verse_occurrence` int(8) unsigned zerofill DEFAULT NULL,
  PRIMARY KEY (`root_id`),
  UNIQUE KEY `root` (`root`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bib_verses`
--

DROP TABLE IF EXISTS `bib_verses`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bib_verses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `translation_id` varchar(10) NOT NULL,
  `verse_id` int(8) unsigned zerofill DEFAULT NULL,
  `book_id` int(11) DEFAULT NULL,
  `chapter` smallint(6) NOT NULL,
  `verse` smallint(6) NOT NULL,
  `text` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `comments`
--

DROP TABLE IF EXISTS `comments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `comments` (
  `CommentId` int(11) NOT NULL AUTO_INCREMENT,
  `Rating` int(2) DEFAULT NULL,
  `CommentKind` varchar(50) NOT NULL,
  `Comment` varchar(500) NOT NULL,
  `Status` varchar(50) NOT NULL,
  `ReviewedBy` int(11) DEFAULT NULL,
  `ReviewedOn` datetime DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`CommentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `csp_reports`
--

DROP TABLE IF EXISTS `csp_reports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `csp_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_report` longtext NOT NULL,
  `document_uri` longtext NOT NULL,
  `referrer` longtext NOT NULL,
  `violated_directive` longtext NOT NULL,
  `original_policy` longtext NOT NULL,
  `blocked_uri` longtext NOT NULL,
  `source_file` longtext NOT NULL,
  `line_number` longtext NOT NULL,
  `column_number` longtext NOT NULL,
  `status_code` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `events` (
  `EventId` int(11) NOT NULL AUTO_INCREMENT,
  `TitleEn` varchar(300) DEFAULT NULL,
  `TitleEs` varchar(300) DEFAULT NULL,
  `TitleDe` varchar(300) DEFAULT NULL,
  `TitlePt` varchar(300) DEFAULT NULL,
  `TitleIt` varchar(300) DEFAULT NULL,
  `TitleFr` varchar(300) DEFAULT NULL,
  `Zoom` smallint(6) NOT NULL DEFAULT 3,
  `Country` varchar(6) DEFAULT NULL,
  `OriginalLanguage` varchar(3) DEFAULT NULL,
  `SlugEn` varchar(50) DEFAULT NULL,
  `SlugEs` varchar(50) DEFAULT NULL,
  `SlugDe` varchar(50) DEFAULT NULL,
  `SlugPt` varchar(50) DEFAULT NULL,
  `SlugIt` varchar(50) DEFAULT NULL,
  `SlugFr` varchar(50) DEFAULT NULL,
  `WikidataSubjectId` int(11) DEFAULT NULL,
  `WikidataPropertyId` int(11) DEFAULT NULL,
  `WikidataLinkByDefault` tinyint(1) NOT NULL DEFAULT 0,
  `DescriptionEn` varchar(300) DEFAULT NULL,
  `DescriptionEs` varchar(300) DEFAULT NULL,
  `DescriptionDe` varchar(300) DEFAULT NULL,
  `DescriptionPt` varchar(300) DEFAULT NULL,
  `DescriptionIt` varchar(300) DEFAULT NULL,
  `DescriptionFr` varchar(300) DEFAULT NULL,
  `StartDate` datetime NOT NULL,
  `StartDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `Duration` int(11) DEFAULT NULL,
  `DurationUnit` varchar(20) NOT NULL DEFAULT 'day',
  `BestTextQuality` varchar(5) DEFAULT NULL,
  `Place` varchar(300) DEFAULT NULL,
  `Tags` varchar(500) DEFAULT NULL,
  `AdminTags` varchar(500) DEFAULT NULL,
  `AudienceText` varchar(500) DEFAULT NULL,
  `AbbreviationEn` varchar(50) DEFAULT NULL,
  `AbbreviationEs` varchar(50) DEFAULT NULL,
  `AbbreviationDe` varchar(50) DEFAULT NULL,
  `AbbreviationPt` varchar(50) DEFAULT NULL,
  `AbbreviationIt` varchar(50) DEFAULT NULL,
  `AbbreviationFr` varchar(50) DEFAULT NULL,
  `AclResourceId` varchar(50) NOT NULL DEFAULT 'evt_public',
  `Url1` varchar(1000) DEFAULT NULL,
  `Url1Label` varchar(50) DEFAULT NULL,
  `Url2` varchar(1000) DEFAULT NULL,
  `Url2Label` varchar(50) DEFAULT NULL,
  `Url3` varchar(1000) DEFAULT NULL,
  `Url3Label` varchar(50) DEFAULT NULL,
  `PublicNotes` mediumtext DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `AdminNotes` mediumtext DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  `LegacySource` varchar(255) DEFAULT NULL,
  `LegacyFile` varchar(255) DEFAULT NULL,
  `LegacyFileDateModified` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EventId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `files`
--

DROP TABLE IF EXISTS `files`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `files` (
  `FileId` int(11) NOT NULL AUTO_INCREMENT,
  `StoreFileName` varchar(256) NOT NULL,
  `OriginalFileName` varchar(256) NOT NULL,
  `FileKind` varchar(50) DEFAULT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Size` int(11) NOT NULL,
  `Sha1` varchar(40) NOT NULL,
  `ContentTags` varchar(256) DEFAULT NULL,
  `StructureTags` varchar(256) DEFAULT NULL,
  `MimeType` varchar(256) DEFAULT NULL,
  `IsPublic` bit(1) NOT NULL DEFAULT b'0',
  `IsEncrypted` bit(1) NOT NULL DEFAULT b'0',
  `EncryptedEncryptionKey` varchar(256) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`FileId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jtranslate_migration`
--

DROP TABLE IF EXISTS `jtranslate_migration`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `jtranslate_migration` (
  `migration` varchar(100) NOT NULL,
  `applied_on` datetime NOT NULL,
  PRIMARY KEY (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_books`
--

DROP TABLE IF EXISTS `lib_books`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_books` (
  `book_id` int(11) NOT NULL AUTO_INCREMENT,
  `library_id` int(11) NOT NULL,
  `collection_id` int(11) DEFAULT NULL,
  `author` varchar(500) DEFAULT NULL,
  `title` varchar(500) DEFAULT NULL,
  `edition` varchar(255) DEFAULT NULL,
  `call_number` varchar(50) DEFAULT NULL,
  `category` varchar(500) DEFAULT NULL,
  `pages` varchar(5) DEFAULT NULL,
  `lang` varchar(10) DEFAULT NULL,
  `original_id` varchar(20) NOT NULL,
  `new_call_number` varchar(50) DEFAULT NULL,
  `is_selected` bit(1) NOT NULL DEFAULT b'0',
  `publication_id` int(11) DEFAULT NULL,
  `sort_text` varchar(100) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by` smallint(6) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `created_by` smallint(6) DEFAULT NULL,
  `inactivation_reason` varchar(255) DEFAULT NULL,
  `is_active` bit(1) NOT NULL DEFAULT b'1',
  `isbn` varchar(30) DEFAULT NULL,
  `copyright_year` int(11) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publisher_place` varchar(255) DEFAULT NULL,
  `public_tags` varchar(255) DEFAULT NULL,
  `admin_tags` varchar(255) DEFAULT NULL,
  `public_notes` varchar(255) DEFAULT NULL,
  `public_notes_updated_at` datetime DEFAULT NULL,
  `public_notes_updated_by` int(11) DEFAULT NULL,
  `admin_notes` varchar(255) DEFAULT NULL,
  `admin_notes_updated_at` datetime DEFAULT NULL,
  `admin_notes_updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE KEY `library_id` (`library_id`,`original_id`),
  KEY `collection_id` (`collection_id`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_borrower_tokens`
--

DROP TABLE IF EXISTS `lib_borrower_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_borrower_tokens` (
  `TokenId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TokenHash` char(64) NOT NULL COMMENT 'sha256 hex of the plaintext token; the plaintext is never stored',
  `PersonId` int(10) unsigned NOT NULL,
  `LibraryId` int(10) unsigned NOT NULL,
  `CreatedOn` datetime NOT NULL,
  `ExpiresOn` datetime NOT NULL,
  `LastUsedOn` datetime DEFAULT NULL,
  `RevokedOn` datetime DEFAULT NULL,
  PRIMARY KEY (`TokenId`),
  UNIQUE KEY `TokenHash` (`TokenHash`),
  KEY `PersonLibrary` (`PersonId`,`LibraryId`),
  KEY `ExpiresOn` (`ExpiresOn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_checkouts`
--

DROP TABLE IF EXISTS `lib_checkouts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_checkouts` (
  `CheckoutId` int(11) NOT NULL AUTO_INCREMENT,
  `PersonId` int(11) NOT NULL,
  `BookId` int(11) NOT NULL,
  `CheckedOutOn` datetime NOT NULL,
  `CheckedOutBy` int(11) DEFAULT NULL,
  `DueOn` datetime DEFAULT NULL,
  `TimesRenewed` smallint(6) NOT NULL DEFAULT 0,
  `LastRenewedOn` datetime DEFAULT NULL,
  `CheckedInOn` datetime DEFAULT NULL,
  `CheckedInBy` int(11) DEFAULT NULL,
  `AdminNotes` varchar(300) DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`CheckoutId`),
  KEY `BookId` (`BookId`,`CheckedInOn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_collections`
--

DROP TABLE IF EXISTS `lib_collections`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_collections` (
  `CollectionId` int(11) NOT NULL AUTO_INCREMENT,
  `LibraryId` int(11) NOT NULL,
  `CollectionName` varchar(128) NOT NULL,
  `Abbreviation` varchar(12) NOT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `SortTextFormat` varchar(255) DEFAULT NULL,
  `CallNumberRegex` varchar(255) DEFAULT NULL,
  `CallNumberHelpText` varchar(255) DEFAULT NULL,
  `CallNumberExplanation` varchar(1000) DEFAULT NULL,
  `MainShowDisplay` varchar(50) NOT NULL DEFAULT 'show-categories',
  `LabelLine1` varchar(255) DEFAULT NULL,
  `LabelLine2` varchar(255) DEFAULT NULL,
  `LabelLine3` varchar(255) DEFAULT NULL,
  `DefaultCheckoutTimePeriodInDays` int(11) DEFAULT NULL,
  `EnforceCallNumberRegex` bit(1) DEFAULT NULL,
  `RequireCallNumbers` bit(1) DEFAULT NULL,
  `IsActive` bit(1) NOT NULL DEFAULT b'1',
  `AdminNotes` varchar(1000) DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`CollectionId`),
  UNIQUE KEY `LibraryId` (`LibraryId`,`CollectionName`),
  UNIQUE KEY `LibraryId_2` (`LibraryId`,`Abbreviation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_imports`
--

DROP TABLE IF EXISTS `lib_imports`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_imports` (
  `ImportId` int(11) NOT NULL AUTO_INCREMENT,
  `ImportName` varchar(100) NOT NULL,
  `LibraryId` int(11) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `Status` varchar(100) NOT NULL DEFAULT 'pending',
  `ColumnMapping` varchar(2000) DEFAULT NULL,
  `Worksheet` varchar(255) DEFAULT NULL,
  `FilePath` varchar(1000) NOT NULL,
  `IsCompleteImport` tinyint(1) NOT NULL DEFAULT 0,
  `BooksCreated` int(11) DEFAULT NULL,
  `BooksUpdated` int(11) DEFAULT NULL,
  `BooksDeleted` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`ImportId`),
  KEY `lib_imports_lib_libraries_FK` (`LibraryId`),
  CONSTRAINT `lib_imports_lib_libraries_FK` FOREIGN KEY (`LibraryId`) REFERENCES `lib_libraries` (`LibraryId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lib_libraries`
--

DROP TABLE IF EXISTS `lib_libraries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `lib_libraries` (
  `LibraryId` int(11) NOT NULL AUTO_INCREMENT,
  `LibraryName` varchar(100) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `CallNumberPlaceholder` varchar(50) DEFAULT NULL,
  `CallNumberHelpText` varchar(255) DEFAULT NULL,
  `CallNumberExplanation` varchar(1000) DEFAULT NULL,
  `FiliationId` int(11) DEFAULT NULL,
  `ContactPerson` int(11) DEFAULT NULL,
  `ContactEmail` varchar(255) DEFAULT NULL,
  `MainShowDisplay` varchar(50) NOT NULL DEFAULT 'show-categories',
  `SortTextFormat` varchar(255) DEFAULT NULL,
  `UseCollections` bit(1) NOT NULL DEFAULT b'0',
  `AllowCollectionlessBooks` bit(1) NOT NULL DEFAULT b'1',
  `MainCollectionId` int(11) DEFAULT NULL,
  `RequireCallNumbers` bit(1) NOT NULL DEFAULT b'0',
  `CallNumberRegex` varchar(255) DEFAULT NULL,
  `EnforceCallNumberRegex` bit(1) NOT NULL DEFAULT b'0',
  `LabelLine1` varchar(255) DEFAULT NULL,
  `LabelLine2` varchar(255) DEFAULT NULL,
  `LabelLine3` varchar(255) DEFAULT NULL,
  `BarcodeText` varchar(50) DEFAULT NULL,
  `CreateCheckoutsIfCheckingInANonCheckedOutBook` bit(1) NOT NULL DEFAULT b'1',
  `DefaultCheckoutPersonId` int(11) DEFAULT NULL,
  `DefaultCheckoutTimePeriodInDays` int(11) NOT NULL DEFAULT 14,
  `MaximumBookRenewals` int(10) unsigned DEFAULT NULL,
  `EnableCheckouts` bit(1) NOT NULL DEFAULT b'0',
  `IsPublicallyListed` bit(1) NOT NULL DEFAULT b'0',
  `CheckoutPersonListKind` varchar(50) NOT NULL DEFAULT 'all-borrowers',
  `CheckoutBooksRole` varchar(50) DEFAULT NULL,
  `ViewRole` varchar(50) DEFAULT 'lib_user',
  `IsActive` bit(1) NOT NULL DEFAULT b'1',
  `AdminNotes` varchar(1000) DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`LibraryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mailings`
--

DROP TABLE IF EXISTS `mailings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `mailings` (
  `MailingId` int(11) NOT NULL AUTO_INCREMENT,
  `ToAddresses` varchar(2000) NOT NULL,
  `MailingOn` datetime DEFAULT NULL,
  `MailingBy` int(11) DEFAULT NULL,
  `Subject` varchar(255) DEFAULT NULL,
  `Body` mediumtext DEFAULT NULL,
  `Sender` varchar(255) DEFAULT NULL,
  `MailingText` mediumtext DEFAULT NULL,
  `MailingTags` varchar(255) DEFAULT NULL,
  `TrackingToken` varchar(100) DEFAULT NULL,
  `OpenedFromHeaders` varchar(255) DEFAULT NULL COMMENT 'JSON',
  `OpenedOn` datetime DEFAULT NULL,
  `EmailTemplate` varchar(100) DEFAULT NULL,
  `EmailLocale` varchar(50) DEFAULT NULL,
  `Status` varchar(50) NOT NULL,
  `QueueUntil` datetime DEFAULT NULL,
  `Attempt` int(11) NOT NULL DEFAULT 1,
  `MaxAttempts` int(11) NOT NULL DEFAULT 3,
  `ErrorMessage` varchar(255) DEFAULT NULL,
  `StackTrace` mediumtext DEFAULT NULL,
  PRIMARY KEY (`MailingId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `mus_compositions`
--

DROP TABLE IF EXISTS `mus_compositions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `mus_compositions` (
  `CompositionId` int(11) NOT NULL AUTO_INCREMENT,
  `CompositionName` varchar(200) NOT NULL,
  `DisambiguatingDescription` varchar(100) DEFAULT NULL,
  `Slug` varchar(50) DEFAULT NULL,
  `InLanguage` varchar(3) DEFAULT NULL,
  `Country` varchar(6) DEFAULT NULL,
  `YearPublished` varchar(4) DEFAULT NULL,
  `ComposerText` varchar(500) DEFAULT NULL,
  `LyricistText` varchar(500) DEFAULT NULL,
  `Tags` varchar(255) DEFAULT NULL,
  `DerivedFromCompositionId` int(11) DEFAULT NULL,
  `Lyrics` mediumtext DEFAULT NULL,
  `ChordProSpec` mediumtext DEFAULT NULL,
  `LilyPondSpec` mediumtext DEFAULT NULL,
  `MusicalKey` varchar(10) DEFAULT NULL,
  `OriginalKey` varchar(10) DEFAULT NULL,
  `AlternateKey` varchar(10) DEFAULT NULL,
  `AlternateKeyLabel` varchar(50) DEFAULT NULL,
  `OpenLicenseUrl` varchar(255) DEFAULT NULL,
  `CopyrightInfo` varchar(1000) DEFAULT NULL,
  `CopyrightContactEmail` varchar(255) DEFAULT NULL,
  `Url1` varchar(1000) DEFAULT NULL,
  `Url1Label` varchar(50) DEFAULT NULL,
  `Url2` varchar(1000) DEFAULT NULL,
  `Url2Label` varchar(50) DEFAULT NULL,
  `Url3` varchar(1000) DEFAULT NULL,
  `Url3Label` varchar(50) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`CompositionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `predicates`
--

DROP TABLE IF EXISTS `predicates`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `predicates` (
  `PredicateKind` varchar(50) NOT NULL,
  `SubjectEntityKind` varchar(50) NOT NULL,
  `ObjectEntityKind` varchar(50) NOT NULL,
  `PredicateText` varchar(256) DEFAULT NULL,
  `DescriptionEn` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`PredicateKind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `relationships`
--

DROP TABLE IF EXISTS `relationships`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `relationships` (
  `RelationshipId` int(11) NOT NULL AUTO_INCREMENT,
  `SubjectEntityId` int(11) NOT NULL,
  `ObjectEntityId` int(11) NOT NULL,
  `PredicateKind` varchar(50) NOT NULL,
  `Priority` int(11) NOT NULL DEFAULT 100,
  `PublicNotes` varchar(500) DEFAULT NULL,
  `AdminNotes` varchar(500) DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`RelationshipId`),
  KEY `relationships_fk0` (`PredicateKind`),
  CONSTRAINT `relationships_fk0` FOREIGN KEY (`PredicateKind`) REFERENCES `predicates` (`PredicateKind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_assignments`
--

DROP TABLE IF EXISTS `sch_assignments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_assignments` (
  `AssignmentId` int(11) NOT NULL AUTO_INCREMENT,
  `RoleId` int(11) NOT NULL,
  `PersonId` int(11) NOT NULL,
  `StartDate` date DEFAULT NULL,
  `StartDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `EndDate` date DEFAULT NULL,
  `EndDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(4) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(4) DEFAULT NULL,
  PRIMARY KEY (`AssignmentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_associations`
--

DROP TABLE IF EXISTS `sch_associations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_associations` (
  `AssociationId` int(11) NOT NULL AUTO_INCREMENT,
  `AssociationName` varchar(200) NOT NULL,
  `InternalName` varchar(200) DEFAULT NULL,
  `IsInternalNameTranslateable` tinyint(1) NOT NULL DEFAULT 0,
  `Parent` int(11) DEFAULT NULL,
  `Kind` varchar(50) NOT NULL,
  `Country` varchar(6) DEFAULT NULL,
  `TimeZone` varchar(100) DEFAULT NULL,
  `FoundationDate` date DEFAULT NULL,
  `FoundationDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `SuppressionDate` date DEFAULT NULL,
  `IsLifeCommunity` tinyint(1) NOT NULL DEFAULT 0,
  `IsNameTranslateable` tinyint(1) NOT NULL DEFAULT 0,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `PublicNotes` mediumtext DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `AdminTags` varchar(255) DEFAULT NULL,
  `AdminNotes` mediumtext DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `Email` varchar(200) DEFAULT NULL,
  `Email2` int(200) DEFAULT NULL,
  `Phone1` varchar(70) DEFAULT NULL,
  `Phone1Label` varchar(50) DEFAULT NULL,
  `Phone2` varchar(70) DEFAULT NULL,
  `Phone2Label` varchar(50) DEFAULT NULL,
  `Phone3` varchar(70) DEFAULT NULL,
  `Phone3Label` varchar(50) DEFAULT NULL,
  `Url1` varchar(1000) DEFAULT NULL,
  `Url1Label` varchar(50) DEFAULT NULL,
  `Url2` varchar(1000) DEFAULT NULL,
  `Url2Label` varchar(50) DEFAULT NULL,
  `Url3` varchar(1000) DEFAULT NULL,
  `Url3Label` varchar(50) DEFAULT NULL,
  `FacebookUrl` varchar(1000) DEFAULT NULL,
  `TwitterUser` varchar(50) DEFAULT NULL,
  `InstagramUser` varchar(50) DEFAULT NULL,
  `Post1Street1` varchar(200) DEFAULT NULL,
  `Post1Street2` varchar(200) DEFAULT NULL,
  `Post1CityState` varchar(70) DEFAULT NULL,
  `Post1Zip` varchar(20) DEFAULT NULL,
  `Post1Country` varchar(3) DEFAULT NULL,
  `Post2Street1` varchar(200) DEFAULT NULL,
  `Post2Street2` varchar(200) DEFAULT NULL,
  `Post2CityState` varchar(70) DEFAULT NULL,
  `Post2Zip` varchar(20) DEFAULT NULL,
  `Post2Country` varchar(3) DEFAULT NULL,
  `GooglePlaceId` varchar(200) DEFAULT NULL,
  `ContactNotes` varchar(1000) DEFAULT NULL,
  `ContactInfoUpdatedOn` datetime DEFAULT NULL,
  `ContactInfoUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  `OverrideNameFormat` tinyint(1) NOT NULL DEFAULT 0,
  `IsAuthor` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Lets association appear in author lists',
  `Location` geometry DEFAULT NULL,
  `Latitude` varchar(15) DEFAULT NULL,
  `Longitude` varchar(15) DEFAULT NULL,
  `OpeningHoursHuman` varchar(500) DEFAULT NULL,
  `OpeningHoursHumanUpdatedOn` datetime DEFAULT NULL,
  `OpeningHoursHumanUpdatedBy` int(11) DEFAULT NULL,
  `OpeningHoursSpecification` mediumtext DEFAULT NULL,
  `OpeningHoursSpecificationUpdatedOn` datetime DEFAULT NULL,
  `OpeningHoursSpecificationUpdatedBy` int(11) DEFAULT NULL,
  `EventsHuman` varchar(1000) DEFAULT NULL,
  `EventsHumanUpdatedOn` datetime DEFAULT NULL,
  `EventsHumanUpdatedBy` int(11) DEFAULT NULL,
  `EventsJson` mediumtext DEFAULT NULL,
  `EventsJsonUpdatedOn` datetime DEFAULT NULL,
  `EventsJsonUpdatedBy` int(11) DEFAULT NULL,
  `SlugEn` varchar(50) DEFAULT NULL,
  `SlugEs` varchar(50) DEFAULT NULL,
  `SlugDe` varchar(50) DEFAULT NULL,
  `SlugPt` varchar(50) DEFAULT NULL,
  `SlugIt` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`AssociationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_changes`
--

DROP TABLE IF EXISTS `sch_changes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_changes` (
  `ChangeID` int(11) NOT NULL AUTO_INCREMENT,
  `ChangedEntity` varchar(100) NOT NULL,
  `ChangedField` varchar(100) NOT NULL,
  `ChangedIDValue` int(11) NOT NULL,
  `NewValue` mediumtext DEFAULT NULL,
  `OldValue` mediumtext DEFAULT NULL,
  `UpdatedOn` datetime NOT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`ChangeID`),
  KEY `ChangedEntity` (`ChangedEntity`,`ChangedIDValue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_dictionary_dictionary`
--

DROP TABLE IF EXISTS `sch_dictionary_dictionary`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_dictionary_dictionary` (
  `Dat_Id` int(7) NOT NULL AUTO_INCREMENT,
  `Dat_Group_Id` int(6) NOT NULL,
  `Dat_Type` varchar(50) NOT NULL,
  `Dat_Title` varchar(255) NOT NULL,
  `Dat_Text` longtext NOT NULL,
  `Dat_Notes` longtext NOT NULL,
  `Dat_Categories` varchar(1000) NOT NULL,
  `Dat_Lang` varchar(255) NOT NULL,
  `Dat_Create_User_Id` int(11) NOT NULL,
  `Dat_Create_DateTime` datetime NOT NULL,
  `Dat_Update_User_Id` int(11) NOT NULL,
  `Dat_Update_DateTime` datetime NOT NULL,
  PRIMARY KEY (`Dat_Id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Various small data';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_dictionary_entries`
--

DROP TABLE IF EXISTS `sch_dictionary_entries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_dictionary_entries` (
  `EntryId` int(11) NOT NULL AUTO_INCREMENT,
  `KeyDe` varchar(255) NOT NULL,
  `Slug` varchar(255) NOT NULL,
  `Locale` varchar(6) NOT NULL,
  `DirectTranslation` varchar(255) DEFAULT NULL,
  `Entry` varchar(1000) DEFAULT NULL,
  `Links` varchar(1000) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`EntryId`),
  UNIQUE KEY `Slug` (`Slug`,`Locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_dictionary_users`
--

DROP TABLE IF EXISTS `sch_dictionary_users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_dictionary_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(100) DEFAULT NULL,
  `lastname` varchar(100) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `role` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_migration`
--

DROP TABLE IF EXISTS `sch_migration`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_migration` (
  `filename` varchar(190) NOT NULL,
  `sha256` char(64) NOT NULL,
  `phase` varchar(8) NOT NULL,
  `kind` varchar(8) NOT NULL,
  `applied_on` datetime NOT NULL,
  `applied_by` varchar(64) NOT NULL,
  `duration_ms` int(10) unsigned DEFAULT NULL,
  `row_counts` text DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_persons`
--

DROP TABLE IF EXISTS `sch_persons`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_persons` (
  `PersonId` int(11) NOT NULL AUTO_INCREMENT,
  `LastName` varchar(100) DEFAULT NULL,
  `FirstName` varchar(100) DEFAULT NULL,
  `LastNameWithoutAccents` varchar(100) DEFAULT NULL,
  `FirstNameWithoutAccents` varchar(100) DEFAULT NULL,
  `PersonTags` varchar(255) DEFAULT NULL,
  `LifeCommunity` varchar(50) DEFAULT NULL,
  `Title` varchar(10) DEFAULT NULL,
  `TitleAutomatic` tinyint(1) NOT NULL DEFAULT 1,
  `Country` varchar(3) DEFAULT NULL,
  `BirthDate` date DEFAULT NULL,
  `BirthDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `NameDay` date DEFAULT NULL,
  `DeathDate` date DEFAULT NULL,
  `DeathDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `PublicNotes` mediumtext DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `PersonalInfoUpdatedOn` datetime DEFAULT NULL,
  `PersonalInfoUpdatedBy` int(11) DEFAULT NULL,
  `AdminTags` varchar(255) DEFAULT NULL,
  `AdminNotes` mediumtext DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `Email` varchar(255) DEFAULT NULL,
  `Email2` varchar(255) DEFAULT NULL,
  `CellPhone` varchar(70) DEFAULT NULL,
  `CellPhoneHasWhatsApp` tinyint(1) NOT NULL DEFAULT 0,
  `Phone1` varchar(70) DEFAULT NULL,
  `Phone1Label` varchar(50) DEFAULT NULL,
  `Phone2` varchar(70) DEFAULT NULL,
  `Phone2Label` varchar(50) DEFAULT NULL,
  `Phone3` varchar(70) DEFAULT NULL,
  `Phone3Label` varchar(50) DEFAULT NULL,
  `Url1` varchar(1000) DEFAULT NULL,
  `Url1Label` varchar(50) DEFAULT NULL,
  `Url2` varchar(1000) DEFAULT NULL,
  `Url2Label` varchar(50) DEFAULT NULL,
  `Url3` varchar(1000) DEFAULT NULL,
  `Url3Label` varchar(50) DEFAULT NULL,
  `FacebookUrl` varchar(1000) DEFAULT NULL,
  `SkypeUser` varchar(50) DEFAULT NULL,
  `TwitterUser` varchar(50) DEFAULT NULL,
  `InstagramUser` varchar(50) DEFAULT NULL,
  `SlackUser` varchar(50) DEFAULT NULL,
  `PostStreet1` varchar(200) DEFAULT NULL,
  `PostStreet2` varchar(200) DEFAULT NULL,
  `PostCityState` varchar(70) DEFAULT NULL,
  `PostZip` varchar(20) DEFAULT NULL,
  `PostCountry` varchar(3) DEFAULT NULL,
  `ContactNotes` mediumtext DEFAULT NULL,
  `ContactInfoUpdatedOn` datetime DEFAULT NULL,
  `ContactInfoUpdatedBy` int(11) DEFAULT NULL,
  `DataSource` varchar(50) DEFAULT NULL,
  `DataSourceId` int(11) DEFAULT NULL,
  `DataSourceUpdatedOn` datetime DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  `SpousePersonId` int(11) DEFAULT NULL,
  `PriestDate` date DEFAULT NULL,
  `PriestDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `BishopDate` date DEFAULT NULL,
  `BishopDatePrecision` varchar(20) NOT NULL DEFAULT 'day',
  `PrimaryLocale` varchar(10) DEFAULT NULL,
  `IsAuthor` bit(1) NOT NULL DEFAULT b'0',
  `IsBorrower` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`PersonId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_provenance`
--

DROP TABLE IF EXISTS `sch_provenance`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_provenance` (
  `ProvenanceId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Entity` varchar(50) NOT NULL COMMENT 'association; persons carry the same groups and may follow',
  `EntityId` int(11) NOT NULL,
  `FieldGroup` varchar(50) NOT NULL COMMENT 'derived from the entity config, never hand-listed',
  `SourceClass` varchar(20) NOT NULL COMMENT 'shrine|office|website|directory|inference; rank lives in PHP',
  `SourceUrl` varchar(1000) DEFAULT NULL,
  `SourceNote` varchar(255) DEFAULT NULL COMMENT 'free text: who said so, which bulletin, which phone call',
  `Outcome` varchar(20) NOT NULL COMMENT 'confirmed|corrected|competing',
  `AssertedOn` datetime NOT NULL COMMENT 'when the claim was true, UTC — not when it was filed',
  `RecordedOn` datetime NOT NULL COMMENT 'when we stored it, UTC',
  `RecordedBy` int(11) DEFAULT NULL COMMENT 'user id of the bot or human; null for an unauthenticated token',
  PRIMARY KEY (`ProvenanceId`),
  KEY `EntityGroupRecorded` (`Entity`,`EntityId`,`FieldGroup`,`RecordedOn`),
  KEY `RecordedOn` (`RecordedOn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_pub_categories`
--

DROP TABLE IF EXISTS `sch_pub_categories`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_pub_categories` (
  `PublicationCategoryId` int(11) NOT NULL AUTO_INCREMENT,
  `ParentId` int(11) DEFAULT NULL,
  `CategoryName` varchar(50) NOT NULL,
  `SortOrder` int(11) NOT NULL DEFAULT 100,
  `IsPlaceholder` bit(1) DEFAULT b'0',
  PRIMARY KEY (`PublicationCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_publications`
--

DROP TABLE IF EXISTS `sch_publications`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_publications` (
  `PublicationId` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(300) NOT NULL,
  `TitleNoAccents` varchar(300) DEFAULT NULL,
  `Subtitle` varchar(300) DEFAULT NULL,
  `SubtitleNoAccents` varchar(300) DEFAULT NULL,
  `ResourceId` varchar(50) DEFAULT NULL,
  `Authors` varchar(500) DEFAULT NULL,
  `AuthorsNoAccents` varchar(500) DEFAULT NULL,
  `BookEdition` varchar(50) DEFAULT NULL,
  `InLanguage` varchar(30) DEFAULT NULL,
  `Description` mediumtext DEFAULT NULL,
  `Isbn` varchar(30) DEFAULT NULL,
  `Translator` varchar(50) DEFAULT NULL,
  `Illustrator` varchar(50) DEFAULT NULL COMMENT 'DEPRECATED',
  `Editor` varchar(255) DEFAULT NULL,
  `EditorNoAccents` varchar(255) DEFAULT NULL,
  `NumberOfPages` int(11) DEFAULT NULL,
  `CopyrightYear` int(11) DEFAULT NULL,
  `CopyrightInfo` varchar(500) DEFAULT NULL,
  `Publisher` varchar(255) DEFAULT NULL,
  `PublishingPlace` varchar(255) DEFAULT NULL,
  `DatePublished` date DEFAULT NULL,
  `DatePublishedText` varchar(12) DEFAULT NULL,
  `PublishingStatus` varchar(50) DEFAULT NULL,
  `BookFormatType` varchar(50) DEFAULT NULL,
  `MainPublicationId` int(11) DEFAULT NULL,
  `VolumeNumber` varchar(25) DEFAULT NULL,
  `ContainedIn` varchar(255) DEFAULT NULL COMMENT 'DEPRECATED',
  `ContainedInIsbn` varchar(30) DEFAULT NULL COMMENT 'DEPRECATED',
  `Genre` varchar(50) DEFAULT NULL,
  `PublicTags` varchar(1000) DEFAULT NULL,
  `AdminTags` varchar(255) DEFAULT NULL COMMENT 'DEPRECATED',
  `IsAccessableForFree` tinyint(1) NOT NULL DEFAULT 0,
  `IsInternalForPatres` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'DEPRECATED',
  `IsScientificWork` tinyint(1) NOT NULL DEFAULT 0,
  `IsAwaitingMerge` tinyint(1) NOT NULL DEFAULT 0,
  `HasBeenMerged` tinyint(1) NOT NULL DEFAULT 0,
  `MergedIntoPublicationId` int(11) DEFAULT NULL,
  `JkQuality` varchar(20) DEFAULT NULL,
  `JkQualityNotes` varchar(255) DEFAULT NULL,
  `JkPeriod` int(11) DEFAULT NULL,
  `JkEventId` int(11) DEFAULT NULL,
  `Url1` varchar(1000) DEFAULT NULL,
  `Url1Label` varchar(50) DEFAULT NULL,
  `Url2` varchar(1000) DEFAULT NULL,
  `Url2Label` varchar(50) DEFAULT NULL,
  `Url3` varchar(1000) DEFAULT NULL,
  `Url3Label` varchar(50) DEFAULT NULL,
  `DataSource` varchar(50) DEFAULT NULL,
  `DataSourceId` int(11) DEFAULT NULL,
  `DataSourceUpdatedOn` datetime DEFAULT NULL,
  `PublicNotes` mediumtext DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `AdminNotes` mediumtext DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  `HasNoISBN` tinyint(1) NOT NULL DEFAULT 0,
  `IsRevisedWithBookInHand` tinyint(1) NOT NULL DEFAULT 0,
  `PublishDataAsJsonLd` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'DEPRECATED',
  `IsFormallyPublished` tinyint(1) NOT NULL DEFAULT 0,
  `TranslatedFromPublicationId` int(11) DEFAULT NULL,
  `HasNoExplictEditionNumber` bit(1) NOT NULL DEFAULT b'0',
  `EditionNotes` mediumtext DEFAULT NULL,
  `CategoryId` int(11) DEFAULT NULL,
  `Slug` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PublicationId`),
  KEY `idx_main_publication` (`MainPublicationId`),
  KEY `idx_translated_from` (`TranslatedFromPublicationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_roles`
--

DROP TABLE IF EXISTS `sch_roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_roles` (
  `RoleId` int(11) NOT NULL AUTO_INCREMENT,
  `RoleTitle` varchar(50) NOT NULL,
  `AssociationId` int(11) NOT NULL,
  `IsMainRole` tinyint(1) NOT NULL DEFAULT 0,
  `IsSinglePosition` tinyint(1) NOT NULL DEFAULT 0,
  `ShouldAlwaysBeFilled` tinyint(1) NOT NULL DEFAULT 0,
  `Sort` smallint(4) NOT NULL DEFAULT 1000,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  `IsMainContact` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`RoleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `sch_visits`
--

DROP TABLE IF EXISTS `sch_visits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sch_visits` (
  `VisitId` int(11) NOT NULL AUTO_INCREMENT,
  `Entity` varchar(50) NOT NULL,
  `EntityId` int(11) DEFAULT NULL COMMENT 'If null, it refers to some entity index',
  `UserId` int(11) DEFAULT NULL,
  `VisitedAt` datetime NOT NULL,
  PRIMARY KEY (`VisitId`),
  KEY `idx_entity_visited` (`Entity`,`EntityId`,`VisitedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `texts`
--

DROP TABLE IF EXISTS `texts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `texts` (
  `TextId` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(255) NOT NULL,
  `TextKind` varchar(50) NOT NULL,
  `Language` varchar(2) NOT NULL,
  `Slug` varchar(50) DEFAULT NULL,
  `IsDraft` tinyint(4) DEFAULT NULL,
  `MarkdownText` longtext DEFAULT NULL,
  `HtmlText` longtext DEFAULT NULL,
  `PlainText` longtext DEFAULT NULL,
  `SearchText` longtext DEFAULT NULL,
  `WordCount` int(11) DEFAULT NULL,
  `JkTextQuality` varchar(10) DEFAULT NULL,
  `Tags` varchar(255) DEFAULT NULL,
  `AdminTags` varchar(255) DEFAULT NULL,
  `AclResourceId` varchar(50) NOT NULL DEFAULT 'txt_public',
  `PublicNotes` varchar(1000) DEFAULT NULL,
  `PublicNotesUpdatedBy` int(11) DEFAULT NULL,
  `PublicNotesUpdatedOn` datetime DEFAULT NULL,
  `AdminNotes` varchar(1000) DEFAULT NULL,
  `AdminNotesUpdatedBy` int(11) DEFAULT NULL,
  `AdminNotesUpdatedOn` datetime DEFAULT NULL,
  `LegacyEventId` int(11) DEFAULT NULL,
  `LegacyFile` varchar(300) DEFAULT NULL,
  `LegacyPathDate` date DEFAULT NULL,
  `LegacyFileDateModified` date DEFAULT NULL,
  `UpdatedOn` datetime DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `CreatedOn` datetime DEFAULT NULL,
  `CreatedBy` int(11) DEFAULT NULL,
  PRIMARY KEY (`TextId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `trans_phrases`
--

DROP TABLE IF EXISTS `trans_phrases`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `trans_phrases` (
  `translation_phrase_id` int(11) NOT NULL AUTO_INCREMENT,
  `project` varchar(50) NOT NULL,
  `text_domain` varchar(50) NOT NULL,
  `phrase` mediumtext NOT NULL,
  `phrase_hash` binary(32) NOT NULL,
  `added_on` datetime NOT NULL,
  `origin_route` varchar(255) DEFAULT NULL,
  `retired_on` datetime DEFAULT NULL,
  PRIMARY KEY (`translation_phrase_id`),
  UNIQUE KEY `phrase_identity` (`project`,`text_domain`,`phrase_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `trans_phrases_blog_backup`
--

DROP TABLE IF EXISTS `trans_phrases_blog_backup`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `trans_phrases_blog_backup` (
  `translation_phrase_id` int(11) NOT NULL DEFAULT 0,
  `project` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `text_domain` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `phrase` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `phrase_hash` binary(32) NOT NULL,
  `added_on` datetime NOT NULL,
  `origin_route` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `retired_on` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `trans_translations`
--

DROP TABLE IF EXISTS `trans_translations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `trans_translations` (
  `translation_id` int(8) NOT NULL AUTO_INCREMENT,
  `translation_phrase_id` int(11) NOT NULL,
  `locale` varchar(20) NOT NULL,
  `translation` mediumtext NOT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime NOT NULL,
  PRIMARY KEY (`translation_id`),
  UNIQUE KEY `translation_phrase_id` (`translation_phrase_id`,`locale`),
  CONSTRAINT `trans_translations_ibfk_1` FOREIGN KEY (`translation_phrase_id`) REFERENCES `trans_phrases` (`translation_phrase_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `trans_translations_blog_backup`
--

DROP TABLE IF EXISTS `trans_translations_blog_backup`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `trans_translations_blog_backup` (
  `translation_id` int(8) NOT NULL DEFAULT 0,
  `translation_phrase_id` int(11) NOT NULL,
  `locale` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `translation` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `trans_translations_history`
--

DROP TABLE IF EXISTS `trans_translations_history`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `trans_translations_history` (
  `history_id` int(11) NOT NULL AUTO_INCREMENT,
  `project` varchar(50) NOT NULL,
  `phrase_hash` binary(32) NOT NULL,
  `locale` varchar(10) NOT NULL,
  `text_domain` varchar(50) NOT NULL,
  `translation_phrase_id` int(11) NOT NULL,
  `old_translation` text NOT NULL,
  `operation` varchar(10) NOT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `written_by` int(11) DEFAULT NULL,
  `written_on` datetime DEFAULT NULL,
  `replaced_by` int(11) DEFAULT NULL,
  `replaced_on` datetime NOT NULL,
  PRIMARY KEY (`history_id`),
  KEY `thread` (`project`,`phrase_hash`,`locale`,`history_id`),
  KEY `phrase` (`translation_phrase_id`,`history_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `display_name` varchar(50) DEFAULT NULL,
  `create_datetime` datetime NOT NULL,
  `update_datetime` datetime NOT NULL,
  `state` int(11) NOT NULL,
  `lang` varchar(255) NOT NULL DEFAULT 'deu;eng;spa' COMMENT 'semicolor separated list of ISO-639-3 Language Code',
  `email_verified` tinyint(1) NOT NULL DEFAULT 0,
  `multi_person_user` tinyint(1) NOT NULL DEFAULT 0,
  `PersID` int(11) DEFAULT NULL,
  `verification_token` char(64) DEFAULT NULL,
  `verification_expiration` datetime DEFAULT NULL,
  `create_by` int(11) DEFAULT NULL,
  `update_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `UNIQ_1483A5E9E7927C74` (`email`),
  UNIQUE KEY `UNIQ_1483A5E9F85E0677` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_api_token`
--

DROP TABLE IF EXISTS `user_api_token`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_api_token` (
  `token_id` int(11) NOT NULL AUTO_INCREMENT,
  `jti` char(43) NOT NULL,
  `user_id` int(11) NOT NULL,
  `label` varchar(100) DEFAULT NULL,
  `issued_on` datetime NOT NULL,
  `issued_by` int(11) DEFAULT NULL,
  `expires_on` datetime NOT NULL,
  `revoked_on` datetime DEFAULT NULL,
  `revoked_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`token_id`),
  UNIQUE KEY `uniq_user_api_token_jti` (`jti`),
  KEY `idx_user_api_token_user` (`user_id`,`issued_on`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_remember_me`
--

DROP TABLE IF EXISTS `user_remember_me`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_remember_me` (
  `sid` varchar(16) NOT NULL,
  `token` varchar(16) NOT NULL,
  `user_id` int(11) NOT NULL,
  UNIQUE KEY `sid` (`sid`,`token`,`user_id`),
  KEY `user_remember_me` (`user_id`),
  CONSTRAINT `user_remember_me` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_role`
--

DROP TABLE IF EXISTS `user_role`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` varchar(255) NOT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `parent_id` int(11) DEFAULT NULL,
  `create_by` int(11) DEFAULT NULL,
  `create_datetime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_role` (`role_id`),
  KEY `idx_parent_id` (`parent_id`),
  CONSTRAINT `fk_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `user_role` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `user_role_linker`
--

DROP TABLE IF EXISTS `user_role_linker`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_role_linker` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `role_id` int(11) NOT NULL,
  `create_by` int(11) DEFAULT NULL,
  `create_datetime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`,`role_id`),
  KEY `idx_role_id` (`role_id`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `fk_role_id` FOREIGN KEY (`role_id`) REFERENCES `user_role` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
--

--
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed
