<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headScript()->appendFile($this->basePath() . '/js/gen-schoenstatt-advanced-search.js');
$areResults = isset($this->objects) && 0!=count($this->objects);
$form = $this->form;
$this->formSelect()->setTranslatorEnabled(false);
$form->prepare();
echo $this->form()->openTag($form);?>

<div class="row">
<?php
echo $this->formRow($form->get('search'));
echo $this->formRow($form->get('associationKind'));
echo $this->formRow($form->get('associationCountry'));
$this->formSelect()->setTranslatorEnabled(true); //we want roleTitle translated
echo $this->formRow($form->get('roleTitle'));
?>
</div>
<div class="form-group ">
<?php
echo $this->formSubmit($form->get('submit'));
echo '&nbsp;';
echo $this->formButton($form->get('clear'));?>
</div>
<?php
// echo $this->formRow($form->get('showPhotos'));

if ($areResults) {
     echo $this->partial('assignments-table-partial', [
         'columns' => [
            'association',
            'role',
            'person',
            'email',
            'telephone',
        ],
        'options' => [
//             'showPhotos' => true//$this->showPhotos,
        ],
        'assignments' => $this->objects
    ]);
}
