<?php
use Schoenstatt\Form\AssignmentForm;

$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$this->headScript()->appendFile($this->basePath() . "/". $this->asset("js/selectize-validation-pack.js"));

$headText = 'Create New Assignment';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php /** @var AssignmentForm $form */
$form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url('assignments/create'));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

$rolesJson = $form->getRolesJson();
$script = <<<JS
$(function() {
    var \$associationId = $("select[name='associationId']");
    var roles = $rolesJson;
    var \$roleSelect = $("select[name='roleId']");
    \$associationId.change(function() {
        if (\$associationId.val() !== '') {
            newOptions = roles[\$associationId.val()];
            if(\$roleSelect.prop) {
              var options = \$roleSelect.prop('options');
            }
            else {
              var options = \$roleSelect.attr('options');
            }
            $('option', \$roleSelect).remove();

            $.each(newOptions, function(val, text) {
                options[options.length] = new Option(text, val);
            });
        }
    })
});

$("select[name='personId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='associationId']").selectize({
    create: false,
    sortField: 'text'
});
JS;

$this->inlineScript()->captureStart();
echo $this->jshrink($script);
$this->inlineScript()->captureEnd();
?>
