<?php
// $this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
// $this->headScript()->appendFile($this->basePath() . "/". $this->asset("js/person-edit.js"));

$headText = 'Create New Assignment';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url('assignments/create'));
$form->prepare();
echo $this->form()->openTag($form);
//don't include
echo $this->partial('fields-partial', array(
    'form' => $form,
    'rolesJson' => $this->rolesJson,
));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

$rolesJson = $this->rolesJson;
$script = <<<JS
$(function() {
    var \$associationId = $("select[name='associationId']");
    var roles = $rolesJson;
    var \$roleSelect = $("select[name='roleId']");
    \$associationId.change(function() {
        if (\$associationId.val() !== '') {
            newOptions = roles[\$associationId.val()];
            if(\$roleSelect.prop) {
              var options = \$roleSelect.prop('options');
            }
            else {
              var options = \$roleSelect.attr('options');
            }
            $('option', \$roleSelect).remove();

            $.each(newOptions, function(val, text) {
                options[options.length] = new Option(text, val);
            });
        }
    })
});
JS;
$this->inlineScript()->captureStart();
echo $this->jshrink($script);
$this->inlineScript()->captureEnd();
?>
