<?php
$form = $this->form;
echo $this->formHidden($form->get('assignmentId'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('associationId'));
echo $this->formRow($form->get('personId'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('roleId'));
echo $this->formRow($form->get('startDate'));
echo $this->formRow($form->get('endDate'));
echo $this->formRow($form->get('security'));
