<?php
$areResults = isset($this->entities) && 0!=count($this->entities);

if ($this->isAllowed('route/assignments/create')) :?>
<a href="<?php echo $this->url('assignments/create')?>"><?php echo $this->translate('Add assignment');?></a>
<?php endif;
if ($areResults) :?>
<table class="table">
    <thead>
    <tr>
    <th><?php echo $this->translate('Name');?></th>
    <th><?php echo $this->translate('Community');?></th>
    <th><?php echo $this->translate('Email');?></th>
    <th><?php echo $this->translate('Cell phone');?></th>
    </tr>
    </thead>
    <tbody>
<?php
foreach ($this->entities as $entity) :?>
<tr>
    <td><?php if ($entity['association']) {
        echo $this->formatEntity('association', $entity['association']);
    }?></td>
    <td><?php echo $this->formatEntity('person', $entity['person']);?></td>
    <td><?php echo $this->email($entity['person']['email']);?></td>
    <td><?php echo $this->telephone($entity['person']['cellPhone']);?></td>
</tr>
<?php endforeach;?>
    </tbody>
</table>
<?php endif;?>