<?php
$areResults = isset($this->entities) && 0!=count($this->entities);
echo $this->partial('schoenstatt/schoenstatt/search-bar', ['form' => $form, 'centerOnPage' => !$areResults]);?>
<div class="row">
<?php if ($this->isAllowed('route/assignments/create')) :?>
<a href="<?php echo $this->url('assignments/create')?>"><?php echo $this->translate('Add assignment');?></a>
<?php endif;
if ($this->isAllowed('route/persons/create')) :?>
|&nbsp;<a href="<?php echo $this->url('persons/create')?>"><?php echo $this->translate('Add person');?></a>
<?php endif;
if ($this->isAllowed('route/associations/create')) :?>
|&nbsp;<a href="<?php echo $this->url('associations/create')?>"><?php echo $this->translate('Add association');?></a>
<?php endif;
if ($this->isAllowed('route/roles/create')) :?>
|&nbsp;<a href="<?php echo $this->url('roles/create')?>"><?php echo $this->translate('Add role');?></a>
<?php endif;?>
</div>

<?php
if ($areResults) :?>
<table class="table">
    <thead>
    <tr>
    <th><?php echo $this->translate('Association');?></th>
    <th><?php echo $this->translate('Role');?></th>
    <th><?php echo $this->translate('Person');?></th>
    <th><?php echo $this->translate('Email');?></th>
    <th><?php echo $this->translate('Cell phone');?></th>
    </tr>
    </thead>
    <tbody>
<?php
foreach ($this->entities as $entity) :?>
<tr>
    <td><?php if ($entity['association']) {
        echo $this->formatEntity('association', $entity['association'], ['showLabel' => false]);
    }?></td>
    <td><?php if ($entity['assignment']) {
        echo $this->formatEntity('assignment', $entity['assignment'], [
            'displayAsLink' => false,
            'displayEditPencil' => true,
        ]);
    }?></td>
    <td><?php echo $this->formatEntity('person', $entity['person']);?></td>
    <td><?php echo $this->email($entity['person']['email']);?></td>
    <td><?php echo $this->telephone($entity['person']['cellPhone']);?></td>
</tr>
<?php endforeach;?>
    </tbody>
</table>
<?php endif;?>