<?php
$object = $this->entity;
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($object['name']);?>
<h1><?php echo $this->escapeHtml($this->entity['name']);?></h1>
<div class="row">

<div class="col-md-9">
<div class="panel panel-default" id="contactInfoPanel">
    <div class="panel-heading">
    	<div class="row">
    	<div class="col-xs-4">
        	<h3 class="panel-title"><?php echo $this->translate('Contact Info'); //@todo add contact notes and modified date?>
        </h3>
        </div>
        <div class="col-xs-5">
        	<?php if (!is_null($object['contactInfoUpdatedOn'])) :?>
        		<span class="pull-right"><small><?php echo sprintf($this->translate('Updated %s'),
        		    $this->diffForHumans($object['contactInfoUpdatedOn']));?></small></span>
        	<?php endif;?>
        </div>
        </div>
	</div>
    <div class="panel-body">
    	<div class="row">
    	<div class="col-md-7">
            <p><strong><?php echo $this->translate('Email'); ?>:</strong> <?php
            if (!is_null($object['email'])) { //@todo add checks for validated
                echo $this->email($object['email']);
                if (!is_null($object['email2'])) {
                    echo ', '.$this->email($object['email2']);
                }
            }?></p>
            <div class="row">
            <div class="col-md-12">
            	<div class="row"><div class="col-md-12">
            	<?php foreach ($object['urls'] as $urlRow) :?>
            	<a target="_blank" href="<?php echo $this->escapeHtmlAttr($urlRow['url']);?>">
            	    <img src="../<?php echo isset($urlRow['logo']) ? $this->escapeHtmlAttr($urlRow['logo']) : 'img/www.png';
            	    ?>" alt="<?php echo $this->escapeHtmlAttr($urlRow['label']);?>" class="img-circle" height="70px">
            	</a>&nbsp;
            	<?php endforeach; //@todo add email modified date?>
            	</div></div> <!-- Websites row and column -->
            </div> <!-- Links column -->
            </div> <!-- Links row -->
        </div>
        <div class="col-md-5">
            <?php foreach ($object['phones'] as $phoneRow) : ?>
                <p><strong><?php echo $this->translate($phoneRow['label']); ?>:</strong>
				<span><?php echo $this->telephone($phoneRow['number'],
						isset($phoneRow['whatsApp']) ? $phoneRow['whatsApp'] : false,
						$this->isAllowed('route/persons/person/edit-contact-info'));?></span></p>
            <?php endforeach;
            if (!is_null($object['phonesUpdatedOn'])) :  //@todo add a question mark here with text
                //@todo use diffForHumans view helper
        	    $phoneUpdated = Carbon::instance($object['phonesUpdatedOn']); //@todo position this Up-to-date better ?>
                <p class="text-right"><?php echo $this->tooltip('✓ Up-to-date', sprintf($this->translate('Updated by %s %s'), 'jeff', $phoneUpdated->diffForHumans()));?></p>
        	<?php endif;?>
        	<!--
        	Phone numbers should be updated or confirmed every 2 years to ensure up-to-date information.
        	Please help in confirming and/or updating out-dated information.
        	 -->
		</div> <!-- phones column -->
        </div>
    </div> <!-- contact info panel body -->
</div> <!-- contact info panel -->
</div> <!-- col-md-9 -->
</div>
<div class="row">
<div class="col-md-12">
<div class="panel panel-default" id="infoPanel">
    <div class="panel-heading">
    	<h3 class="panel-title"><?php echo $this->translate('Association Info'); ?></h3>
	</div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
        <p><strong><?php echo $this->translate('Foundation date');?>:</strong>
        <?php if (!is_null($object['foundationDate'])) {
        echo $this->dateFormat($object['foundationDate'], IntlDateFormatter::LONG, IntlDateFormatter::NONE);
        }?></p>
		<?php if (!is_null($object['suppressionDate'])) :?>
      		<p><strong><?php echo $this->translate('Suppression date');?>:</strong> <?php
                echo $this->dateFormat($object['suppressionDate'], IntlDateFormatter::LONG, IntlDateFormatter::NONE);
            ?></p>
		<?php endif;?>
	</div> <!-- info 1 column -->

    <div class="col-md-6">
      <h4 class="text-center"><strong><?php echo $this->translate('Association representatives');?></strong></h4>
    <?php foreach ($object['roles'] as $role) : ?>
    <p>
    	<?php if ($role['assignmentPersonId']) :?>
    		<?php echo $this->formatPersonName($role['assignmentFirstName'], $role['assignmentLastName'], null,
    	    $role['assignmentPersonId'], $role['assignmentCountry']);
            echo ' '.$this->shortDateRange($role['assignmentStartDate'], $role['assignmentEndDate']);
    		if ($this->isAllowed('route/roles/assignment/edit')) : ?>
        		<a href="<?php
        		echo $this->url('roles/assignment/edit', array('assignment_id' => $role['assignmentId'],
                    'action' => 'edit'));?>">
    			<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
    		<?php endif;?>
    	<?php endif;?>
    </p>
    <?php endforeach;?>
    <?php if (isset($object['roles'][0]) && $object['roles'][0]['roleId'] && $this->isAllowed('route/roles/create')): ?>
        <p><a class="btn btn-default btn-sm" href="<?php
            echo $this->url('roles/create', [],
                array('query' => array('roleId' => $object['roles'][0]['roleId'])));?>">
            <span class="glyphicon glyphicon-plus">&nbsp;</span><?php echo $this->translate('Add generation representative')?></a>
        </p>
    <?php endif;?>
	</div> <!-- info 2 column -->
    </div></div> <!-- contact info panel body -->
</div> <!-- course info 1 panel -->
</div><!-- info 1 column -->
</div> <!-- Info row -->

<div class="row"><div class="col-md-12">
<?php if ($this->isAllowed('route/associations/association/edit')):?>
      <a class="btn btn-primary" href="<?php echo $this->url('associations/association/edit',
          ['association_id' => $object['associationId']]);?>"><?php
    echo $this->translate("Edit details")?></a>
<?php endif;?>
</div></div>
