<?php
use Books\Model\LibraryTable;
$persons = $this->persons && is_array($this->persons) ? $this->persons : null;

/**
 * @param $entities mixed[]
 */
?>
<table class="table">
<thead><tr>
	<th><?php echo $this->translate('Library');?></th>
	<th><?php echo $this->translate('Book');?></th>
	<th><?php echo $this->translate('Checked out on');?></th>
<?php if (!is_null($persons)):?>
	<th><?php echo $this->translate('Checked out by');?></th>
<?php endif;?>
	<th><?php echo $this->translate('Due on');?></th>
	<th><?php echo $this->translate('Checked in on');?></th>
</tr></thead>
<tbody>
<?php foreach ($this->entities as $entityId => $entity) :
    $rowClass = null;
    if ($entity['status'] == LibraryTable::CHECKOUT_STATUS_OVERDUE) {
        $rowClass = 'danger';
    } elseif ($entity['status'] == LibraryTable::CHECKOUT_STATUS_RETURNED) {
        $rowClass = 'success';
    }?>
<tr <?php if (!is_null($rowClass)) {
    echo "class=\"$rowClass\"";
}?>>
	<td><?php echo $this->formatEntity('library', $entity['book']['library']);?></td>
	<td><?php echo $this->formatEntity('book', $entity['book']);?></td>
	<td><?php echo $this->dateFormat($entity['checkedOutOn'], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);?></td>
<?php if (!is_null($persons)):?>
	<td><?php if (key_exists($entity['personId'], $persons)) {
	   echo $this->persons[$entity['personId']];
	}?></td>
<?php endif;?>
	<td><?php if ($entity['dueOn']) {
	   echo $this->dateFormat($entity['dueOn'], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);
    }?></td>
	<td><?php if ($entity['checkedInOn']) {
	    echo $this->dateFormat($entity['checkedInOn'], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);
	}?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>