<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headScript()->appendFile($this->basePath() . '/js/gen-books-checkin.js');
$headText = 'Book Check-in';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('withinLibraryIds'));?>
<ul id="book-list" class="list-unstyled"></ul>
<?php echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
