<?php
$this->headScript()->appendFile($this->basePath() . '/'. $this->asset("js/checkin.js"));
$headText = 'Book Check-in';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('libraries/library/checkin', ['library_id' => $this->libraryId]));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('bookIds'));?>
<ul id="book-list" class="list-unstyled"></ul>
<?php echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
