<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headScript()->appendFile($this->basePath() . '/'. $this->asset("js/selectize.min.js"));
$headText = 'Book Check-in';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('libraries/library/checkin', ['library_id' => $this->libraryId]));
$form->prepare();
echo $this->form()->openTag($form);
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('bookIds'));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

$jsScript = <<<JS
$("select[name='bookIds[]']").selectize({
    create: false,
    sortField: 'text'
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
