<?php
use Laminas\Json\Json;
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headScript()->appendFile($this->basePath() . '/js/gen-books-checkouts.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/mass-checkouts.css');
$headText = 'Book Checkout';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
$checkouts = $form->get('checkout');
$firstCheckout = $checkouts->getTargetElement();
$this->formSelect()->setTranslatorEnabled(false);?>
<div class="table-responsive">
<table class="table">
<thead>
<tr>
    <th><?php echo $this->formLabel($firstCheckout->get('checkedOutOn'));?></th>
    <th><?php echo $this->formLabel($firstCheckout->get('personId'));?></th>
    <th><?php echo $this->formLabel($firstCheckout->get('withinLibraryIds'));?></th>
</tr>
</thead>
<tbody>
<?php foreach ($checkouts as $fieldset) :?>
<tr>
    <td><?php echo $this->formText($fieldset->get('checkedOutOn'));
       echo $this->formElementErrors($fieldset->get('checkedOutOn'));?></td>
    <td><?php echo $this->formSelect($fieldset->get('personId'));
       echo $this->formElementErrors($fieldset->get('personId'));?></td>
    <td><?php echo $this->formText($fieldset->get('withinLibraryIds'));
       echo $this->formElementErrors($fieldset->get('withinLibraryIds'));?></td>
</tr><?php
endforeach;?>
</tbody>
</table>
</div>
<ul id="book-list" class="list-unstyled"></ul>
<?php
//build the template for dynamically adding elements
$templateFieldset = $checkouts->getTargetElement();
ob_start();
?><tr><td><?php echo $this->formText($templateFieldset->get('checkedOutOn'));?></td>
<td><?php echo $this->formSelect($templateFieldset->get('personId'));?></td>
<td><?php echo $this->formText($templateFieldset->get('withinLibraryIds'));?></td></tr><?php
$templateText = ob_get_clean();
$re = '/name="([A-Za-z]+)"/';
$subst = 'name="checkout[__index__][$1]"';
$templateText = preg_replace($re, $subst, $templateText);?>
<span id="rowTemplate" data-template="<?php echo $this->escapeHtmlAttr($templateText);?>"></span>
<?php echo $this->formRow($form->get('security'));?>
<p><?php echo $this->formSubmit($form->get('submit'));?>&nbsp;
<a class="btn btn-default" id="addRows"><?php echo $this->translate('Add 4 rows');?></a></p>
<?php echo $this->form()->closeTag();
$personValueOptions = Json::encode($this->personValueOptions);
$jsScript = <<<JS
var personOptions = $personValueOptions;
$("select[name*='personId']").selectize({
	valueField: 'id',
	labelField: 'name',
	searchField: 'name',
	options: personOptions,
    create: false
});
$("input[name='checkout[0][checkedOutOn]']").focus();
$("#addRows").click(function() {
    var currentCount = $('form tr').length;
    var template = $('#rowTemplate').data('template');
    for (var i=0;i<4;i++) {
        templateHtml = template.replace(/__index__/g, currentCount+i);
        $('form tbody').append(templateHtml);
    }
    $("select[name*='personId']").selectize({
    	valueField: 'id',
    	labelField: 'name',
    	searchField: 'name',
    	options: personOptions,
        create: false
    });
    return false;
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
