<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-selectize.bootstrap.min.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . '/js/gen-books-checkouts.js');
$headText = 'Book checkout';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('libraries/library/checkout', ['library_id' => $this->libraryId]));
$form->prepare();
echo $this->form()->openTag($form);
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('withinLibraryIds'));?>
<ul id="book-list" class="list-unstyled"></ul>
<?php echo $this->formRow($form->get('personId'));
echo $this->formRow($form->get('adminNotes'));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

$jsScript = <<<JS
$("select[name='personId']").selectize({
    create: false
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
