<?php 
/**
 * @param array $assignments
 * @param bool $showActive = true
 * @param bool $showInactive = true
 * @param bool $wrapInPanel = false
 * @param array $columns = [role, person] (role, person, email, telephone)
 * @param string $header
 */
$showActive     = isset($this->showActive) ? $this->showActive : true;
$showInactive   = isset($this->showInactive) ? $this->showInactive : true;
$assignments    = is_array($this->assignments) ? $this->assignments : [];
$wrapInPanel    = isset($this->wrapInPanel) ? $this->wrapInPanel : false;
$columns        = isset($this->columns) && is_array($this->columns) ? $this->columns : ['role', 'person'];

$columnHeaders = [
    'role' => 'Role',
    'person' => 'Contact person',
    'email' => 'Email',
    'telephone' => 'Telephone',
];

//count assignments to print
$count = 0;
foreach ($assignments as $assignment) {
if ($assignment['person'] &&
	(($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive))) {
		$count++;
	}
}
if ($count>0):
    if ($wrapInPanel):?>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <?php if (isset($this->headerText)):?>
        	<div class="panel-heading"><?php echo $this->escapeHtml($this->headerText);?></div>
        <?php endif;?>
        <!--<div class="panel-body">
         <p>...</p> 
        </div>-->
    <?php endif;
	if (isset($this->headerText) && !$wrapInPanel):?>
	<p class="text-center"><strong><u><?php echo $this->escapeHtml($this->headerText);?></u></strong></p>
	<?php endif;?>
    <table class="table">
    <thead><tr>
    <?php foreach ($columns as $column) {
        if (key_exists($column, $columnHeaders)) {
            echo '<th>'. $this->translate($columnHeaders[$column]). '</th>';
        } else {
            array_unshift($columns, $column);
        }
    }?>
    </tr></thead>
    <tbody>
    <?php foreach ($assignments as $assignment) : 
    	if ($assignment['person'] && 
    		(($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive))
        ):?>
        	<tr>
            <?php foreach ($columns as $column) :
                switch ($column) :
                    case 'role': ?>
                		<td><?php echo $this->escapeHtml($assignment['roleTitle']).
                			' '.$this->shortDateRange($assignment['startDate'], $assignment['endDate']);
                		?></td>
                        <?php break;
                    case 'person': ?>
                        <td><?php echo $this->formatEntity('person', $assignment['person'], ['displayEditPencil' => false]);
                            if ($this->isAllowed('route/assignments/assignment/edit')) : ?>
                				<a href="<?php
                		          echo $this->url('assignments/assignment/edit', ['assignment_id' => $assignment['assignmentId'],
                                    'action' => 'edit']);?>">
            					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
            				<?php endif;
        				?></td><?php 
    				    break;
                    case 'email': ?>
                		<td><?php echo $this->email($assignment['person']['email']);
                		?></td><?php 
                        break;
                    case 'telephone': ?>
                		<td><?php echo $this->telephone($assignment['person']['cellPhone']);
                		?></td><?php 
                        break;
                endswitch;?>
        	<?php endforeach;?>
        	</tr>
    	<?php endif;
	endforeach;?>
    </tbody></table>
    <?php if ($wrapInPanel):?>
    </div>
    <?php endif;
endif;?>