<?php
/**
 * @name assignments-table-partial
 * @param array $assignments
 * @param bool $showActive = true
 * @param bool $showInactive = true
 * @param bool $wrapInPanel = false
 * @param array $columns = [role, person] (role, person, email, telephone,
 *      association[requires each assignment to have an 'assignment' key])
 * @param string $header MUST be pre-escaped
 * @param array $associationFormatOptions = []
 * @param array $personFormatOptions = []
 */
$showActive     = isset($this->showActive) ? $this->showActive : true;
$showInactive   = isset($this->showInactive) ? $this->showInactive : true;
$assignments    = is_array($this->assignments) ? $this->assignments : [];
$wrapInPanel    = isset($this->wrapInPanel) ? $this->wrapInPanel : false;
$columns        = isset($this->columns) && is_array($this->columns) ? $this->columns : ['role', 'person'];
$associationFormatOptions = isset($this->associationFormatOptions) && is_array($this->associationFormatOptions) ? $this->associationFormatOptions : [];
$personFormatOptions = isset($this->personFormatOptions) && is_array($this->personFormatOptions) ? $this->personFormatOptions : ['displayEditPencil' => false];

$columnHeaders = [
    'role' => 'Role',
    'person' => 'Contact person',
    'email' => 'Email',
    'telephone' => 'Telephone',
    'association' => 'Association',
];

//count assignments to print
$count = 0;
foreach ($assignments as $assignment) {
if ($assignment['person'] &&
	(($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive))) {
		$count++;
	}
}
if ($count > 0):
    if ($wrapInPanel):?>
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <?php if (isset($this->headerText)):?>
        	<div class="panel-heading"><?php echo $this->headerText;?></div>
        <?php endif;?>
        <!--<div class="panel-body">
         <p>...</p>
        </div>-->
    <?php endif;
	if (isset($this->headerText) && !$wrapInPanel):?>
		<p class="text-center"><strong><u><?php echo $this->headerText;?></u></strong></p>
	<?php endif;
?><table class="table">
    <thead><tr>
    <?php foreach ($columns as $column) {
        if (key_exists($column, $columnHeaders)) {
            echo '<th>'. $this->translate($columnHeaders[$column]). '</th>';
        } else {
            array_unshift($columns, $column);
        }
    }?>
    </tr></thead>
    <tbody>
    <?php foreach ($assignments as $assignment) :
    	if (($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive)):?>
        	<tr>
            <?php foreach ($columns as $column) :
                switch ($column) :
                    case 'association': ?>
                		<td><?php if (isset($assignment['association'])) {
                		    echo $this->formatEntity('association', $assignment['association'], $associationFormatOptions);
                		}?></td>
                        <?php break;
                    case 'role': ?>
                		<td><?php if (isset($assignment['roleTitle'])) {
                		    echo $this->formatEntity('assignment', $assignment, ['displayAsLink' => false]);
                		    //@todo add date range
                        }
//                 		    echo $this->escapeHtml($assignment['roleTitle']).
//                                 ' '.$this->shortDateRange($assignment['startDate'], $assignment['endDate']);
//                 		}
?></td>
                        <?php break;
                    case 'person': ?>
                        <td><?php if (isset($assignment['person']) && !empty($assignment['person'])) {
                            echo $this->formatEntity('person', $assignment['person'], $personFormatOptions);
                            echo $this->editPencil('assignment', $assignment['assignmentId']);
                        }
        				?></td><?php
    				    break;
                    case 'email': ?>
                		<td><?php if (isset($assignment['person']) && !empty($assignment['person'])) {
                		    echo $this->email($assignment['person']['email']);
                		} elseif (isset($assignment['association']) && !empty($assignment['association'])) {
                		    echo $this->email($assignment['association']['email']);
                		}?></td><?php
                        break;
                    case 'telephone': ?>
                		<td><?php if (isset($assignment['person']) && !empty($assignment['person'])) {
                		    echo $this->telephone($assignment['person']['cellPhone']);
                		} elseif (isset($assignment['association']) && !empty($assignment['association'])) {
                		    echo $this->telephone($assignment['association']['phone1']);
                		} ?></td><?php
                        break;
                endswitch;?>
        	<?php endforeach;?>
        	</tr>
    	<?php endif;
	endforeach;?>
    </tbody></table>
    <?php if ($wrapInPanel):?>
    </div>
    <?php endif;
endif;?>