<?php 
/**
 * @param array $assignments
 * @param bool $showActive = true
 * @param bool $showInactive = true
 * @param string $header
 */
$showActive = isset($this->showActive) ? $this->showActive : true;
$showInactive = isset($this->showInactive) ? $this->showInactive : true;
$assignments = is_array($this->assignments) ? $this->assignments : [];
//count assignments to print
$count = 0;
foreach ($assignments as $assignment) {
if ($assignment['person'] &&
	(($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive))) {
		$count++;
	}
}
if ($count>0):
	if (isset($this->headerText)):?>
	<p class="text-center"><strong><?php echo escapeHtml($this->headerText);?></strong></p>
	<?php endif;?>
    <table class="table">
    <thead><tr>
    <th><?php echo $this->translate('Role');?></th>
    <th><?php echo $this->translate('Contact person');?></th>
    </tr></thead>
    <tbody>
    <?php foreach ($assignments as $assignment) : 
    	if ($assignment['person'] && 
    		(($assignment['isActive'] && $showActive) || (!$assignment['isActive'] && $showInactive))):?>
    		<tr><td><?php echo $this->escapeHtml($assignment['roleTitle']).
    			' '.$this->shortDateRange($assignment['startDate'], $assignment['endDate']);
    		?></td>
    		<td><?php echo $this->formatEntity('person', $assignment['person'], ['displayEditPencil' => false]);
    		if ($this->isAllowed('route/assignments/assignment/edit')) : ?>
        		<a href="<?php
        		echo $this->url('assignments/assignment/edit', ['assignment_id' => $assignment['assignmentId'],
                    'action' => 'edit']);?>">
    			<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
    		<?php endif;?></td></tr>
    	<?php endif;
    	endforeach;?>
    </tbody></table>
<?php endif;?>