<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . "/". $this->asset("js/person-edit.js"));

$headText = 'Create New Association';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url('associations/create'));
$form->prepare();
echo $this->form()->openTag($form);
//don't include
echo $this->partial('fields-partial', array(
    'form' => $form,
));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
