<?php
$headText = 'Create New Association';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url('associations/create'));
$form->prepare();
echo $this->form()->openTag($form);
//don't include
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
