<?php $headText = 'Delete Association';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('associations/association/delete',
    ['sw_id' => $this->entityObject['identifier']]));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
