<?php
$object = $this->entity;
$headText = 'Edit Association';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('associations/association/edit',
		['association_id' => $this->entity['associationId']]));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', [
     'form' => $form,
 ]);
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>