<?php
use Schoenstatt\Model\SchoenstattTable;

$object = $this->entity;
$name = $object['isNameTranslateable'] ? $this->translate($object['name']) : $object['name'];
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($name);?>
<h1><?php echo $this->escapeHtml($name);?></h1>
<div class="row">
<div class="col-md-9">
<div class="panel panel-default" id="contactInfoPanel">
    <div class="panel-heading">
    	<div class="row">
    	<div class="col-xs-4">
        	<h3 class="panel-title"><?php echo $this->translate('Contact Info'); //@todo add contact notes and modified date?>
        </h3>
        </div>
        <div class="col-xs-5">
        	<?php if (!is_null($object['contactInfoUpdatedOn'])) :?>
        		<span class="pull-right"><small><?php echo sprintf($this->translate('Updated %s'),
        		    $this->diffForHumans($object['contactInfoUpdatedOn']));?></small></span>
        	<?php endif;?>
        </div>
        </div>
	</div>
    <div class="panel-body">
    	<div class="row">
    	<!-- Here goes the logo -->
    	<div class="col-md-7">
            <p><strong><?php echo $this->translate('Email'); ?>:</strong> <?php
            if (!is_null($object['email'])) { //@todo add checks for validated
                echo $this->email($object['email']);
                if (!is_null($object['email2'])) {
                    echo ', '.$this->email($object['email2']);
                }
            }?></p>
            <div class="row">
            <div class="col-md-12">
            	<div class="row"><div class="col-md-12">
            	<?php foreach ($object['urls'] as $urlRow) :?>
            	<a target="_blank" href="<?php echo $this->escapeHtmlAttr($urlRow['url']);?>">
            	    <img src="../<?php echo isset($urlRow['logo']) ? $this->escapeHtmlAttr($urlRow['logo']) : 'img/www.png';
            	    ?>" alt="<?php echo $this->escapeHtmlAttr($urlRow['label']);?>" class="img-circle" height="70px">
            	</a>&nbsp;
            	<?php endforeach; //@todo add email modified date?>
            	</div></div> <!-- Websites row and column -->
            </div> <!-- Links column -->
            </div> <!-- Links row -->
        </div>
        <div class="col-md-5">
            <?php foreach ($object['phones'] as $phoneRow) : ?>
                <p><strong><?php echo $this->translate($phoneRow['label']); ?>:</strong>
				<span><?php echo $this->telephone($phoneRow['number'],
						isset($phoneRow['whatsApp']) ? $phoneRow['whatsApp'] : false,
						$this->isAllowed('route/persons/person/edit-contact-info'));?></span></p>
            <?php endforeach;
            if (!is_null($object['phonesUpdatedOn'])) :  //@todo add a question mark here with text
                //@todo use diffForHumans view helper
        	    $phoneUpdated = Carbon::instance($object['phonesUpdatedOn']); //@todo position this Up-to-date better ?>
                <p class="text-right"><?php echo $this->tooltip('✓ Up-to-date', sprintf($this->translate('Updated by %s %s'), 'jeff', $phoneUpdated->diffForHumans()));?></p>
        	<?php endif;
        	if (!is_null($object['contactNotes'])) :?>
        		<p><strong><?php echo $this->translate('Notes');?>:</strong></p>
        		<div id="contactNotes"><?php echo $this->markdown($object['contactNotes']);?></div>
        	<?php endif;?>
        	<!--
        	Phone numbers should be updated or confirmed every 2 years to ensure up-to-date information.
        	Please help in confirming and/or updating out-dated information.
        	 -->
		</div> <!-- phones column -->
        </div>
    </div> <!-- contact info panel body -->
</div> <!-- contact info panel -->
</div> <!-- col-md-9 -->
</div>
<div class="row">
<div class="col-md-12">
<div class="panel panel-default" id="infoPanel">
    <div class="panel-heading">
    	<h3 class="panel-title"><?php echo $this->translate('Association Info'); ?></h3>
	</div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
        <p><strong><?php echo $this->translate('Foundation date');?>:</strong>
        <?php if (!is_null($object['foundationDate'])) {
        echo $this->dateFormat($object['foundationDate'], IntlDateFormatter::LONG, IntlDateFormatter::NONE);
        }?></p>
		<?php if (!is_null($object['suppressionDate'])) :?>
      		<p><strong><?php echo $this->translate('Suppression date');?>:</strong> <?php
                echo $this->dateFormat($object['suppressionDate'], IntlDateFormatter::LONG, IntlDateFormatter::NONE);
            ?></p>
		<?php endif;?>
		<?php if (!is_null($object['country'])) :?>
      		<p><strong><?php echo $this->translate('Country');?>:</strong> <?php
                echo $this->countryName($object['country'], true);
            ?></p>
		<?php endif;?>
	</div> <!-- info 1 column -->

    <div class="col-md-6">
		<?php if ($object['publicNotes']) : ?>
			<p class="text-center"><strong><?php echo $this->translate('Additional Info');?></strong></p>
			<?php echo $this->markdown($object['publicNotes']);
		endif;?>
	</div> <!-- info 2 column -->
    </div></div> <!-- contact info panel body -->
</div> <!-- course info 1 panel -->
</div><!-- info 1 column -->
</div> <!-- Info row -->

<div class="row">
<div class="col-md-12">
<div class="panel panel-default" id="assignmentsPanel">
    <div class="panel-heading">
    	<h3 class="panel-title"><?php echo $this->translate('Contact persons'); ?></h3>
	</div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
    	<p>&nbsp;</p>
    	<?php echo $this->partial('assignments-table-partial', [
    		'assignments' 	=> $object['assignments'],
    		'showActive' 	=> true,
    		'showInactive' 	=> false,
    	]);?>
	</div> <!-- assignments 1 column -->
    <div class="col-md-6">
    	<?php echo $this->partial('assignments-table-partial', [
    		'assignments' 	=> $object['assignments'],
    		'showActive' 	=> false,
    		'showInactive' 	=> true,
    		'headerText'	=> $this->translate('Past contacts'),
    	]);?>
    </div> <!-- assignments 2 column -->
	</div></div>
</div></div></div>

<?php
if ($object['kind'] == 'sch-national-movement' && isset($object['nationalOrganizations'])):?>
<div class="panel panel-default">
<!-- Default panel contents -->
<div class="panel-heading"><?php echo $this->translate('National organizations');?></div>
<?php if (0 === count($object['nationalOrganizations'])) :?>
    <div class="panel-body"><p><?php echo sprintf($this->translate('No other national organizations are registered in %s.'),
            $this->countryName($object['country']));?></p></div>
<?php else :
    echo $this->partial('associations-table', [
        'objects' => $object['nationalOrganizations'],
    ]);
endif;?>
</div>
<?php endif;?>

<!-- Left side roles, right side Admin notes -->
<div class="row">
<div class="col-md-12">
<div class="panel panel-default" id="adminPanel">
    <div class="panel-heading">
    	<h3 class="panel-title"><?php echo $this->translate('Admin info'); ?></h3>
	</div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
    <?php if (!empty($object['roles'])): ?>
    <ul class="list-group">
    	<?php foreach ($object['roles'] as $roleId => $role) :?>
    		<li class="list-group-item"><?php echo $this->formatEntity('role', $role);?></li>
        <?php endforeach;?>
	</ul>
	<?php endif;
	if ($this->isAllowed('route/roles/create')): ?>
        <p><a class="btn btn-default btn-sm" href="<?php
            echo $this->url('roles/create', [],
                ['query' => ['associationId' => $object['associationId']]]);?>">
            <span class="glyphicon glyphicon-plus">&nbsp;</span><?php echo $this->translate('Add role')?></a>
        </p>
    <?php endif;?>
	</div>
    <div class="col-md-6"><!-- Admin notes column -->
		<?php if ($object['adminNotes']):?>
    		<p><strong><?php echo $this->translate('Admin notes');?>:</strong></p>
    		<div><?php echo $this->markdown($object['adminNotes']);?></div>
		<?php endif;?>
    </div>
	</div></div>
</div></div></div>

<!-- @todo Add photos at the bottom -->
<div class="row"><div class="col-md-12">
<?php if ($this->isAllowed('route/associations/association/edit')): ?>
      <a class="btn btn-primary" href="<?php echo $this->url('associations/association/edit',
          ['association_id' => $object['associationId']]);?>"><?php
    echo $this->translate("Edit details")?></a>
<?php endif;?>
</div></div>
