<!-- Table -->
<div class="table-responsive">
<table class="table">
<tr>
	<th><?php echo $this->translate('Shrine');?></th>
	<th><?php echo $this->translate('Website');?></th>
	<th><?php echo $this->translate('Opening hours?');?></th>
	<th><?php echo $this->translate('Events?');?></th>
	<th><?php echo $this->translate('Name translated?');?></th>
</tr>
<?php foreach ($this->objects as $entityId => $entity) :?>
<tr>
	<td><?= $this->formatEntity('association', $entity);?></td>
	<!-- <td><?= $this->formatEntity('association', $entity, ['display' => 'kind']);?></td> -->
	<td><?php foreach ($entity['urls'] as $url) {
	    if ('Map' !== $url['label']) {
	       echo $this->formatUrlObject($url);
	       break;
	    }
	}?></td>
	<td><?= isset($entity['openingHoursJson']) || isset($entity['openingHoursHuman']) ? 'Yup!' : 'Nope :-('; ?></td>
	<td><?= isset($entity['eventsJson']) || isset($entity['eventsHuman']) ? 'Yup!' : 'Nope :-('; ?></td>
	<td><?= $entity['hasTranslationCount'] . '/'.$entity['needTranslationCount']; ?></td>
</tr>
<?php endforeach;?>
</table>
</div>