<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap-markdown.min.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . '/'. $this->asset("js/markdown-form-$lang.js"));
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headScript()->appendFile($this->basePath() . '/'. $this->asset("js/selectize.min.js"));
$form = $this->form;
echo $this->formRow($form->get('title'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('authors'));
echo $this->formRow($form->get('bookEdition'));
echo $this->formRow($form->get('hasNoExplictEditionNumber'));
echo $this->formRow($form->get('inLanguage'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('mainPublicationId'));
echo $this->formRow($form->get('translatedFromPublicationId'));
echo $this->formRow($form->get('volumeNumber'));
echo $this->formRow($form->get('isbn'));
echo $this->formRow($form->get('hasNoISBN'));
echo $this->formRow($form->get('containedIn'));
echo $this->formRow($form->get('containedInIsbn'));
echo $this->formRow($form->get('copyrightYear'));
echo $this->formRow($form->get('publisher'));
echo $this->formRow($form->get('publishingPlace'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('bookFormatType'));
echo $this->formRow($form->get('numberOfPages'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('keywords'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('resourceId'));
echo $this->formRow($form->get('isFormallyPublished'));
echo $this->formRow($form->get('isAccessibleForFree'));
echo $this->formRow($form->get('isScientificWork'));
echo $this->formRow($form->get('isRevisedWithBookInHand'));?>
<div style="clear: left; display: block;" class="pull-right"><a href="http://commonmark.org/help/" class="btn btn-default"> <?php echo $this->translate("Learn Markdown in 60 seconds");?></a></div>
<?php
echo $this->formRow($form->get('editionNotes'));
echo $this->formRow($form->get('publicNotes'));
echo $this->formRow($form->get('categoryId'));
echo $this->formRow($form->get('url1'));
echo $this->formRow($form->get('url1Label'));
echo $this->formRow($form->get('url2'));
echo $this->formRow($form->get('url2Label'));
echo $this->formRow($form->get('url3'));
echo $this->formRow($form->get('url3Label'));
echo $this->formRow($form->get('adminNotes'));
echo $this->formRow($form->get('adminTags'));
echo $this->formRow($form->get('security'));

$jsScript = <<<JS
$("select[name='authors[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='inLanguage']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='mainPublicationId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='translatedFromPublicationId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='publisher']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='keywords[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='url1Label']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='url2Label']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='url3Label']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='adminTags[]']").selectize({
    create: true,
    sortField: 'text'
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();

?>
