<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/publications-index.css');
$languageName = isset($this->language) ? $this->languageName($this->language) : null;
if ($this->language === 'xx') {
    $headText = $this->translate('Schoenstatt Literature without language');
} elseif (isset($languageName)) {
    $headTextPattern = 'Schoenstatt Literature in %s';
    $headText = sprintf($this->translate($headTextPattern), $languageName);
} else {
    $headText = "Schoenstatt Literature";
}
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headText);
?>

<h2><?php echo $headText;?></h2>
<?php echo $this->partial('search-bar', [
    'form' => $this->form,
]);
if ($this->isAllowed('route/publications/create')):?>
<p><a class="btn btn-primary pull-right" href="<?php echo $this->url('publications/create');?>"><?php echo $this->translate('Add publication');?></a>
<?php endif;?>

<div class="row">

<div class="col-md-9">
<?php 
foreach ($this->objects as $categoryName => $category) :
if (empty($category['objects'])) {
continue;
}?>
<h3 id="<?php echo $category['bookmark'];?>"><?php echo $this->escapeHtml($this->translate($categoryName));?></h3>
<?php 
    echo $this->partial('publication-list', [
        'objects' => $category['objects'],
        'columns' => [
            'cover', 'authors', 'title', 'edition',
        ],
        'files' => $this->files,
    ]);
endforeach;?>

</div>

 <!--Affix start https://www.w3schools.com/bootstrap/bootstrap_ref_js_scrollspy.asp-->
 <nav class="col-md-3 pull-right" id="sidebar-nav" role="complementary">
    <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="275">
    <?php $firstTime = true;
    foreach ($this->objects as $categoryName => $category) :
    if (empty($category['objects'])) {
    continue;
    }?>
       <li><a href="#<?php echo $this->escapeHtmlAttr($category['bookmark']);?>" <?php if ($firstTime) echo 'class="active"';?>><?php echo $this->escapeHtml($this->translate( $categoryName ));?></a></li>
       <?php $firstTime = false;
       endforeach;?>
    </ul>
 </nav>
 <!--Affix end-->
</div>