<?php
$this->headMeta()->appendName('description', 'Literature relating to Schoenstatt. This index has been compiled from several libraries of the Schoenstatt Fathers and will continue to grow as we review the information of further books.');
$headText = 'Schoenstatt Literature Index';
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headText);?>
<h1><?php echo $headText;?></h1>
<?php echo $this->partial('search-bar', [
    'form' => $this->form,
]);
if ($this->isAllowed('route/publications/create')):?>
<p><a class="btn btn-primary pull-right" href="<?php echo $this->url('publications/create');?>"><?php echo $this->translate('Add publication');?></a>
<?php endif;
$this->badge()->setTranslatorEnabled(false); ?>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="list-group">
<?php foreach ($this->objects as $inLanguage => $count) :?>
	<a href="<?php echo $this->url('publications/index', ['inLanguage' => $inLanguage]);?>" class="list-group-item">
    	<span class="badge alert-info"><?php echo $this->escapeHtml($count); ?></span>
    <h4 class="list-group-item-heading"><?php echo $this->escapeHtml(array_key_exists($inLanguage, $this->languages) ? $this->languages[$inLanguage] : $inLanguage);?></h4></a>
<?php endforeach;?>
</div>
</div>
</div>