<?php
$this->headMeta()->appendName('description',
    $this->translate('Literature relating to Schoenstatt. This index has been compiled from several libraries of the Schoenstatt Fathers and will continue to grow as we review the information of further books.'));
$headText = $this->translate('Schoenstatt Literature Tools');
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headText);?>
<div class="row">
<h1><?php echo $headText;?></h1>
<?php echo $this->partial('search-bar', [
    'form' => $this->form,
]);
if ($this->isAllowed('route/publications/create')):?>
<p><a class="btn btn-primary pull-right" href="<?php echo $this->url('publications/create');?>"><?php echo $this->translate('Add publication');?></a>
<?php endif;
$this->badge()->setTranslatorEnabled(false); ?>
<div class="col-md-8 col-md-offset-2">
<div class="list-group">
<?php foreach ($this->objects as $inLanguage => $count) :?>
	<a href="<?php echo $this->url('publications/index', ['inLanguage' => $inLanguage]);?>" class="list-group-item">
    	<span class="badge alert-info"><?php echo $this->escapeHtml($count); ?></span>
    <h4 class="list-group-item-heading"><?php 
    $languageText = array_key_exists($inLanguage, $this->languages) ? $this->translate($this->languages[$inLanguage]) : $inLanguage;
    echo $this->escapeHtml(sprintf($this->translate("%s Catalog"), $languageText));?></h4></a>
<?php endforeach;?>
</div>
</div>
</div>

<div class="row">
<h2><?php echo $this->translate('Schoenstatt libraries');?></h2>
<?php echo $this->partial('books/libraries/library-list', [
    'objects' => $this->libraries,
]);?>
</div>


<div class="row">
<h2 id="dictionaries"><?php echo $this->translate('Fr. Kentenich translation dictionaries');?></h2>
<div class="col-md-8 col-md-offset-2">
<div class="list-group">
<?php foreach ($this->dictionaries as $dict) :?>
	<a href="<?php echo $this->url('dictionary/inLanguage', ['inLanguage' => $dict['inLanguage']]);?>" class="list-group-item">
    <span class="badge alert-info"><?php echo $this->escapeHtml($dict['count']); ?></span>
    <h4 class="list-group-item-heading"><?php echo sprintf($this->translate('German to %s Dictionary'), $dict['inLanguageName']);?></h4></a>
<?php endforeach;?>
</div>
</div>
</div>