<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
?>
<?php
if ($this->isSimulation) : ?>
<p>This is a simulation. <a href="?simulate=0" class="btn btn-danger">Do the real deal</a></p>
<?php else: ?>
<p class="text-danger">This is the real deal!</p>
<?php endif;?>
<p>We are showing the <?= $this->escapeHtml(count($this->results));?> rows which come from an outside data source,
    has been approved, and hadn't yet been mapped to a 1st-class-citizen row.</p>
<div class="responsive-table">
    <table class="table">
        <tr>
            <th>Action</th>
            <th>Result</th>
            <th>Data source</th>
            <th>Language</th>
            <th>PubId</th>
            <th>Title</th>
        </tr>
        <?php foreach ($this->results as $result) :?>
            <tr>
                <td>Duplicate and relink</td>
                <td><?php
                if (isset($result['result'])) {
                    echo $this->escapeHtml($result['result']);
                }
                ?></td>
                <td><?= $this->escapeHtml($result['dataSource'])?></td>
                <td><?= $this->escapeHtml(implode('|',$result['inLanguage']))?></td>
                <td><?= $this->escapeHtml($result['publicationId'])?></td>
                <td><?= $this->escapeHtml($result['title'])?></td>
            </tr>
        <?php endforeach;?>
    </table>
</div>
