<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="list-group">
            <a href="<?php echo $this->url('admin/literature-maintenance/copy-data-sourced-row-to-first-class-citizen');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->copyDataSourcedRowToFirstClassCitizen?></span>
                <h4 class="list-group-item-heading">Copy over useful data sourced records to first class citizens</h4>
                <p class="list-group-item-text">A first class citizen are the publication rows we will ultimately
                    show to the user. We had an old system for determining which go to the user. It copies
                    data-sourced rows to new rows and updates the reference of the original to the new.</p>
            </a>
            <a href="<?php echo $this->url('admin/literature-maintenance/update-main-publication-ids');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->countUpdateMainPublicationId?></span>
                <h4 class="list-group-item-heading">Update MainPublicationId to new ids</h4>
                <p class="list-group-item-text">Check for MainPublicationId's pointing to data-sourced rows and update them.</p>
            </a>
            <a href="<?php echo $this->url('admin/literature-maintenance/update-translated-from-publication-id');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->countUpdateTranslatedFromPublicationIdReferences?></span>
                <h4 class="list-group-item-heading">Update TranslatedFromPublicationId to new ids</h4>
                <p class="list-group-item-text">Check for TranslatedFromPublicationId's pointing to data-sourced rows and update them.</p>
            </a>
            <a href="<?php echo $this->url('admin/literature-maintenance/update-cover-images');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->countUpdateCoverImages?></span>
                <h4 class="list-group-item-heading">Update cover images</h4>
                <p class="list-group-item-text">Check for cover image file names pointing to data-sourced rows and update them.</p>
            </a>
            <a href="<?php echo $this->url('admin/literature-maintenance/update-library-book-publication-references');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->countUpdateLibraryBooks?></span>
                <h4 class="list-group-item-heading">Update library book to publication references</h4>
                <p class="list-group-item-text">Check all library books for references to data-sourced publications.</p>
            </a>
            <a href="<?php echo $this->url('admin/literature-maintenance/list-merged-publication-id-map');?>"
               class="list-group-item">
                <span class="badge badge-info"><?= $this->countListMap?></span>
                <h4 class="list-group-item-heading">Show merged publication id map</h4>
                <p class="list-group-item-text">List all the data sourced publication ids that have been merged into first-class citizens.</p>
            </a>
        </div>
    </div>
</div>