<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
?>
<p><a href="<?= $this->url('admin/literature-maintenance')?>">Return to literature maintenance menu</a></p>
<?php
if ($this->isSimulation) : ?>
<p>This is a simulation. <a href="?simulate=0" class="btn btn-danger">Do the real deal</a></p>
<?php else: ?>
<p class="text-danger">This is the real deal!</p>
<?php endif;?>
<p>We are showing the <?= $this->escapeHtml(count($this->results));?> rows which come from an outside data source,
    has been approved, and hadn't yet been mapped to a 1st-class-citizen row.</p>
<div class="responsive-table">
    <table class="table">
        <tr>
            <?php foreach ($this->fields as $field) :?>
            <th><?= $field?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->results as $result) :?>
            <tr>
                <?php foreach ($this->fields as $field) :?>
                <td>
                    <?php switch ($field):
                        case 'Action':
                            echo $this->rowAction;
                            break;
                        case 'Result':
                            if (isset($result['result'])) {
                                echo $this->escapeHtml($result['result']);
                            }
                            break;
                        case 'Data source':
                            echo $this->escapeHtml($result['dataSource']);
                            break;
                        case 'Language':
                            echo $this->escapeHtml(implode('|',$result['inLanguage']));
                            break;
                        case 'PubId':
                            echo $this->escapeHtml($result['publicationId']);
                            break;
                        case 'Title':
                            echo $this->escapeHtml($result['title']);
                            break;
                        case 'MainPubId':
                            echo $this->escapeHtml($result['mainPublicationId']);
                            break;
                        case 'TranslatedFromPubId':
                            echo $this->escapeHtml($result['translatedFromPublicationId']);
                            break;
                        case 'File name':
                            echo $this->escapeHtml($result['fileName']);
                            break;

                        default:
                            echo '';
                        endswitch;?>
                </td><?php endforeach; ?>
            </tr>
        <?php endforeach;?>
    </table>
</div>
