<?php
/**
 * @var mixed[] $object
 */
$object = $this->object;
?>
<div class="row">
<div class="col-md-3">
<?php if (file_exists(sprintf('public/covers/%s.jpg', $object['publicationId']))) : ?>
    <img src="<?php echo $this->basePath() . sprintf("/covers/%s.jpg", $object['publicationId']); ?>"
    height="200px" alt="<?php echo $this->escapeHtmlAttr($object['title']);?>">
<?php endif;?>
<p class="align-center"><?php //echo $this->escapeHtml(ucwords($object['condition']));?></p>
</div>
<div class="col-md-9">
<div class="panel panel-default" id="infoPanel">
    <div class="panel-heading">
        <div class="row">
        <div class="col-xs-6">
            <h3 class="panel-title"><?php echo $this->escapeHtml($this->translate('Publication Info')); ?></h3>
        </div>

        <div class="col-xs-6">
            <?php if ($this->isAllowed($object['resourceId'], 'edit')): ?>
                <span class="pull-right"><a class="btn btn-primary btn-sm" href="<?php
                    echo $this->url('publications/publication/edit', array('publication_id' => $object['publicationId']));?>">
                    <?php echo $this->translate('Edit publication')?></a>
                </span>
            <?php elseif (false)://@todo $this->isAllowed('route/publications/publication/suggest')):?>
                <span class="pull-right"><a class="btn btn-default btn-sm" href="<?php
                    echo $this->url('courses/course/suggest', array('publication_id' => $object['publicationId']));?>">
                    <?php echo $this->translate('Suggest change')?></a>
                </span>
            <?php endif;?>
        </div>
        </div>
    </div>
    <div class="panel-body"><div class="row">
    <div class="col-md-6">
          <p><strong><?php echo $this->translate('Author(s)');?></strong></p>
          <?php echo $this->formatEntity('publication', $object, ['display' => 'authors']);?>
    </div> <!-- info 1 column -->

    <div class="col-md-6">
      <!-- <p><strong><?php echo $this->translate('Superiors');?></strong></p> -->
        <?php echo $this->formatField('Language', $object['inLanguage']);
        if (!is_null($object['mainPublication'])) :?>
        <p><strong><?php echo $this->translate('Current publication');?>:</strong> <?php
        echo $this->formatEntity('publication', $object['mainPublication']);?></p>
        <?php endif;
        if (!is_null($object['translatedFromPublication'])) :?>
        <p><strong><?php echo $this->translate('Translated from');?>:</strong> <?php
        echo $this->formatEntity('publication', $object['translatedFromPublication']);?></p>
        <?php endif;
        echo $this->formatField('ISBN', $object['isbn'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Edition', $object['bookEdition'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Translator', $object['translatorPersonId'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Illustrator', $object['illustratorPersonId'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Number of pages', $object['numberOfPages'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Copyright year', $object['copyrightYear'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Publisher', $object['publisher'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Publishing place', $object['publishingPlace'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Publishing status', $object['publishingStatus'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Book format', $object['bookFormatType'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Volume number', $object['volumeNumber'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Contained in', $object['containedIn'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Contained in ISBN', $object['containedInIsbn'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Genre', $object['genre'], ['displayOnlyIfNotNull' => true]);
        echo $this->formatField('Keywords', $object['keywords'], ['displayOnlyIfNotNull' => true, 'translateLabel' => false]);
        echo $this->formatField('Admin tags', $object['adminTags'], ['displayOnlyIfNotNull' => true, 'translateLabel' => false,
            'displayOnlyWithPermission' => 'route/publications/publication/edit']);
        foreach ($object['urls'] as $urlObject) :
            ?><p><?php echo $this->formatPublicationUrlObject($urlObject);?></p><?php
        endforeach;
        ?>
    </div> <!-- info 2 column -->
    </div></div> <!-- contact info panel body -->
</div> <!-- course info 1 panel -->
</div> <!-- info 1 column -->
</div> <!-- Info row -->

<?php //@todo add 5 description languages
// if (count($entity['idealLanguages']) > 0) {
//     echo $this->partial('patres/patres/multi-language-text-box', [
//         'title'             => $this->translate('Ideal Statement'),
//         'textLanguageKeys'  => $entity['idealLanguages'],
//         'entity'            => $entity,
//         'id'                => $entity['territoryId'],
//     ]);
// }?>

  <?php if (!is_null($object['publicNotes']) && 0 !== strlen($object['publicNotes'])):?>
<div class="row"> <!-- notes row -->
<div class="col-md-12">
<div class="panel panel-default" id="notesPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Notes'); ?></h3>
    </div>
    <div class="panel-body">
    <div><?php echo $this->markdown($object['publicNotes']);?>
    </div>
    </div> <!-- notes panel body -->
</div> <!-- notes panel -->
</div> <!-- notes column 12 -->
</div> <!-- notes row -->
<?php endif;?>

  <?php if (!is_null($object['adminNotes']) && 0 !== strlen($object['adminNotes']) &&
          $this->isAllowed($object['resourceId'], 'show-admin-info')):?>
<div class="row"> <!-- notes row -->
<div class="col-md-12">
<div class="panel panel-default" id="adminNotesPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Admin notes'); ?></h3>
    </div>
    <div class="panel-body">
    <div><?php echo $this->markdown($object['adminNotes']);?>
    </div>
    </div> <!-- notes panel body -->
</div> <!-- notes panel -->
</div> <!-- notes column 12 -->
</div> <!-- notes row -->
<?php endif;

echo $this->booksJsonLd('publication', $object);
?>