<?php
use Books\View\Helper\FormatPublication;

/**
 * @var $objects mixed[]
 * @var $columns string[]
 */
if (!isset($this->columns)) {
    throw new \InvalidArgumentException('Please pass a list of columns to the publication-list partial');
}
$columnNames = [
    'cover'     => '',
    'authors'   => 'Authors',
    'title'     => 'Title',
    'edition'   => 'Edition',
];
?>
<table class="table">
<tr><?php foreach ($this->columns as $key => $column) :
    if (!key_exists($column, $columnNames)) {
        unset($column[$key]);
        continue;
    }?>
    <th><?php echo $this->translate($columnNames[$column]);?></th>
<?php endforeach;?>
</tr>
<?php foreach($this->objects as $entityId => $entity) :
if (!$this->isAllowed($entity['resourceId'], 'show')) {
    continue;
}?>
<tr><?php foreach ($this->columns as $column) :
switch ($column) {
    case 'cover': ?>
    <td><?php
        if (file_exists(sprintf('public/covers/%s-80px.jpg', $entity['publicationId']))):?>
    	<a href="<?php echo $this->url('publications/publication', ['publication_id' => $entity['publicationId']]); ?>">
    <img src="<?php echo $this->basePath() . sprintf("/covers/%s-80px.jpg", $entity['publicationId']); ?>"
    height="80px" alt="<?php echo $this->escapeHtmlAttr($entity['title']);?>"></a>
    	<?php endif;
	?></td><?php
        break;
    case 'authors':?>
		<td><?php echo $this->formatEntity('publication', $entity, [
		    'display' => 'authors',
		]);?></td>
    	<?php break;
    case 'title':?>
		<td><?php echo $this->formatEntity('publication', $entity, ['displayLanguageLabel' => false, 'displayResourceLabel' => true]);?></td>
    	<?php break;
    case 'edition':?>
		<td><?php echo $this->formatEntity('publication', $entity, ['display' => FormatPublication::DISPLAY_EDITION]);?></td>
    	<?php break;

    default:
        ;
    break;
}
endforeach;
endforeach; ?></tr>
</table>