<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$title = "Publications search";
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($this->translate($title));?></h3>
<?php echo $this->partial('search-bar', ['form' => $this->form]);
if ($this->isAllowed('route/publications/create')) :?>
<p><a class="btn btn-primary pull-right" href="<?php echo $this->url('publications/create');?>"><?php echo $this->translate('Add publication');?></a>
<?php endif;
if (! is_null($this->entities) && 0 !== count($this->entities)) {
    echo $this->partial('publication-list', [
        'objects' => $this->entities,
        'columns' => [
            'cover', 'authors', 'title', 'edition',
        ],
    ]);
}
