<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headScript()->appendFile($this->basePath() . "/js/gen-publications-search-bar.js");
$form = $this->form;
$form->setAttribute('action', $this->url('publications/search'));
$form->prepare();?>
<div class="row search-bar <?php if ($this->centerOnPage) {
    echo " search-bar-center";
                           } ?>">
      <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div id="custom-search-input">
            <?php echo $this->form()->openTag($form); ?>
              <div class="input-group col-md-12">
                    <?php echo $this->formElement($form->get('search'));?>
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>
                      </button>
                  </span>
              </div>
            <div class="row">
                <div class="col-md-12">
                    <a data-toggle="collapse" data-target="#options" aria-expanded="false" aria-controls="options"><?php
                        echo $this->translate("Advanced options"); ?></a>
                    <?php if ($this->isAllowed('route/publications/advanced-search')) :?>
                        &nbsp;&nbsp;<a href="<?php echo $this->url('publications/advanced-search'); ?>"><?php
                        echo $this->translate("Advanced search"); ?></a>
                    <?php endif;?>
                </div>
                <div id="options" class= "collapse row">
                    <div class="checkbox col-md-4">
                        <?php echo $this->formCheckbox($form->get('showEditionsSeparately')); ?>
                    </div>
                    <div class="checkbox col-md-4">
                        <div class="pull-right"><?php
                        $this->formSelect()->setTranslatorEnabled(false);
                        echo $this->formLabel($form->get('inLanguage')); ?></div>
                    </div>
                    <div class="checkbox col-md-4">
                        <?php
                        echo $this->formSelect($form->get('inLanguage'));
                        $this->formSelect()->setTranslatorEnabled(true);
                        ?>
                    </div>
                </div>
            </div>
            <?php echo $this->form()->closeTag();?>
          </div>
      </div>
</div>
