<?php
$title = "Publications search";
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($this->translate($title));?></h3>
<?php echo $this->partial('search-bar', ['form' => $this->form]);
if (!is_null($this->entities) && 0 !== count($this->entities)) {
    echo $this->partial('publication-list', [
        'objects' => $this->entities,
        'columns' => [
            'authors', 'title', 'edition',
        ],
    ]);
}
