<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$object = $this->entity;
//@todo add edition information and author into meta description
$this->headMeta()->appendName(
    'description',
    sprintf($this->translate('Bibliographical information about "%s".'), $object['title'])
);
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($object['title']);?>
<h1><?php echo $this->formatPublication('publication', $this->entity, ['link' => false, 'displayEditPencil' => false]);?></h1>
<?php echo $this->partial('publication-info', ['object' => $this->entity]);

if ($this->isAllowed('route/publication-create-new-edition')) :?>
<p><a class="btn btn-default" href="<?php echo $this->url('publication-create-new-edition', [], [], true);?>"><?php
echo $this->translate('Add another edition');?></a></p>
<?php endif;
if (! empty($object['files']) && $this->isAllowed('publication_drive')) {
    echo $this->partial('books/files/files-list-panel', [
        'files' => $object['files'],
        'columns' => ['fileName', 'notes', 'size', 'mimeType'],
    ]);
}
echo $this->partial('books/books/book-list', [
    'entities' => $this->libraryBooks,
    'columns' => ['library', 'book', 'callNumber'], //@todo add library contact info
]);
if (isset($this->comments)) {
    echo $this->partial('sion-model/comments/comments-list', ['comments' => $this->comments]);
}
if ($this->isAllowed('route/comments/create')) {
    echo $this->partial('sion-model/comments/create', [
        'form' => $this->commentForm
    ]);
}
if ($this->isAllowed('route/publication-edit')) {
    echo $this->partial('sion-model/sion-model/entity-changes-panel', [
        'changes' => $this->changes,
        'panelTitle' => 'Change log'
    ]);
}?>

<div class="row"><div class="col-md-12">
<p><strong><?= $this->translate('Total views')?></strong>: <?= $this->visits['total']?> <strong><?= $this->translate('Views this month')?></strong>: <?= $this->visits['pastMonth']?></p>
</div></div>
