<?php
$headText = 'Upload book cover';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('publications/publication/upload-cover',
		[], [], true));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('fileUpload'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>