<?php
use Books\Filter\KentenichPeriodFromDate;
?>
<h1><?= $this->translate('Fr. Kentenich Timeline')?></h1>
<p>This timeline is the fruit of a collaborative effort since 2006 of several generations of students of the Schoenstatt Fathers community. The basic idea is to better understand the main events of Fr. Kentenich's biography by seeing them in relation to world and Church events. Please let us know if you would like to collaborate!</p>
<?php foreach ($this->periods as $period => $years) :?>
<h2><?= $this->translate(KentenichPeriodFromDate::PERIOD_NAMES[$period]);?></h2>
<?php foreach ($years as $year => $eventObjects) :?>
<div class="row">
<div class="col-4"><strong><?php echo $this->escapeHtml($year);?></strong></div>
<div class="col-8"><?php foreach ($eventObjects as $event) :?>
<span><?php echo $this->escapeHtml($event['titleEn']);?></span><br>
<?php endforeach;?>
</div>
</div>
<?php endforeach;?>
<?php endforeach;?>