<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$form = $this->form;
echo $this->formRow($form->get('name'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('libraryId'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('filePath'));
echo $this->formRow($form->get('worksheet'));
echo $this->formRow($form->get('isCompleteImport'));
echo $this->formRow($form->get('security'));
echo $this->formRow($form->get('submit'));
