<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$entity = $this->entity;?>

<p><strong><?php echo $this->translate('Books created');?>:</strong> <?php echo $this->escapeHtml($entity['booksCreated']);?></p>
<p><strong><?php echo $this->translate('Books updated');?>:</strong> <?php echo $this->escapeHtml($entity['booksUpdated']);?></p>
<p><strong><?php echo $this->translate('Books inactivated');?>:</strong> <?php echo $this->escapeHtml($entity['booksInactivated']);?></p>