<?php
if ($this->isAllowed('route/library-imports/library/create')):?>
<p><a class="btn btn-primary" href="<?php
    echo $this->url('library-imports/library/create', ['library_id' => $this->libraryId]);?>"><?php echo $this->translate('Start new import');?></a></p>
<?php endif;?>
<table class="table">
<thead>
<tr>
	<th><?php echo $this->translate('Import name');?></th>
	<th><?php echo $this->translate('Description');?></th>
	<th><?php echo $this->translate('Complete import');?></th>
	<th><?php echo $this->translate('Import started');?></th>
	<th><?php echo $this->translate('Last updated');?></th>
	<th><?php echo $this->translate('Books created');?></th>
	<th><?php echo $this->translate('Books updated');?></th>
	<th><?php echo $this->translate('Books deleted');?></th>
</tr>
</thead>
<tbody>
<?php
$objects = $this->objects;
foreach ($objects as $object) :?>
<tr>
	<td><?php echo $this->escapeHtml($object['name']);?></td>
	<td><?php echo $this->escapeHtml($object['description']);?></td>
	<td><?php echo $object['isCompleteImport'] ? $this->translate('Yes') : $this->translate('No');?></td>
	<td><?php echo $this->dateFormat($object['createdOn'], \IntlDateFormatter::MEDIUM, \IntlDateFormatter::MEDIUM);?></td>
	<td><?php echo $this->dateFormat($object['updatedOn'], \IntlDateFormatter::MEDIUM, \IntlDateFormatter::MEDIUM);?></td>
	<td><?php echo $this->escapeHtml($object['booksCreated']);?></td>
	<td><?php echo $this->escapeHtml($object['booksUpdated']);?></td>
	<td><?php echo $this->escapeHtml($object['booksDeleted']);?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>