<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());

$headText = 'Create New Person';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url('persons/create'));
$form->prepare();
echo $this->form()->openTag($form);
//don't include
echo $this->partial('fields-partial', array(
    'form' => $form,
    'entity' => 'person',
));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
