<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$this->headScript()->appendFile($this->basePath() . "/". $this->asset("js/person-edit.js"));

// $isModeration = false;
$headText = 'Edit Person Info';
$titleText = 'Edit %s';
if (isset($titleText)) {
    $this->headTitle()->setTranslatorEnabled(false);
    $this->headTitle(sprintf($this->translate($titleText), $this->personName));
}?>
<h1><?php echo $this->translate($headText);?></h1>
<p class="lead"><?php echo $this->escapeHtml($this->personName);?></p>

<?php //if ($isModeration) {
//     echo $this->partial('patres/patres/moderate-form-text', ['suggestion' => $this->person]);
// } else {
//     echo $this->partial('show-active-living-situation', ['person' => $this->person]);
//     if ($this->entity != 'person') {
//         echo '<hr>';
//     }
// }

$form = $this->form;
$form->setAttribute('action', $this->url($this->action,
    [
        'person_id' => $this->entityId,
        //only used if we're reviewing a suggestion:
//         'suggestion_id' => isset($this->person['suggestionId']) ? $this->person['suggestionId'] : null,
    ]));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', array(
     'form' => $form,
     'entity' => $this->entity,
 ));
//  if ($isModeration) {
//      echo $this->formRow($form->get('suggestionResponse'));
//      echo $this->formHidden($form->get('suggestionId'));
//  }
//  echo $this->formRow($form->get('security'));
 echo $this->formSubmit($form->get('submit'));
 if ($this->isAllowed('route/persons/person/delete')) {
     echo '&nbsp;';
     echo $this->formButton($form->get('delete'));
 }
//  if ($isModeration) :
//      echo '&nbsp;'.$this->formSubmit($form->get('deny'));
// endif;
 echo $this->form()->closeTag();
 //@todo DRY up this modal
if ($this->isAllowed('route/persons/person/delete')) :?>
<!-- Modal -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><?php echo $this->translate('Careful');?>...</h4>
      </div>
      <div class="modal-body">
        <p><?php echo $this->translate("Only delete a person if he/she was created by mistake!
        		If you wish change the person in charge, simply set an \"End Date\" in the past
        		and create a new assignment.");?></p>
        <?php $form = $this->deleteForm;
        	$form->setAttribute('action', $this->url('persons/person/delete',
        			['person_id' => $this->entityId]));
        	$form->prepare();
 			echo $this->form()->openTag($form);
			echo $this->formRow($form->get('security'));
			echo $this->formSubmit($form->get('submit'));
			echo '&nbsp;';
			echo $this->formButton($form->get('cancel'));
			echo $this->form()->closeTag();
        ?>
      </div>
    </div>
  </div>
</div>
<?php endif;?>