<?php
use Schoenstatt\View\Helper\FormatPerson;
use Schoenstatt\Model\SchoenstattTable;
$this->headScript()->appendFile($this->basePath() . '/js/gen-bootstrap-sortable.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-bootstrap-sortable.min.css');
$columnNames = [
    'name' => 'Name',
    'email' => 'Email',
    'cellPhone' => 'Cell',
];
$options = [
    'showPhotos' => false,
    'showEmailsButton' => true,
    'showDeceased' => true,
    'showExMembers' => true,
    'showLabels' => false,
];
if ($this->options) {
    if (isset($this->options['showPhotos']) && is_bool($this->options['showPhotos'])) {
        $options['showPhotos'] = $this->options['showPhotos'];
    }
    if (isset($this->options['showEmailsButton']) && is_bool($this->options['showEmailsButton'])) {
        $options['showEmailsButton'] = $this->options['showEmailsButton'];
    }
    if (isset($this->options['showDeceased']) && is_bool($this->options['showDeceased'])) {
        $options['showDeceased'] = $this->options['showDeceased'];
    }
    if (isset($this->options['showExMembers']) && is_bool($this->options['showExMembers'])) {
        $options['showExMembers'] = $this->options['showExMembers'];
    }
    if (isset($this->options['showLabels']) && is_bool($this->options['showLabels'])) {
        $options['showLabels'] = $this->options['showLabels'];
    }
}
$areResults = isset($this->entities) && 0 != count($this->entities);
// var_dump($this->persons);
if ($areResults) :
    $emails = [];
    $emailValidator = new \Laminas\Validator\EmailAddress();
    $resultsTotal = 0;
    $resultsCount = SchoenstattTable::CATEGORY_PLURALS;
    foreach ($resultsCount as $key => $value) {
        $resultsCount[$key] = 0;
    }?>
<div class="panel panel-default">
<div id="personsresults" class="table-responsive panel-body">
    <table class="table sortable">
        <thead>
        <tr>
            <?php foreach ($this->columns as $col) :?>
                <th><?php if ($col != 'course' || $this->isAllowed('courses')) {
                    echo $this->translate($columnNames[$col]);
                    }?></th>
            <?php endforeach;?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->entities as $person) :
            if (is_null($person['deathDate']) && is_null($person['leaveDate']) &&
                $emailValidator->isValid($person['email'])) {
                $thisEmail = '"' . $person['firstName'] . ' ' . $person['lastName'] . '" <' . $person['email'] . '>';
                array_push($emails, $thisEmail);
            }
            if ((! $options['showDeceased'] && ! is_null($person['deathDate'])) ||
                (! $options['showExMembers'] && ! is_null($person['leaveDate']) )) {
                continue;
            }
            if (isset($resultsCount[$person['category']])) {
                $resultsCount[$person['category']]++;
            }
            $resultsTotal++;
            ?>
        <tr>
            <?php foreach ($columns as $col) :
                switch ($col) :
                    case 'name':
                        $nameOptions = [
                            'display'    => FormatPerson::FULL_LAST_FIRST,
                            'showStatus' => $options['showStatus'],
                            'showLabels' => $options['showLabels'],
                        ];?>
            <td><?php if ($options['showPhotos']) :?>
                <div class="row">
                    <div class="col-md-3">
                    <?php if (file_exists(sprintf('public/persons/photos/%s.jpg', $person['personId']))) : ?>
                        <img src="<?php echo $this->basePath() . sprintf("/persons/photos/%s.jpg", $person['personId']); ?>"
                    height="100px" alt="">
                    <?php endif;?></div>
                    <div class="col-md-9"><?php echo $this->formatPerson($person, $nameOptions);
                    ?></div>
                </div><?php
                else :
                      echo $this->formatPerson($person, $nameOptions);
                endif;
                ?></td>
                        <?php
                        break;
                    case 'email':
                        ?>
            <td><?php echo $this->email($person['email']);
            ?></td>
                        <?php
                        break;
                    case 'cellPhone':
                        ?>
            <td><?php echo $this->telephone(
                $person['cellPhone'],
                $person['cellPhoneHasWhatsApp'],
                $this->isAllowed('route/persons/person/edit-contact-info')
                );
                        ;?></td>
                        <?php
                        break;
                endswitch;
            endforeach;
            ?></tr><?php
        endforeach;
        ?></tbody>
    </table>
</div>
<div class="panel-footer"><?php
    $counts = [];
foreach ($resultsCount as $result => $count) {
    if ($count > 0) {
        $counts[] = $count . '&nbsp;' .
        ($count > 1 ? $this->translate(SchoenstattTable::CATEGORY_PLURALS[$result]) : $this->translate($result));
    }
}
if (count($counts) > 1) {
    echo $this->translate('Total') . ': <strong>' . $resultsTotal . '</strong>, ';
}
if (! empty($counts)) {
     echo implode(', ', $counts);
}
?>
</div>
</div>
<?php endif;
if ($areResults && $options['showEmailsButton'] && $this->isAllowed('emails_button')) {
    echo $this->clipboardButton()->clipboardWidget($this->translate('Emails'), implode(', ', $emails), $this->translate('Copy emails to clipboard'));
}?>
