<?php
use JTranslate\View\Helper\CountryName;
use Carbon\Carbon;

$object = $this->person;
$pageTitle = '';
$pageHeader = '';
if (!$object['isLiving']) {
    $pageTitle .= '✝';
    $pageHeader .= '✝';
}
if ($object['title']) {
    $title =  $this->escapeHtml($this->translate($object['title']));
    $pageTitle .= $title . ' ';
    $pageHeader .= $title . ' ';
}
$pageTitle .= $this->escapeHtml($object['fullFriendlyName']);
$pageHeader .= $this->escapeHtml($object['fullName']);
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($pageTitle);
?>
<h1<?php if (!$object['isLiving']) { echo ' class="text-center"';}?>><?php echo $pageHeader;?></h1>
<div class="row">
<div class="col-md-2<?php if (!$object['isLiving']) { echo ' col-md-offset-5';}?>">
<?php if (file_exists(sprintf('public/persons/photos/%s.jpg', $object['personId']))) : ?>
	<img src="<?php echo $this->basePath() . sprintf("/persons/photos/%s.jpg", $object['personId']); ?>"
	height="200px" alt="<?php echo $this->escapeHtmlAttr($object['firstName'].' '.$object['lastName']);?>">
<?php endif;?>
</div>
<?php if ($object['isLiving']):?>
<div class="col-md-10">
<div class="panel panel-default" id="contactInfoPanel">
    <div class="panel-heading">
    	<div class="row">
    	<div class="col-xs-4">
        	<h3 class="panel-title"><?php echo $this->translate('Contact Info'); //@todo add contact notes and modified date?>
        </h3>
        </div>
        <div class="col-xs-5">
        	<?php if (!is_null($object['contactInfoUpdatedOn'])) :?>
        		<span class="pull-right"><small><?php echo sprintf($this->translate('Updated %s'),
        		    $this->diffForHumans($object['contactInfoUpdatedOn']));?></small></span>
        	<?php endif;?>
        </div>
        </div>
	</div>
    <div class="panel-body">
    	<div class="row">
    	<?php if (isset($object['postStreet1'])) {
    	   $emailUrlCols = 5;
    	   $phoneCols = 4;
    	} else {
    	   $emailUrlCols = 7;
    	   $phoneCols = 5;
    	}?>
    	<div class="col-md-<?php echo $emailUrlCols;?>">
            <p><strong><?php echo $this->translate('Email'); ?>:</strong> <?php
            if (!is_null($object['email'])) { //@todo add checks for validated
                echo $this->email($object['email']);
                if (!is_null($object['email2'])) {
                    echo ', '.$this->email($object['email2']);
                }
            }?></p>
            <div class="row">
            <div class="col-md-12">
            	<div class="row"><div class="col-md-12">
            	<?php foreach ($object['urls'] as $urlRow) :?>
                	<a target="_blank" href="<?php echo $this->escapeHtmlAttr($urlRow['url']);?>">
                	    <img src="../<?php echo isset($urlRow['logo']) ? $this->escapeHtmlAttr($urlRow['logo']) : 'img/www.png';
                	    ?>" alt="<?php echo $this->escapeHtmlAttr($urlRow['label']);?>" class="img-circle" height="70px">
                	</a>&nbsp;
            	<?php endforeach; //@todo add email modified date?>
            	</div></div> <!-- Websites row and column -->
            </div> <!-- Links column -->
            </div> <!-- Links row -->
        </div>
        <?php if (isset($object['postStreet1'])) :?>
        <div class="col-md-3">
        	<p><strong><?php echo $this->translate('Postal address');?>:</strong></p>
			<?php echo $this->address([
			    'street1'    => $object['postStreet1'],
			    'street2'    => $object['postStreet2'],
			    'cityState'  => $object['postCityState'],
			    'zip'        => $object['postZip'],
			    'country'    => $object['postCountry'],
			]);?>
        </div>
        <?php endif;?>
        <div class="col-md-<?php echo $phoneCols;?>">
            <?php foreach ($object['phones'] as $phoneRow) : ?>
                <p><strong><?php echo $this->translate($phoneRow['label']); ?>:</strong>
				<span><?php echo $this->telephone($phoneRow['number'],
						isset($phoneRow['whatsApp']) ? $phoneRow['whatsApp'] : false,
						$this->isAllowed('route/persons/person/edit-contact-info'));?></span></p>
            <?php endforeach;
            if (!is_null($object['phonesUpdatedOn'])) :  //@todo add a question mark here with text
                //@todo use diffForHumans view helper
        	    $phoneUpdated = Carbon::instance($object['phonesUpdatedOn']); //@todo position this Up-to-date better ?>
                <p class="text-right"><?php echo $this->tooltip('✓ Up-to-date', sprintf($this->translate('Updated by %s %s'), 'jeff', $phoneUpdated->diffForHumans()));?></p>
        	<?php endif;?>
        	<!--
        	Phone numbers should be updated or confirmed every 2 years to ensure up-to-date information.
        	Please help in confirming and/or updating out-dated information.
        	 -->
		</div> <!-- phones column -->
        </div>
    </div> <!-- contact info panel body -->
</div> <!-- contact info panel -->
</div> <!-- col-md-9 -->
<?php endif;?>
</div> <!-- row -->

<div class="row"> <!-- personal info row -->
<div class="col-md-12">
<div class="panel panel-default" id="personalInfoPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Personal Info');?></h3>
	</div>
    <div class="panel-body">

<div class="row"> <!-- personal info panel row -->
<div class="col-md-6"> <!-- community info column (free and official) -->
<p><strong><?php echo $this->translate('Home country'); ?>:</strong> <?php echo $this->countryName($object['country'], true, CountryName::COUNTRY_NAME_OFFICIAL);?></p>
</div> <!-- community info column -->

<div class="col-md-6"> <!-- dates column -->
    <?php if (is_object($object['deathDate'])): ?>
        <p><strong><?php echo $this->translate('Passed away on'); ?>:</strong> <?php
        echo $this->dateFormat($object['deathDate'], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);?></p>
    <?php endif;
    if ($object['nameDay']) : ?>
    <p><strong><?php echo $this->translate('Nameday'); ?>: </strong>
        <?php echo $this->dayFormat($object['nameDay']);?>
    </p>
    <?php endif;?>
</div> <!-- dates column -->
</div> <!-- personal info panel row -->

</div> <!-- personal info panel body -->
</div> <!-- personal info panel -->
</div> <!-- personal info column 12 -->
</div> <!-- personal info row -->

<?php if ($this->isAllowed('patres_details')):?>
<div class="row"> <!-- private info row -->
<div class="col-md-12">
<div class="panel panel-default" id="privateInfoPanel">
    <div class="panel-heading">

    	<div class="row">
        <div class="col-xs-8">
            <h3 class="panel-title"><?php echo $this->translate('Private Info');?></h3>
        </div>
        <div class="col-xs-4">
        	<?php if ($this->isAllowed('route/persons/person/edit-private-info')) :  ?>
        	   <span class="pull-right"><a class="btn btn-default btn-sm"
                href="<?php echo $this->url('persons/person/edit-private-info', ['person_id' => $object['personId']]);?>"><?php
                echo $this->translate("Edit information");?></a></span>
        	<?php //elseif ($this->isAllowed('route/suggest')) : @todo enable searchForm
//         	   echo $this->partial('patres/patres/suggest-button',
//                 ['entityType' => 'person', 'entityId' => $object['personId'],
//                     'class' => 'btn btn-default btn-sm pull-right',
//                     'suggestForm' => $this->suggestForm,]);
            endif;?>
        </div>
        </div>
	</div>
    <div class="panel-body">

<div class="row"> <!-- private info panel row -->
<div class="col-md-6"> <!-- private facts column -->
    <p><strong><?php echo $this->translate('Birthday'); ?>: </strong> <?php
    if (is_object($object['birthDate'])) {
        echo $this->dateFormat($object['birthDate'], IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);
    }?></p>
<?php if (!empty($object['adminTags'])) :?>
<p><strong><?php echo $this->translate('Admin tags'); ?>:</strong> <?php
$adminTagFormat = '<span class="label label-default">%s</span>';
$formattedAdminTags = array();
foreach ($object['adminTags'] as $value) {
    $formattedAdminTags[] = sprintf($adminTagFormat, $this->escapeHtml($value));
}
echo implode(' ', $formattedAdminTags);?>
<?php endif;?>
</div> <!-- private facts column -->

<?php if (!is_null($object['adminNotes']) && $this->isAllowed('patres_details')): ?>
<div class="col-md-12">
    <p><strong><?php echo $this->translate('Admin Notes');?>:</strong></p>
    <div><?php echo $this->markdown($object['adminNotes']);?>
    </div>
</div> <!-- admin notes column -->
<?php endif;?>

</div> <!-- private info panel row -->

</div> <!-- private info panel body -->
</div> <!-- private info panel -->
</div> <!-- private info column 12 -->
</div> <!-- private info row -->
<?php endif;?>

<?php if (!empty($object['assignments'])) : ?>
<div class="row"> <!-- assignments row -->
<div class="col-md-12">
<div class="panel panel-default" id="assignmentsPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Assignments'); //@todo add "+" add button with link to new assignment?></h3>
	</div>
  <ul class="list-group">
   <?php foreach ($object['assignments'] as $assignment) :
   if ($assignment['active'] || $this->isAllowed('patres_details')) :?>
       <li class="list-group-item <?php if (!$assignment['active']) echo 'disabled';?>"><?php
           echo $this->formatPersonAssignment($assignment);?>
       </li>
   <?php endif;
   endforeach;?>
   </ul>
</div> <!-- assignments panel -->
</div> <!-- assignments column 12 -->
</div> <!-- assignments row -->
<?php endif;?>

<?php if (!is_null($object['publicNotes']) && 0 !== strlen($object['publicNotes'])):?>
<div class="row"> <!-- notes row -->
<div class="col-md-12">
<div class="panel panel-default" id="notesPanel">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Notes'); ?></h3>
	</div>
    <div class="panel-body">
    <div><?php echo $this->markdown($object['publicNotes']);?>
    </div>
	</div> <!-- notes panel body -->
</div> <!-- notes panel -->
</div> <!-- notes column 12 -->
</div> <!-- notes row -->
<?php endif;?>

<?php //@todo add date modified and counter?>

<div class="row"><div class="col-md-12">
<?php if ($this->isAllowed('route/persons/person/edit')):?>
      <a target="_blank" class="btn btn-primary"
    href="<?php echo $this->url('persons/person/edit', array('person_id' => $object['personId']));?>"><?php
    echo $this->translate("Edit details")?></a>
<?php endif;?>
</div></div>
