<?php

$this->headTitle()->setTranslatorEnabled(false);
$titleText = 'Suggestion %s';
$headText = 'Suggest Contact Info Update';
$this->headTitle(sprintf($this->translate($titleText), $this->person['fullFriendlyName'])); ?>
<h1><?php echo $this->translate($headText);?></h1>
<p class="lead"><?php echo $this->escapeHtml($this->person['fullName']);?></p>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('persons/person/suggest-contact-info',
		['person_id' => $this->person['personId']]));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('personId')); //print this here because the partial is reused for the create form
 echo $this->partial('fields-partial', [
     'form' => $form,
     'entity' => 'contactInfo',
 ]);
 echo $this->partial('patres/patres/suggest-common-form-fields', [
    'form' => $form,
    'options' => ['includeSelectizeCss' => false, 'includeSelectizeJs' => false]
 ]);
 echo $this->formRow($form->get('security'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
