<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$headText = 'New text';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>


<?php /** @var \Books\Form\TextForm $form */
$form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->form()->closeTag();
?>