<?php
use Cake\Utility\Text;
/** @var \Zend\View\Renderer\PhpRenderer $this */
echo $this->partial('search-bar', $this->vars);
//add a bar graph showing the distribution of search results in the life of JK
if (isset($this->objects)):
foreach ($this->objects as $object) :?>
<p><strong><?= $this->formatEntity('text', $object)?></strong>&nbsp;<?php
if (isset($this->search)) {
    echo Text::highlight(
        Text::excerpt($object['plainText'], $this->search),
        $this->search,
        ['format' => '<mark>\1</mark>']);
}?></p>
<?php endforeach;
else: 
$message = <<<MD
## To whomever may stumble across this page...

This is a work in progress to make Fr. Kentenich available to anyone
who is interested.

So far we have only imported the texts, but not yet parsed the metadata
describing the day on which each conference took place and the publication
from which it was extracted. Once we have that 
information, we can make present this information in a little nicer format. 

In any case, the texts are already searchable.

In the near future we hope to apply some artificial intelligence to abstract
brief summaries of each text, translate them to various language, and extract
keywords, concepts and person/place references from each.

The page should be accessible to any father who makes an account on this site
using the same email address as is recorded on schoenstatt-fathers.link. This
provides some simple, but precise access control until we decide as a movement
to open up Fr. Kentenich's writings to everyone.
MD;
echo $this->markdown($message);
endif;?>