<?php
/**
 * @param \Books\Form\TextForm $form
 * @param string $url
 */
/** @var \Zend\View\Renderer\PhpRenderer $this */
$form = $this->form;
if (isset($this->action) && !is_null($this->action)) {
    $form->setAttribute('action', $this->action);
} else {
    $form->setAttribute('action', $this->url('texts'));
}
$form->prepare();?>
<div class="row search-bar <?php if ($this->centerOnPage) {
  echo " search-bar-center";} ?>">
      <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div id="custom-search-input">
           <?php echo $this->form()->openTag($form); ?>
              <div class="input-group col-md-12">
                  <?php echo $this->formElement($form->get('search'));?>
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>
                      </button>
                  </span>
              </div>
            <?php
            echo $this->form()->closeTag();?>
          </div>
      </div>
</div>
 <?php //$this->inlineScript()->captureStart();
// echo <<<JS
// $(document).ready(function(){
//     $("form").submit(function(){
//         $("input, select").each(function(index, obj){
//             if($(obj).val() == "" || $(obj).val() == "false") {
//                 $(obj).remove();
//             }
//         });
//     });
// });
// JS;
// $this->inlineScript()->captureEnd();?>