<?php /** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = $this->translate($this->entity['title']);
$this->headTitle($headText);
$object = $this->entity;?>
<h1><?php echo $this->escapeHtml($headText);?></h1>

<i class="fa fa-calendar"></i> <?php echo $this->translate('Posted');?> <?php 
if (isset($this->entity['createdOn'])) {
    echo $this->diffForHumans($this->entity['createdOn']);
}?></p>
<p><i class="fa fa-tags"></i> <?php echo $this->translate('Tags');?>: <?php 
foreach ($object['tags'] as $tag) : ?>
<a href=""><span class="badge badge-info"><?php echo $this->escapeHtml($tag); //@todo translate this later?></span></a> 
<?php endforeach;?></p>
<hr>
<?php
if (isset($object['htmlText'])) {
    echo $object['htmlText'];
}?>
<hr>
    <!-- the comment box -->
<?php if (isset($this->commentForm)) {
    echo $this->partial('sion-model/comments/create', [
        'form' => $this->commentForm,
    ]);
}
echo $this->partial('sion-model/comments/comments-list', [
    'comments' => $this->comments,
]);

if (isset($this->schema)) {
    /** @var \Spatie\SchemaOrg\BlogPosting $schema */
    $schema = $this->schema;
    $thisUrl = $this->serverUrl().$this->url(null, [], [], true);
    $schema->setProperty('url', $thisUrl);
    echo $schema->toScript();
}?>
