<div class="table-responsive">
<table>
<tr><?php
if (isset($this->publications) && is_array($this->publications)):?><th></th><?php endif;?>
<th><?php echo $this->translate('Barcode');?></th>
<th><?php echo $this->translate('Call number');?></th>
<th><?php echo $this->translate('Author');?></th>
</tr>
<?php foreach ($this->objects as $bookId => $book) : ?>
<tr>
    <?php if (isset($this->publications) && is_array($this->publications)):?><th><?php
    if (!is_null($book['publicationId']) && array_key_exists($book['publicationId'], $this->publications) &&
        !is_null($this->publications[$book['publicationId']]['coverThumbnail80pxUri'])):?>
    <a href="<?php echo $this->url('publications/publication', ['publication_id' => $book['publicationId']]); ?>">
    <img src="<?php echo $this->publications[$book['publicationId']]['coverThumbnail80pxUri']; ?>"
    height="80px" alt="<?php echo $this->escapeHtmlAttr($this->publications[$book['publicationId']]['title']);?>"></a>
    <?php endif;?>
    </th><?php endif;?>
	<td><?php echo $this->escapeHtml($book['withinLibraryId']);?></td>
	<td><?php echo $this->escapeHtml($book['callNumber']);?></td>
	<td><?php echo $this->escapeHtml($book['authorsText']);?></td>
</tr>
<?php endforeach;?>
</table>
</div>