<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$headText = 'Create new library';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$this->formSelect()->setTranslatorEnabled(false);
$form->setAttribute('action', $this->url(null, [], [], true));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', [
     'form' => $form,
 ]);
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
    ?>
