<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-selectize-markdown.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . "/js/gen-selectize-markdown-$lang.js");
$form = $this->form;
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('filiationId'));
echo $this->formRow($form->get('contactPersonId'));
if ($this->isAllowed('route/persons/create')):?>
<p><?php echo $this->translate('Not in the list?')?> <a target="_blank" href="<?php
echo $this->url('persons/create');?>"><?php echo $this->translate('Add new person'); ?></a>
    <?php if ($this->isAllowed('route/admin/import-father')):?>
    or <a target="_blank" href="<?php echo $this->url('admin/import-father');?>"><?php echo $this->translate('Import from Patres')?></a>
    <?php endif;
?></p><?php
endif;
echo $this->formRow($form->get('contactEmail'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('mainShowDisplay'));
echo $this->formRow($form->get('viewRole'));
echo $this->formRow($form->get('defaultCheckoutTimePeriodInDays'));
echo $this->formRow($form->get('checkoutPersonListKind'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('defaultCheckoutPersonId'));
echo $this->formRow($form->get('mainCollectionId'));
echo $this->formRow($form->get('callNumberRegex'));
echo $this->formRow($form->get('callNumberPlaceholder'));
echo $this->formRow($form->get('callNumberHelpText'));
echo $this->formRow($form->get('callNumberExplanation'));
echo $this->formRow($form->get('sortTextFormat'));
echo $this->formRow($form->get('labelLine1'));
echo $this->formRow($form->get('labelLine2'));
echo $this->formRow($form->get('labelLine3'));
echo $this->formRow($form->get('barcodeText'));
echo $this->formRow($form->get('adminNotes'));
echo $this->formRow($form->get('isActive'));
echo $this->formRow($form->get('enableCheckouts'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('checkoutBooksRole'));
echo $this->formRow($form->get('createCheckoutsIfCheckingInANonCheckedOutBook'));
echo $this->formRow($form->get('useCollections'));
echo $this->formRow($form->get('allowCollectionlessBooks'));
echo $this->formRow($form->get('requireCallNumbers'));
echo $this->formRow($form->get('enforceCallNumberRegex'));
echo $this->formRow($form->get('security'));

$jsScript = <<<JS
$("select[name='filiationId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='contactPersonId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='mainCollectionId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='defaultCheckoutPersonId']").selectize({
    create: false,
    sortField: 'text'
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
?>
