<?php
$this->headScript()->appendFile($this->basePath() . "/js/books-inactivate-books.js");
$headText = 'Inactivate books';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('libraries/library/inactivate-books', ['library_id' => $this->libraryId]));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('inactivationReason'));
echo $this->formRow($form->get('withinLibraryIds'));?>
<ul id="book-list" class="list-unstyled"></ul>
<?php echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
