<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = 'Schoenstatt Library System';
$this->headTitle($headText);?>
<h1><?php echo $this->translate($headText);?></h1>
<p><?php echo $this->translate("The Schoenstatt Library System was developed in the Schoenstatt Fathers' seminary in Santiago, Chile to help with studies, but is made available to the whole Schoenstatt family with 3 objectives:");?></p>
<ol>
  <li><?php echo $this->translate("To develop a comprehensive, open, and up-to-date catalog of Schoenstatt literature");?></li>
  <li><?php echo $this->translate("To help Father Kentenich scholars locate rare books and manuscripts");?></li>
  <li><?php echo $this->translate("To encourage collaboration within the Schoenstatt family to further our knowledge of Father Kentenich's thinking and mission in the world");?></li>
</ol>
<p><?php echo str_replace('contact us', '<a href="mailto:webmaster@schoenstatt.link">contact us</a>', $this->translate("Please contact us if you are willing to help with the project or if you would like to add a library to the catalog."));?></p>
<?php echo $this->partial('library-list', $this->vars);?>