<?php /** @var \Laminas\View\Renderer\PhpRenderer $this */?>

<?php if ($this->isAllowed('route/libraries/create')) : ?>
    <p><a href="<?= $this->url('libraries/create')?>" class="btn btn-primary pull-right">
            <?=$this->translate('Create new library');?></a></p>
<?php endif; ?>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="list-group">
<?php foreach ($this->objects as $libraryId => $library) :
//don't show the libraries the user doesn't have permission to see
    if (! $this->isAllowed($library['resourceId'], 'show')) {
        continue;
    }?>
    <a href="<?php echo $this->url('libraries/library', ['library_id' => $libraryId]);?>" class="list-group-item">
        <span class="badge alert-info"><?php echo $this->escapeHtml($library['bookCount']); ?></span>
    <h4 class="list-group-item-heading"><?php echo $this->formatEntity('library', $library, ['displayEditPencil' => false, 'displayAsLink' => false]);?></h4>
    <?php if (isset($library['description'])) :?>
    <p class="list-group-item-text"><?php echo $this->escapeHtml($this->translate($library['description']));?></p>
    <?php endif;?></a>
<?php endforeach;?>
</div>
</div>
</div>