<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
/**
 * @param array $queryParams
 * @param mixed[] $library
 * @param mixed[] $borrowers
 * @param bool $simulate
 */
$headText = 'Book notices for %s';
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle(sprintf($headText, $this->library['name']));
$queryParams = $this->queryParams;?>
<h1><?php echo sprintf($this->translate($headText), $this->formatEntity('library', $this->library, ['displayEditPencil' => false]));?></h1>
<?php //@todo add feed back to user whether the email was successfully sent in the case of a non-simulation
if (isset($this->simulate) && $this->simulate) :?>
<p><?php echo $this->translate('All following emails are a simulation, click "Send now" to send emails.')?></p>
<p><a href="<?php $queryParams['simulate'] = 0;
echo $this->url(null, [], ['query' => $queryParams], true);?>" class="btn btn-primary"><?php echo $this->translate('Send emails now');?></a>
<?php endif;
foreach ($this->borrowers as $object) :?>
<h2><?php echo $this->formatEntity('borrower', $object);?></h2>
<p><?php echo $this->translate('Email');?>: <?php echo $this->escapeHtml($object['email']);?></p>
<p><?php echo $this->translate('Locale');?>: <?php echo $this->escapeHtml($object['primaryLocale']);?></p>
    <?php echo $this->partial('books/checkouts/checkout-list', [
    'entities' => $object['checkouts'],
    'columns' => ['withinLibraryId', 'callNumber', 'book', 'checkedOutOn', 'dueOn'],
    ]);
endforeach;
