<?php /** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Books\Model\LibraryOptions $libraryOptions */
$libraryOptions = $this->entity['options'];
if (!empty($this->entity['collectionCategoryStatistics']) && is_null($this->books)):?>
    <?php foreach ($this->entity['collectionCategoryStatistics'] as $collectionId => $categories) :
        $collectionName = isset($libraryOptions->collections[$collectionId]) ?
            $this->translate($libraryOptions->collections[$collectionId]->name) :
            sprintf('(%s)', $this->translate('none'));?>
        <h3 id="collection_<?php echo $this->escapeHtmlAttr($collectionId);?>">
        <a href="<?= $this->url(null, [], ['query' => ['collectionId' => $collectionId]], true);?>"><?php echo $this->escapeHtml($collectionName);?></a>
        <?php if (isset($libraryOptions->collections[$collectionId]) && $this->isAllowed($this->entity['resourceId'], 'administrate')) {
            echo $this->editPencil('collection', $collectionId);
        }?></h3>
    	<ul class="list-group">
    	<?php foreach ($categories as $category => $count) : ?>
        	<li class="list-group-item">
                <span class="badge"><?php echo $this->escapeHtml($count);?></span>
                <a href="<?php echo $this->url('libraries/library', ['library_id' => $this->entityId],
                        ['query' => ['category' => $category, 'collectionId' => $collectionId === 0 ? '' : $collectionId]]);?>"><?php
                if (!isset($category) || strlen($category) === 0) {
                    $category = sprintf('(%s)', $this->translate('none'));
                }
                echo $this->escapeHtml($category);?></a>
          	</li>
		<?php endforeach;?>
    	</ul>
	<?php endforeach;
else:
    echo $this->partial('books/library/book-list', [
        'entities'  => $this->books,
        'borrowers' => $this->borrowers,
        'publications'  => $this->publications,
    ]);
endif;?>