<?php use Books\Model\LibraryOptions;
$this->headTitle()->setTranslatorEnabled(false);
$object = $this->entity;
$entityId = $this->entityId;
$this->headTitle($object['name']);
echo $this->partial('books/library/search-bar', [
    'form' => $this->form,
    'action'    => $this->url('libraries/library', ['library_id' => $entityId]),
]);?>
<h1><?php echo $this->escapeHtml($object['name']);?></h1>
<div class="row"><?php if ($object['options']->enableCheckouts && $this->isAllowed($object['resourceId'], 'checkout')):?>
<a class="btn btn-primary" href="<?php echo $this->url('libraries/library/checkout',
        ['library_id' => $entityId]);?>"><?php echo $this->escapeHtml($this->translate('Checkout books'));?></a><?php
endif;?>
<?php if ($this->isAllowed($object['resourceId'], 'administrate')):?><a class="btn btn-default pull-right" href="<?php echo $this->url('libraries/library/admin',
        ['library_id' => $entityId]);?>"><?php echo $this->escapeHtml($this->translate('Admin menu'));?></a>
<?php endif;
?></div>

<?php
/** @var LibraryOptions $libraryOptions */
$libraryOptions = $this->entity['options'];
echo $this->partial($libraryOptions->mainShowDisplay, $this->vars);
?>