<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css');
$this->headScript()->appendFile($this->basePath() . '/js/selectize.min.js');
$form = $this->form;
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('associationId'));
echo $this->formRow($form->get('roleTitle'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('sort'));
echo $this->formRow($form->get('isSinglePosition'));
echo $this->formRow($form->get('isMainRole'));
echo $this->formRow($form->get('isMainContact'));
echo $this->formRow($form->get('isActive'));
echo $this->formRow($form->get('security'));

$jsScript = <<<JS
$("select[name='roleTitle']").selectize({
    create: true,
    maxItems: 1,
    sortField: 'text'
});

JS;

$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
