<p><?php if ($this->isAllowed('route/roles/create')):?>
<a href="<?php echo $this->url('roles/create');?>"><?php
    echo $this->translate('Create new role');?></a><?php
endif;?></p>
<div class="table-responsive">
	<table class="table">
		<tr>
			<th><?php echo $this->translate("Association");?></th>
			<th><?php echo $this->translate("Role");?></th>
			<th><?php echo $this->translate("Main role");?></th>
			<th><?php echo $this->translate("Main contact");?></th>
			<th><?php echo $this->translate("Single position");?></th>
			<th><?php echo $this->translate("Sort");?></th>
		</tr>
		<?php foreach ($this->objects as $entity): ?>
		<tr>
			<td><?php echo $this->formatEntity('association', $entity['association']);?>
			</td>
			<td><?php echo $this->formatEntity('role', $entity);
                if (!$entity['isActive']) {
                    echo '&nbsp;'.$this->label('Inactive', 'label-info');
                }?>
			</td>
			<td><?php echo $entity['isMainRole'] ? $this->translate('yes'): 'no';?></td>
			<td><?php echo $entity['isMainContact'] ? $this->translate('yes'): 'no';?></td>
			<td><?php echo $entity['isSinglePosition'] ? $this->translate('yes'): 'no';?></td>
			<td><?php echo $this->escapeHtml($entity['sort']);?>
			</td>
			<?php endforeach; ?>
		</tr>
	</table>
</div>
