<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Schoenstatt\Module'                        => __DIR__ . '/Module.php',
    'Schoenstatt\Controller\SkeletonController' => __DIR__ . '/src/Schoenstatt/Controller/SkeletonController.php',
    'SchoenstattTest\Framework\TestCase'        => __DIR__ . '/tests/Schoenstatt/Framework/TestCase.php',
    'SchoenstattTest\SampleTest'                => __DIR__ . '/tests/Schoenstatt/SampleTest.php',
);