#submitted 2019-06-13
CREATE TABLE `ourlink_db1`.`bib_greek_root_words` ( `word_id` INT NOT NULL AUTO_INCREMENT , `root` VARCHAR(100) NOT NULL , `part_of_speech` VARCHAR(50) NULL DEFAULT NULL , `first_verse_ occurrence` INT(8) UNSIGNED ZEROFILL NULL DEFAULT NULL , `occurrence_count` INT NULL DEFAULT NULL , `gender` ENUM('m','f','n') NULL DEFAULT NULL COMMENT 'Only for nouns' , `paradigm_part_1` VARCHAR(100) NULL DEFAULT NULL , `paradigm_part_2` VARCHAR(100) NULL DEFAULT NULL , `paradigm_part_3` VARCHAR(100) NULL DEFAULT NULL , `paradigm_part_4` VARCHAR(100) NULL DEFAULT NULL , `forms_available` VARCHAR(255) NULL DEFAULT NULL COMMENT 'pipe-separated list of forms' , `dictionary_entry_id` INT NULL DEFAULT NULL , PRIMARY KEY (`word_id`), UNIQUE (`root`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;
ALTER TABLE `bib_greek_root_words` CHANGE `word_id` `root_id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `bib_greek_root_words` ADD `john_occurrence_count` INT NOT NULL DEFAULT '0' AFTER `dictionary_entry_id`, ADD `john_first_verse_occurrence` INT(8) UNSIGNED ZEROFILL NULL DEFAULT NULL AFTER `john_occurrence_count`;
ALTER TABLE `bib_books` ADD `jeresp_abbreviation` VARCHAR(10) NULL DEFAULT NULL AFTER `alt_id_septnt`;
UPDATE `bib_books` SET `jeresp_abbreviation`='Gn' WHERE (`book_id`=1);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ex' WHERE (`book_id`=2);
UPDATE `bib_books` SET `jeresp_abbreviation`='Lv' WHERE (`book_id`=3);
UPDATE `bib_books` SET `jeresp_abbreviation`='Nm' WHERE (`book_id`=4);
UPDATE `bib_books` SET `jeresp_abbreviation`='Dt' WHERE (`book_id`=5);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jos' WHERE (`book_id`=6);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jc' WHERE (`book_id`=7);
UPDATE `bib_books` SET `jeresp_abbreviation`='Rt' WHERE (`book_id`=8);
UPDATE `bib_books` SET `jeresp_abbreviation`='1S' WHERE (`book_id`=9);
UPDATE `bib_books` SET `jeresp_abbreviation`='2S' WHERE (`book_id`=10);
UPDATE `bib_books` SET `jeresp_abbreviation`='1R' WHERE (`book_id`=11);
UPDATE `bib_books` SET `jeresp_abbreviation`='2R' WHERE (`book_id`=12);
UPDATE `bib_books` SET `jeresp_abbreviation`='1Cro' WHERE (`book_id`=13);
UPDATE `bib_books` SET `jeresp_abbreviation`='2Cro' WHERE (`book_id`=14);
UPDATE `bib_books` SET `jeresp_abbreviation`='Esd' WHERE (`book_id`=15);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ne' WHERE (`book_id`=16);
UPDATE `bib_books` SET `jeresp_abbreviation`='Tb' WHERE (`book_id`=73);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jdt' WHERE (`book_id`=74);
UPDATE `bib_books` SET `jeresp_abbreviation`='Est' WHERE (`book_id`=17);
UPDATE `bib_books` SET `jeresp_abbreviation`='1M' WHERE (`book_id`=82);
UPDATE `bib_books` SET `jeresp_abbreviation`='2M' WHERE (`book_id`=83);
UPDATE `bib_books` SET `jeresp_abbreviation`='Sal' WHERE (`book_id`=19);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ct' WHERE (`book_id`=22);
UPDATE `bib_books` SET `jeresp_abbreviation`='Lm' WHERE (`book_id`=25);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jb' WHERE (`book_id`=18);
UPDATE `bib_books` SET `jeresp_abbreviation`='Pr' WHERE (`book_id`=20);
UPDATE `bib_books` SET `jeresp_abbreviation`='Qo' WHERE (`book_id`=21);
UPDATE `bib_books` SET `jeresp_abbreviation`='Sb' WHERE (`book_id`=76);
UPDATE `bib_books` SET `jeresp_abbreviation`='Si' WHERE (`book_id`=77);
UPDATE `bib_books` SET `jeresp_abbreviation`='Is' WHERE (`book_id`=23);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jr' WHERE (`book_id`=24);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ba' WHERE (`book_id`=78);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ez' WHERE (`book_id`=26);
UPDATE `bib_books` SET `jeresp_abbreviation`='Dn' WHERE (`book_id`=27);
UPDATE `bib_books` SET `jeresp_abbreviation`='Os' WHERE (`book_id`=28);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jl' WHERE (`book_id`=29);
UPDATE `bib_books` SET `jeresp_abbreviation`='Am' WHERE (`book_id`=30);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ab' WHERE (`book_id`=31);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jon' WHERE (`book_id`=32);
UPDATE `bib_books` SET `jeresp_abbreviation`='Mi' WHERE (`book_id`=33);
UPDATE `bib_books` SET `jeresp_abbreviation`='Na' WHERE (`book_id`=34);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ha' WHERE (`book_id`=35);
UPDATE `bib_books` SET `jeresp_abbreviation`='So' WHERE (`book_id`=36);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ag' WHERE (`book_id`=37);
UPDATE `bib_books` SET `jeresp_abbreviation`='Za' WHERE (`book_id`=38);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ml' WHERE (`book_id`=39);
UPDATE `bib_books` SET `jeresp_abbreviation`='Mt' WHERE (`book_id`=40);
UPDATE `bib_books` SET `jeresp_abbreviation`='Mc' WHERE (`book_id`=41);
UPDATE `bib_books` SET `jeresp_abbreviation`='Lc' WHERE (`book_id`=42);
UPDATE `bib_books` SET `jeresp_abbreviation`='Jn' WHERE (`book_id`=43);
UPDATE `bib_books` SET `jeresp_abbreviation`='Hch' WHERE (`book_id`=44);
UPDATE `bib_books` SET `jeresp_abbreviation`='Rm' WHERE (`book_id`=45);
UPDATE `bib_books` SET `jeresp_abbreviation`='1Co' WHERE (`book_id`=46);
UPDATE `bib_books` SET `jeresp_abbreviation`='2Co' WHERE (`book_id`=47);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ga' WHERE (`book_id`=48);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ef' WHERE (`book_id`=49);
UPDATE `bib_books` SET `jeresp_abbreviation`='Flp' WHERE (`book_id`=50);
UPDATE `bib_books` SET `jeresp_abbreviation`='Col' WHERE (`book_id`=51);
UPDATE `bib_books` SET `jeresp_abbreviation`='1Ts' WHERE (`book_id`=52);
UPDATE `bib_books` SET `jeresp_abbreviation`='2Ts' WHERE (`book_id`=53);
UPDATE `bib_books` SET `jeresp_abbreviation`='1Tm' WHERE (`book_id`=54);
UPDATE `bib_books` SET `jeresp_abbreviation`='2Tm' WHERE (`book_id`=55);
UPDATE `bib_books` SET `jeresp_abbreviation`='Tt' WHERE (`book_id`=56);
UPDATE `bib_books` SET `jeresp_abbreviation`='Flm' WHERE (`book_id`=57);
UPDATE `bib_books` SET `jeresp_abbreviation`='Hb' WHERE (`book_id`=58);
UPDATE `bib_books` SET `jeresp_abbreviation`='St' WHERE (`book_id`=59);
UPDATE `bib_books` SET `jeresp_abbreviation`='1P' WHERE (`book_id`=60);
UPDATE `bib_books` SET `jeresp_abbreviation`='2P' WHERE (`book_id`=61);
UPDATE `bib_books` SET `jeresp_abbreviation`='1Jn' WHERE (`book_id`=62);
UPDATE `bib_books` SET `jeresp_abbreviation`='2Jn' WHERE (`book_id`=63);
UPDATE `bib_books` SET `jeresp_abbreviation`='3Jn' WHERE (`book_id`=64);
UPDATE `bib_books` SET `jeresp_abbreviation`='Judas' WHERE (`book_id`=65);
UPDATE `bib_books` SET `jeresp_abbreviation`='Ap' WHERE (`book_id`=66);

ALTER TABLE `bib_books` CHANGE `jeresp_abbreviation` `abbreviation_jerusalem_es` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `bib_books` ADD `abbreviation_jerusalem_en` VARCHAR(10) NULL DEFAULT NULL AFTER `abbreviation_jerusalem_es`;
