
ALTER TABLE `bib_books` ADD `alt_id_njb` INT NULL DEFAULT NULL AFTER `alt_id_1`;
UPDATE `bib_books` SET `alt_id_njb`=3068 WHERE `book_id` = 1;
UPDATE `bib_books` SET `alt_id_njb`=3069 WHERE `book_id` = 2;
UPDATE `bib_books` SET `alt_id_njb`=3070 WHERE `book_id` = 3;
UPDATE `bib_books` SET `alt_id_njb`=3071 WHERE `book_id` = 4;
UPDATE `bib_books` SET `alt_id_njb`=3072 WHERE `book_id` = 5;
UPDATE `bib_books` SET `alt_id_njb`=3073 WHERE `book_id` = 6;
UPDATE `bib_books` SET `alt_id_njb`=3074 WHERE `book_id` = 7;
UPDATE `bib_books` SET `alt_id_njb`=3075 WHERE `book_id` = 8;
UPDATE `bib_books` SET `alt_id_njb`=3076 WHERE `book_id` = 9;
UPDATE `bib_books` SET `alt_id_njb`=3077 WHERE `book_id` = 10;
UPDATE `bib_books` SET `alt_id_njb`=3078 WHERE `book_id` = 11;
UPDATE `bib_books` SET `alt_id_njb`=3079 WHERE `book_id` = 12;
UPDATE `bib_books` SET `alt_id_njb`=3080 WHERE `book_id` = 13;
UPDATE `bib_books` SET `alt_id_njb`=3081 WHERE `book_id` = 14;
UPDATE `bib_books` SET `alt_id_njb`=3082 WHERE `book_id` = 15;
UPDATE `bib_books` SET `alt_id_njb`=3083 WHERE `book_id` = 16;
UPDATE `bib_books` SET `alt_id_njb`=3084 WHERE `book_id` = 73;
UPDATE `bib_books` SET `alt_id_njb`=3085 WHERE `book_id` = 74;
UPDATE `bib_books` SET `alt_id_njb`=3086 WHERE `book_id` = 17;
UPDATE `bib_books` SET `alt_id_njb`=3089 WHERE `book_id` = 82;
UPDATE `bib_books` SET `alt_id_njb`=3090 WHERE `book_id` = 83;
UPDATE `bib_books` SET `alt_id_njb`=3088 WHERE `book_id` = 19;
UPDATE `bib_books` SET `alt_id_njb`=3093 WHERE `book_id` = 22;
UPDATE `bib_books` SET `alt_id_njb`=3098 WHERE `book_id` = 25;
UPDATE `bib_books` SET `alt_id_njb`=3087 WHERE `book_id` = 18;
UPDATE `bib_books` SET `alt_id_njb`=3091 WHERE `book_id` = 20;
UPDATE `bib_books` SET `alt_id_njb`=3092 WHERE `book_id` = 21;
UPDATE `bib_books` SET `alt_id_njb`=3094 WHERE `book_id` = 76;
UPDATE `bib_books` SET `alt_id_njb`=3095 WHERE `book_id` = 77;
UPDATE `bib_books` SET `alt_id_njb`=3096 WHERE `book_id` = 23;
UPDATE `bib_books` SET `alt_id_njb`=3097 WHERE `book_id` = 24;
UPDATE `bib_books` SET `alt_id_njb`=3099 WHERE `book_id` = 78;
UPDATE `bib_books` SET `alt_id_njb`=3100 WHERE `book_id` = 26;
UPDATE `bib_books` SET `alt_id_njb`=3101 WHERE `book_id` = 27;
UPDATE `bib_books` SET `alt_id_njb`=3102 WHERE `book_id` = 28;
UPDATE `bib_books` SET `alt_id_njb`=3103 WHERE `book_id` = 29;
UPDATE `bib_books` SET `alt_id_njb`=3104 WHERE `book_id` = 30;
UPDATE `bib_books` SET `alt_id_njb`=3105 WHERE `book_id` = 31;
UPDATE `bib_books` SET `alt_id_njb`=3106 WHERE `book_id` = 32;
UPDATE `bib_books` SET `alt_id_njb`=3107 WHERE `book_id` = 33;
UPDATE `bib_books` SET `alt_id_njb`=3108 WHERE `book_id` = 34;
UPDATE `bib_books` SET `alt_id_njb`=3109 WHERE `book_id` = 35;
UPDATE `bib_books` SET `alt_id_njb`=3110 WHERE `book_id` = 36;
UPDATE `bib_books` SET `alt_id_njb`=3111 WHERE `book_id` = 37;
UPDATE `bib_books` SET `alt_id_njb`=3112 WHERE `book_id` = 38;
UPDATE `bib_books` SET `alt_id_njb`=3113 WHERE `book_id` = 39;
UPDATE `bib_books` SET `alt_id_njb`=3114 WHERE `book_id` = 40;
UPDATE `bib_books` SET `alt_id_njb`=3115 WHERE `book_id` = 41;
UPDATE `bib_books` SET `alt_id_njb`=3116 WHERE `book_id` = 42;
UPDATE `bib_books` SET `alt_id_njb`=3117 WHERE `book_id` = 43;
UPDATE `bib_books` SET `alt_id_njb`=3118 WHERE `book_id` = 44;
UPDATE `bib_books` SET `alt_id_njb`=3119 WHERE `book_id` = 45;
UPDATE `bib_books` SET `alt_id_njb`=3120 WHERE `book_id` = 46;
UPDATE `bib_books` SET `alt_id_njb`=3121 WHERE `book_id` = 47;
UPDATE `bib_books` SET `alt_id_njb`=3122 WHERE `book_id` = 48;
UPDATE `bib_books` SET `alt_id_njb`=3123 WHERE `book_id` = 49;
UPDATE `bib_books` SET `alt_id_njb`=3124 WHERE `book_id` = 50;
UPDATE `bib_books` SET `alt_id_njb`=3125 WHERE `book_id` = 51;
UPDATE `bib_books` SET `alt_id_njb`=3126 WHERE `book_id` = 52;
UPDATE `bib_books` SET `alt_id_njb`=3127 WHERE `book_id` = 53;
UPDATE `bib_books` SET `alt_id_njb`=3128 WHERE `book_id` = 54;
UPDATE `bib_books` SET `alt_id_njb`=3129 WHERE `book_id` = 55;
UPDATE `bib_books` SET `alt_id_njb`=3130 WHERE `book_id` = 56;
UPDATE `bib_books` SET `alt_id_njb`=3131 WHERE `book_id` = 57;
UPDATE `bib_books` SET `alt_id_njb`=3132 WHERE `book_id` = 58;
UPDATE `bib_books` SET `alt_id_njb`=3133 WHERE `book_id` = 59;
UPDATE `bib_books` SET `alt_id_njb`=3134 WHERE `book_id` = 60;
UPDATE `bib_books` SET `alt_id_njb`=3135 WHERE `book_id` = 61;
UPDATE `bib_books` SET `alt_id_njb`=3136 WHERE `book_id` = 62;
UPDATE `bib_books` SET `alt_id_njb`=3137 WHERE `book_id` = 63;
UPDATE `bib_books` SET `alt_id_njb`=3138 WHERE `book_id` = 64;
UPDATE `bib_books` SET `alt_id_njb`=3139 WHERE `book_id` = 65;
UPDATE `bib_books` SET `alt_id_njb`=3140 WHERE `book_id` = 66;

INSERT INTO bib_verses
(translation_id, verse_id, book_id, chapter, verse, text)
SELECT 'njb' AS translation_id, CONCAT(LPAD(b.book_id, 2, '0'), LPAD(j.chapter, 3, '0'), LPAD(j.verse, 3, '0')) AS verse_id, b.book_id, j.chapter, j.verse, j.text FROM `bib_jeru_en_temp` j INNER JOIN `bib_books` b ON b.`alt_id_njb` = j.`book_id`;


ALTER TABLE `bib_books` ADD `alt_id_septnt` INT NULL DEFAULT NULL AFTER `alt_id_njb`;
ALTER TABLE `bib_books` CHANGE `alt_id_1` `alt_id_jeresp` INT(11) NULL DEFAULT NULL;

UPDATE `bib_books` SET `alt_id_septnt`=4474 WHERE `book_id` = 1;
UPDATE `bib_books` SET `alt_id_septnt`=4475 WHERE `book_id` = 2;
UPDATE `bib_books` SET `alt_id_septnt`=4476 WHERE `book_id` = 3;
UPDATE `bib_books` SET `alt_id_septnt`=4477 WHERE `book_id` = 4;
UPDATE `bib_books` SET `alt_id_septnt`=4478 WHERE `book_id` = 5;
UPDATE `bib_books` SET `alt_id_septnt`=4479 WHERE `book_id` = 6;
UPDATE `bib_books` SET `alt_id_septnt`=4480 WHERE `book_id` = 7;
UPDATE `bib_books` SET `alt_id_septnt`=4481 WHERE `book_id` = 8;
UPDATE `bib_books` SET `alt_id_septnt`=4482 WHERE `book_id` = 9;
UPDATE `bib_books` SET `alt_id_septnt`=4483 WHERE `book_id` = 10;
UPDATE `bib_books` SET `alt_id_septnt`=4484 WHERE `book_id` = 11;
UPDATE `bib_books` SET `alt_id_septnt`=4485 WHERE `book_id` = 12;
UPDATE `bib_books` SET `alt_id_septnt`=4486 WHERE `book_id` = 13;
UPDATE `bib_books` SET `alt_id_septnt`=4487 WHERE `book_id` = 14;
UPDATE `bib_books` SET `alt_id_septnt`=4488 WHERE `book_id` = 15;
UPDATE `bib_books` SET `alt_id_septnt`=4489 WHERE `book_id` = 16;
UPDATE `bib_books` SET `alt_id_septnt`=4490 WHERE `book_id` = 73;
UPDATE `bib_books` SET `alt_id_septnt`=4491 WHERE `book_id` = 74;
UPDATE `bib_books` SET `alt_id_septnt`=4492 WHERE `book_id` = 17;
UPDATE `bib_books` SET `alt_id_septnt`=4495 WHERE `book_id` = 82;
UPDATE `bib_books` SET `alt_id_septnt`=4496 WHERE `book_id` = 83;
UPDATE `bib_books` SET `alt_id_septnt`=4494 WHERE `book_id` = 19;
UPDATE `bib_books` SET `alt_id_septnt`=4499 WHERE `book_id` = 22;
UPDATE `bib_books` SET `alt_id_septnt`=4504 WHERE `book_id` = 25;
UPDATE `bib_books` SET `alt_id_septnt`=4493 WHERE `book_id` = 18;
UPDATE `bib_books` SET `alt_id_septnt`=4497 WHERE `book_id` = 20;
UPDATE `bib_books` SET `alt_id_septnt`=4498 WHERE `book_id` = 21;
UPDATE `bib_books` SET `alt_id_septnt`=4500 WHERE `book_id` = 76;
UPDATE `bib_books` SET `alt_id_septnt`=4501 WHERE `book_id` = 77;
UPDATE `bib_books` SET `alt_id_septnt`=4502 WHERE `book_id` = 23;
UPDATE `bib_books` SET `alt_id_septnt`=4503 WHERE `book_id` = 24;
UPDATE `bib_books` SET `alt_id_septnt`=4505 WHERE `book_id` = 78;
UPDATE `bib_books` SET `alt_id_septnt`=4506 WHERE `book_id` = 26;
UPDATE `bib_books` SET `alt_id_septnt`=4507 WHERE `book_id` = 27;
UPDATE `bib_books` SET `alt_id_septnt`=4508 WHERE `book_id` = 28;
UPDATE `bib_books` SET `alt_id_septnt`=4509 WHERE `book_id` = 29;
UPDATE `bib_books` SET `alt_id_septnt`=4510 WHERE `book_id` = 30;
UPDATE `bib_books` SET `alt_id_septnt`=4511 WHERE `book_id` = 31;
UPDATE `bib_books` SET `alt_id_septnt`=4512 WHERE `book_id` = 32;
UPDATE `bib_books` SET `alt_id_septnt`=4513 WHERE `book_id` = 33;
UPDATE `bib_books` SET `alt_id_septnt`=4514 WHERE `book_id` = 34;
UPDATE `bib_books` SET `alt_id_septnt`=4515 WHERE `book_id` = 35;
UPDATE `bib_books` SET `alt_id_septnt`=4516 WHERE `book_id` = 36;
UPDATE `bib_books` SET `alt_id_septnt`=4517 WHERE `book_id` = 37;
UPDATE `bib_books` SET `alt_id_septnt`=4518 WHERE `book_id` = 38;
UPDATE `bib_books` SET `alt_id_septnt`=4519 WHERE `book_id` = 39;
UPDATE `bib_books` SET `alt_id_septnt`=4520 WHERE `book_id` = 40;
UPDATE `bib_books` SET `alt_id_septnt`=4521 WHERE `book_id` = 41;
UPDATE `bib_books` SET `alt_id_septnt`=4522 WHERE `book_id` = 42;
UPDATE `bib_books` SET `alt_id_septnt`=4523 WHERE `book_id` = 43;
UPDATE `bib_books` SET `alt_id_septnt`=4524 WHERE `book_id` = 44;
UPDATE `bib_books` SET `alt_id_septnt`=4525 WHERE `book_id` = 45;
UPDATE `bib_books` SET `alt_id_septnt`=4526 WHERE `book_id` = 46;
UPDATE `bib_books` SET `alt_id_septnt`=4527 WHERE `book_id` = 47;
UPDATE `bib_books` SET `alt_id_septnt`=4528 WHERE `book_id` = 48;
UPDATE `bib_books` SET `alt_id_septnt`=4529 WHERE `book_id` = 49;
UPDATE `bib_books` SET `alt_id_septnt`=4530 WHERE `book_id` = 50;
UPDATE `bib_books` SET `alt_id_septnt`=4531 WHERE `book_id` = 51;
UPDATE `bib_books` SET `alt_id_septnt`=4532 WHERE `book_id` = 52;
UPDATE `bib_books` SET `alt_id_septnt`=4533 WHERE `book_id` = 53;
UPDATE `bib_books` SET `alt_id_septnt`=4534 WHERE `book_id` = 54;
UPDATE `bib_books` SET `alt_id_septnt`=4535 WHERE `book_id` = 55;
UPDATE `bib_books` SET `alt_id_septnt`=4536 WHERE `book_id` = 56;
UPDATE `bib_books` SET `alt_id_septnt`=4537 WHERE `book_id` = 57;
UPDATE `bib_books` SET `alt_id_septnt`=4538 WHERE `book_id` = 58;
UPDATE `bib_books` SET `alt_id_septnt`=4539 WHERE `book_id` = 59;
UPDATE `bib_books` SET `alt_id_septnt`=4540 WHERE `book_id` = 60;
UPDATE `bib_books` SET `alt_id_septnt`=4541 WHERE `book_id` = 61;
UPDATE `bib_books` SET `alt_id_septnt`=4542 WHERE `book_id` = 62;
UPDATE `bib_books` SET `alt_id_septnt`=4543 WHERE `book_id` = 63;
UPDATE `bib_books` SET `alt_id_septnt`=4544 WHERE `book_id` = 64;
UPDATE `bib_books` SET `alt_id_septnt`=4545 WHERE `book_id` = 65;
UPDATE `bib_books` SET `alt_id_septnt`=4546 WHERE `book_id` = 66;

ALTER TABLE `bib_verses` CHANGE `text` `text` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

INSERT INTO bib_verses
(translation_id, verse_id, book_id, chapter, verse, text)
SELECT 'septnt' AS translation_id, CONCAT(LPAD(b.book_id, 2, '0'), LPAD(j.chapter, 3, '0'), LPAD(j.verse, 3, '0')) AS verse_id, b.book_id, j.chapter, j.verse, j.text FROM `bib_jeru_septnt_temp` j INNER JOIN `bib_books` b ON b.`alt_id_septnt` = j.`book_id`;

