-- db8.7 — index the two columns publication linking searches on
--
-- @phase: pre
-- @kind: ddl
-- @idempotent: yes
-- @tables: sch_publications
-- @verify: SELECT c.COLUMN_NAME AS column_without_index FROM information_schema.COLUMNS c LEFT JOIN information_schema.STATISTICS s ON s.TABLE_SCHEMA=c.TABLE_SCHEMA AND s.TABLE_NAME=c.TABLE_NAME AND s.COLUMN_NAME=c.COLUMN_NAME AND s.SEQ_IN_INDEX=1 WHERE c.TABLE_SCHEMA=DATABASE() AND c.TABLE_NAME='sch_publications' AND c.COLUMN_NAME IN ('MainPublicationId','TranslatedFromPublicationId') AND s.INDEX_NAME IS NULL
--
-- `sch_publications` has exactly one index — the primary key — across 10,166 rows. Every
-- lookup by anything else is a full table scan, and the publication page does two of them
-- per request: `PublicationsTable::linkPublication()` asks for a record's sub-editions and
-- translations with
--
--     WHERE PublicationId = ? OR MainPublicationId = ? OR TranslatedFromPublicationId = ?
--
-- and the `searchPublications()` call that answers it links its own results, which issues
-- the same shape again with `IN` lists.
--
-- Measured in the capsule 2026-08-22, warm both sides, three samples each:
--
--     getPublication(1976)   54–71 ms wall / 50–65 ms SQL   ->   7.4–10.4 ms / 3.2–5.9 ms
--     /literature/en index   56.4 ms                        ->   35.7 ms
--
-- Both columns are highly selective: 198 rows have a MainPublicationId and 257 have a
-- TranslatedFromPublicationId, out of 10,166. That is why the index pays so well here and
-- why no index on `DataSource` is added alongside — 5,963 of 10,166 rows have one, so it
-- would not be used.
--
-- This is `@phase: pre` because nothing about it depends on the code: the release being
-- deployed benefits, and so does the one already running if the swap is rolled back.
--
-- ## The @verify line, and the one this file shipped with
--
-- `@verify` selects **what is still wrong** and must return nothing. The first version of
-- this line listed the table's indexes instead, so it returned three rows on success and
-- aborted the 2026-08-22 deploy after the migration had run correctly. Nothing was broken by
-- that — the indexes were created and recorded, `@phase: pre` means the release still
-- running benefits from them, and no swap had happened — but the deploy stopped, and the
-- error read like a failure rather than like a mistyped assertion.
--
-- The corrected line asks the opposite question: of the two columns this file indexes, which
-- still has no index whose first column it is? Zero rows once both exist. Verified against
-- the capsule by adding a third column that has no index, which the query then names.
--
-- The way to not repeat it is to rehearse through `tools/migrate.sh apply --env=capsule`
-- rather than piping the file into `mysql`, which is what happened here: the statements were
-- rehearsed and the header was not.
--
-- ## Applying this by hand
--
-- `CREATE INDEX IF NOT EXISTS` is MariaDB syntax (10.0.2+) and this server is 10.11. It
-- makes the migration re-runnable, which `@kind: ddl` requires because a DDL statement
-- cannot commit inside the ledger's transaction.

CREATE INDEX IF NOT EXISTS idx_main_publication ON sch_publications (MainPublicationId);
CREATE INDEX IF NOT EXISTS idx_translated_from ON sch_publications (TranslatedFromPublicationId);
