<?php
$headText = 'Edit greek root';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<p><?php echo $this->escapeHtml($this->entity['root']) . ' ';

$bibleSearchUrl = $this->url('bible/search');
foreach ($this->entity['formsAvailable'] as $form) {
    echo sprintf(
        '<a href="%s?search=%s@%s" target="_blank">%s</a> ',
        $bibleSearchUrl,
        urlencode($this->entity['root']),
        urlencode($form),
        $this->escapeHtml($form)
    );
}?></p>
<?php $form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->form()->closeTag();
