<?php use Patres\Model\EntityProblem;
/**
 * @var EntityProblem[] $problems
 */
$problems = $this->problems;
?>
<table class="table">
	<thead>
	<tr>
	<th><?php echo $this->translate('Entity');?></th>
	<th><?php echo $this->translate('Problem');?></th>
	</tr>
	</thead>
	<tbody>
<?php foreach ($problems as $entity) :?>
<tr>
	<td><?php echo $this->formatEntity($entity->getEntity(), $entity->getData(), ['editPencil' => true]);?></td>
	<td class="<?php echo $entity->getProblemTextClass()?>"><?php echo $this->escapeHtml($this->translate($entity->getProblemText()));?></td>
</tr>
<?php endforeach;?>
	</tbody>
</table>