<?php
echo '&nbsp;';
$this->moderateDenyForm->prepare();
echo $this->form()->openTag($this->moderateDenyForm);
echo $this->formButton($this->moderateDenyForm->get('deny'));
echo $this->formHidden($this->moderateDenyForm->get('suggestionId'));
echo $this->formHidden($this->moderateDenyForm->get('suggestionEntityId'));
echo $this->formHidden($this->moderateDenyForm->get('suggestionResponse'));
echo $this->form()->closeTag();
if ($this->isAllowed('route/admin/moderate')) :?>
     <a class="btn btn-default" href="<?php echo $this->url('admin/moderate')?>"><?php echo $this->translate("Cancel review");?></a>
<?php endif;
//put a script at the end to copy the suggestionResponse from the main form to the deny form
$mainFormName = $this->mainFormName;
$this->inlineScript()->captureStart();
echo <<<JS
    $(function () {
      $('#moderate_deny').submit(function() {
        $('#moderate_deny input[name="suggestionResponse"]').val(
          $('#$mainFormName textarea[name="suggestionResponse"').val()
        );
      });
    });
JS;
$this->inlineScript()->captureEnd();