<?php $headText = 'Fix Flag Problems';
$this->headTitle($headText);
?>
<h1><?php echo $this->translate('Flag fixer');?></h1>
<?php if ($this->changes && !empty($this->changes)):?>
<h2><?php if ($this->simulated) {
    echo $this->translate('Proposed Changes');
} else {
    echo $this->translate('Changed Rows:');
}?></h2>
<table class="table">
<thead><tr>
	<th><?php echo $this->translate('Person');?></th>
	<th><?php echo $this->translate('Field');?></th>
	<th><?php echo $this->translate('Old Value');?></th>
	<th><?php echo $this->translate('New Value');?></th>
</tr></thead>
<tbody>
<?php foreach ($this->changes as $row) : ?>
<tr>
	<td><?php echo $this->formatPersonName($row['personFirstName'], $row['personLastName'], null,
		$row['id'], null, $row['personDeathDate'], null, true);?></td>
	<td><?php echo $this->escapeHtml($row['column']);?></td>
	<td><?php echo $this->escapeHtml($row['oldValue']);?></td>
	<td><?php echo $this->escapeHtml($row['newValue']);?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>
<?php if ($this->simulated) :?>
<form method="post">
<button type="submit" class="btn btn-primary"><?php echo $this->translate('Confirm Changes');?></button>
</form>
<?php endif;?>
<?php else: //if changes is empty or null?>
<p><?php echo $this->translate('No flag problems found.');?></p>
<?php endif;?>