<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/selectize.bootstrap3.css');
$this->headScript()->appendFile($this->basePath() . "/js/_selectize.min.js");
$headText = 'Import Schoenstatt Father';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('admin/import-father'));
 $form->prepare();
 echo $this->form()->openTag($form);
$this->formSelect()->setTranslatorEnabled(false);
 echo $this->formRow($form->get('personId'));
$this->formSelect()->setTranslatorEnabled(true);
 echo $this->formRow($form->get('security'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
$jsScript = <<<JS
$("select[name='personId']").selectize({
    create: false,
    sortField: 'text'
});
JS;
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
?>
