<?php
$headText = 'Import Schoenstatt Father';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('admin/import-father'));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('personId'));
 echo $this->formRow($form->get('security'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>