<?php
$headText = 'Admin';
$this->headTitle($headText);
$this->badge()->setTranslatorEnabled(false);
foreach ($this->pages as $route => $text) :
    if ($this->isAllowed('route/' . $route)) :?>
        <p><a href="<?php echo $this->url($route);?>"><?php echo $this->translate($text);?></a> <?php
        if (isset($this->badges[$route])) {
            echo $this->badge($this->badges[$route]);
        }?>
        </p>
    <?php endif;
endforeach;?>
