<?php
$title = $this->translate("Book Search");
$this->headTitle($title);
$escaper = new \Zend\Escaper\Escaper('utf-8');
?>
<?php if (is_null($this->libraries) || count($this->libraries) == 0) :?>
<form class="form-search">
  <input type="text" class="input-medium search-query" size="50" name="search" value="<?php echo $this->query;?>">
  <button type="submit" class="btn"><?php echo $this->translate("Search");?></button>
</form>
<?php else : ?>
<div class="row">
<div class="span12 pagination-centered">
    <form class="form-search">
      <p><input type="text" class="input-large search-query" size="50" name="search" value="<?php echo $this->query;?>"></p>
      <p><button type="submit" class="btn">Search</button></p>
    </form>
    </div>
</div>
<div class="row">
<div class="span2 bs-docs-sidebar hidden-phone">
    <ul class="nav nav-list bs-docs-sidenav affix">
    <?php foreach ($this->libraries as $library => $books) : ?>
    <li><a href="#<?php echo $library;?>"><i class="icon-chevron-right"></i> <?php echo $library;?></a>
    <p><?php echo sprintf($this->translatePlural("%s result found.", " results found.", count($books)),count($books));?></p>
    </li>
    <?php endforeach;?>
    </ul>
</div>
<div class="span10">
<?php foreach ($this->libraries as $library => $books): ?>
<div id="<?php echo $output = $escaper->escapeHtmlAttr($library);?>">
    <h1><?php echo $library;?></h1>
    <table class="table">
    <tr>
    	<th>#</th>
        <th><?php echo $this->translate("Author");?></th>
        <th><?php echo $this->translate("Title");?></th>
        <th><?php echo $this->translate("Edition");?></th>
    </tr>
    <?php  foreach($books as $book) : ?>
        <tr>
        	<td><?php echo $book['call_number'];?></td>
        	<td><?php echo $book['author'];?></td>
        	<?php if (!is_null($book['file_type'])) :?>
        	<td><a href="<?php echo $book['url']; //echo $this->url('library/book', array('book_id' => $book['book_id']));?>" target="_blank">
        	<?php echo $book['title'];?></a>
        	<?php echo '('.$book['file_type'].', '.number_format($book['file_size']/1048576, 1, '.','').'MB)';?></td>
        	<?php else: ?>
        	<td><?php echo $book['title'];?></td>
        	<?php endif;?>
        	<td><?php echo $book['edition'];?></td>
        	<!-- <td><?php echo $book['updated_at'];?></td> -->
        <?php endforeach; ?>
        </tr>
    </table>
</div>
<?php endforeach; ?>
</div>
</div>
<?php endif;?>
