<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bible\Service\ConfigServiceFactory'     => __DIR__ . '/src/Service/ConfigServiceFactory.php',
    'Bible\Service\BibleTableServiceFactory' => __DIR__ . '/src/Service/BibleTableServiceFactory.php',
    'Bible\Service\FormatBibleVerseFactory'  => __DIR__ . '/src/Service/FormatBibleVerseFactory.php',
    'Bible\Controller\BibleController'       => __DIR__ . '/src/Bible/Controller/BibleController.php',
    'Bible\Model\BibleTable'                 => __DIR__ . '/src/Bible/Model/BibleTable.php',
    'Bible\View\Helper\FormatBibleVerse'     => __DIR__ . '/src/Bible/View/Helper/FormatBibleVerse.php',
    'Bible\Module'                           => __DIR__ . '/Module.php',
);
