<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JTranslation\Module'                                  => __DIR__ . '/Module.php',
    'JTranslation\Controller\JTranslationController'       => __DIR__ . '/src/JTranslation/Controller/JTranslationController.php',
    'JTranslation\Controller\Plugin\NowMessenger'          => __DIR__ . '/src/JTranslation/Controller/Plugin/NowMessenger.php',
    'JTranslation\Form\EditPhraseForm'                     => __DIR__ . '/src/JTranslation/Form/EditPhraseForm.php',
    'JTranslation\I18n\Translator\TranslatorEventListener' => __DIR__ . '/src/JTranslation/I18n/Translator/TranslatorEventListener.php',
    'JTranslation\Model\CountriesInfo'                     => __DIR__ . '/src/JTranslation/Model/CountriesInfo.php',
    'JTranslation\Model\TranslationsTable'                 => __DIR__ . '/src/JTranslation/Model/TranslationsTable.php',
    'JTranslation\Service\CacheFactory'                    => __DIR__ . '/src/JTranslation/Service/CacheFactory.php',
    'JTranslation\Service\ConfigServiceFactory'            => __DIR__ . '/src/JTranslation/Service/ConfigServiceFactory.php',
    'JTranslation\Service\CountriesFactory'                => __DIR__ . '/src/JTranslation/Service/CountriesFactory.php',
    'JTranslation\Service\EditPhraseFormFactory'           => __DIR__ . '/src/JTranslation/Service/EditPhraseFormFactory.php',
    'JTranslation\Service\TranslationsTableFactory'        => __DIR__ . '/src/JTranslation/Service/TranslationsTableFactory.php',
    'JTranslation\View\Helper\NowMessenger'                => __DIR__ . '/src/JTranslation/View/Helper/NowMessenger.php',
    'JTranslation\View\Helper\Service\NowMessengerFactory' => __DIR__ . '/src/JTranslation/View/Helper/Service/NowMessengerFactory.php',
);
