<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JTranslate\Module'                                  => __DIR__ . '/Module.php',
    'JTranslate\Controller\JTranslateController'       => __DIR__ . '/src/JTranslate/Controller/JTranslateController.php',
    'JTranslate\Controller\Plugin\NowMessenger'          => __DIR__ . '/src/JTranslate/Controller/Plugin/NowMessenger.php',
    'JTranslate\Form\EditPhraseForm'                     => __DIR__ . '/src/JTranslate/Form/EditPhraseForm.php',
    'JTranslate\I18n\Translator\TranslatorEventListener' => __DIR__ . '/src/JTranslate/I18n/Translator/TranslatorEventListener.php',
    'JTranslate\Model\CountriesInfo'                     => __DIR__ . '/src/JTranslate/Model/CountriesInfo.php',
    'JTranslate\Model\TranslationsTable'                 => __DIR__ . '/src/JTranslate/Model/TranslationsTable.php',
    'JTranslate\Service\CacheFactory'                    => __DIR__ . '/src/JTranslate/Service/CacheFactory.php',
    'JTranslate\Service\ConfigServiceFactory'            => __DIR__ . '/src/JTranslate/Service/ConfigServiceFactory.php',
    'JTranslate\Service\CountriesFactory'                => __DIR__ . '/src/JTranslate/Service/CountriesFactory.php',
    'JTranslate\Service\EditPhraseFormFactory'           => __DIR__ . '/src/JTranslate/Service/EditPhraseFormFactory.php',
    'JTranslate\Service\TranslationsTableFactory'        => __DIR__ . '/src/JTranslate/Service/TranslationsTableFactory.php',
    'JTranslate\View\Helper\NowMessenger'                => __DIR__ . '/src/JTranslate/View/Helper/NowMessenger.php',
    'JTranslate\View\Helper\Service\NowMessengerFactory' => __DIR__ . '/src/JTranslate/View/Helper/Service/NowMessengerFactory.php',
);
