<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JTranslate\Service\ConfigServiceFactory'                              => __DIR__ . '/src/JTranslate/Service/ConfigServiceFactory.php',
    'JTranslate\Service\TranslationsTableFactory'                          => __DIR__ . '/src/JTranslate/Service/TranslationsTableFactory.php',
    'JTranslate\Service\CountriesFactory'                                  => __DIR__ . '/src/JTranslate/Service/CountriesFactory.php',
    'JTranslate\Service\EditPhraseFormFactory'                             => __DIR__ . '/src/JTranslate/Service/EditPhraseFormFactory.php',
    'JTranslate\Service\CacheFactory'                                      => __DIR__ . '/src/JTranslate/Service/CacheFactory.php',
    'JTranslate\Controller\Plugin\NowMessenger'                            => __DIR__ . '/src/JTranslate/Controller/Plugin/NowMessenger.php',
    'JTranslate\Controller\JTranslateController'                           => __DIR__ . '/src/JTranslate/Controller/JTranslateController.php',
    'JTranslate\Model\CountriesInfo'                                       => __DIR__ . '/src/JTranslate/Model/CountriesInfo.php',
    'JTranslate\Model\TranslationsTable'                                   => __DIR__ . '/src/JTranslate/Model/TranslationsTable.php',
    'JTranslate\I18n\Translator\TranslatorEventListener'                   => __DIR__ . '/src/JTranslate/I18n/Translator/TranslatorEventListener.php',
    'JTranslate\Form\EditPhraseForm'                                       => __DIR__ . '/src/JTranslate/Form/EditPhraseForm.php',
    'JTranslate\View\Helper\Service\CountryNameFactory'                    => __DIR__ . '/src/JTranslate/View/Helper/Service/CountryNameFactory.php',
    'JTranslate\View\Helper\Service\NowMessengerFactory'                   => __DIR__ . '/src/JTranslate/View/Helper/Service/NowMessengerFactory.php',
    'JTranslate\View\Helper\Service\FlagFactory'                           => __DIR__ . '/src/JTranslate/View/Helper/Service/FlagFactory.php',
    'JTranslate\View\Helper\CountryName'                                   => __DIR__ . '/src/JTranslate/View/Helper/CountryName.php',
    'JTranslate\View\Helper\NowMessenger'                                  => __DIR__ . '/src/JTranslate/View/Helper/NowMessenger.php',
    'JTranslate\View\Helper\Flag'                                          => __DIR__ . '/src/JTranslate/View/Helper/Flag.php',
    'JTranslate\Module'                                                    => __DIR__ . '/Module.php',
);
