<?php
namespace Bible;

use Zend\Router\Http\Segment;
use Zend\Router\Http\Literal;
use BjyAuthorize\Guard\Route;

return [
//     'controllers' => [
//         'invokables' => [
//             'Bible\Controller\Bible' => 'Bible\Controller\BibleController',
//         ],
//     ],
    'bible' => [
        'special_countries' => [
            'CL',
            'AR',
            'PY'
        ],
    ],
    'service_manager' => [
        'factories' => [
            Model\BibleTable::class        => Service\BibleTableFactory::class,
            Model\DhTable::class        => Service\DhTableFactory::class,
            Provider\Rule\SpecialCountryRuleProvider::class => Service\SpecialCountryRuleProviderFactory::class,
        ],
    ],
    'view_helpers' => [
        'factories' => [
            'verseFromId' => Service\VerseFromIdFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'todays-reading-audio' => [
                'type'    => Literal::class,
                'options' => [
                    'route'    => '/todays-reading-audio',
                    'defaults' => [
                        'controller' => Controller\BibleController::class,
                        'action'     => 'todaysReadingAudio',
                    ],
                ],
            ],
            'tomorrows-reading-audio' => [
                'type'    => Literal::class,
                'options' => [
                    'route'    => '/tomorrows-reading-audio',
                    'defaults' => [
                        'controller' => Controller\BibleController::class,
                        'action'     => 'tommorrowsReadingAudio',
                    ],
                ],
            ],
            'sundays-reading-audio' => [
                'type'    => Literal::class,
                'options' => [
                    'route'    => '/sundays-reading-audio',
                    'defaults' => [
                        'controller' => Controller\BibleController::class,
                        'action'     => 'sundaysReadingAudio',
                    ],
                ],
            ],
            'dh' => [
                'type'    => Literal::class,
                'options' => [
                    'route'    => '/dh',
                    'defaults' => [
                        'controller' => Controller\DhController::class,
                        'action'     => 'index',
                    ],
                ],
                'may_terminate' => true,
                'child_routes' => [
                    'number' => [
                        'type'    => Segment::class,
                        'options' => [
                            'route'    => '/:dh_number',
                            'constraints' => [
                                'dh_number' => '[0-9]{1,4}',
                            ],
                            'defaults' => [
                                'action'     => 'show',
                            ],
                        ],
                    ],
                    'page' => [
                        'type'    => Segment::class,
                        'options' => [
                            'route'    => '/pg/:page_number',
                            'constraints' => [
                                'page_number' => '[0-9]{1,4}',
                            ],
                            'defaults' => [
                                'action'     => 'show',
                            ],
                        ],
                    ],
                    'import' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/import',
                            'defaults' => [
                                'action'     => 'import',
                            ],
                        ],
                    ],
                ],
            ],
            'bible' => [
                'type'    => Literal::class,
                'options' => [
                    'route'    => '/bible',
                    'defaults' => [
                        'controller' => Controller\BibleController::class,
                        'action'     => 'index',
                    ],
                ],
                'may_terminate' => true,
                'child_routes' => [
                    'text' => [
                        'type'    => Segment::class,
                        'may_terminate' => true,
                        'options' => [
                            'route'    => '/:book/:chapter',
                            'constraints' => [
                                /*
                                 * If the user comes to book that doesn't exist in their
                                 * selected translations, add the first translation that
                                 * has that book.
                                 */
                                'book'        => '[A-Za-z0-9]{1,15}',
                                'chapter'     => '[0-9]{1,3}'
                            ],
                            'defaults' => [
                                'action'     => 'text',
                            ],
                        ],
                    ],
                    'migrate' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/migrate',
                            'defaults' => [
                                'action'     => 'migrate',
                            ],
                        ],
                    ],
                    'create-greek-reference' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/create-greek-reference',
                            'defaults' => [
                                'action'     => 'createGreekReference',
                            ],
                        ],
                    ],
                    'normalize-greek' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/normalize-greek',
                            'defaults' => [
                                'action'     => 'normalizeGreek',
                            ],
                        ],
                    ],
                    'search' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/search',
                            'defaults' => [
                                'action'     => 'search',
                            ],
                        ],
                    ],
                    'greek' => [
                        'type'    => Literal::class,
                        'options' => [
                            'route'    => '/greek',
                            'defaults' => [
                                'controller' => Controller\GreekRootController::class,
                                'action'     => 'index',
                            ],
                        ],
                        'may_terminate' => true,
                        'child_routes' => [
                            'root' => [
                                'type'    => Segment::class,
                                'options' => [
                                    'route'    => '/:root_id',
                                    'constraints' => [
                                        'root_id'        => '[0-9]{1,4}',
                                    ],
                                    'defaults' => [
                                        'action'     => 'show',
                                    ],
                                ],
                                'child_routes' => [
                                    'edit' => [
                                        'type'    => Literal::class,
                                        'options' => [
                                            'route'    => '/edit',
                                            'defaults' => [
                                                'action'     => 'edit',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
//                     'bible-import' => [
//                         'type'    => Segment::class,
//                         'options' => [
//                             'route'    => '/import/:translation',
//                             'constraints' => [
//                                 'translation' => '[a-zA-Z]{3,3}',
//                             ],
//                             'defaults' => [
//                                 'action'     => 'import',
//                             ],
//                         ],
//                     ],
                ],
            ],
        ],
    ],
    'sion_model' => [
        'entities' => [
            'bible-verse' => [
                'name'                                      => 'bible-verse',
                'table_name'                                => 'bib_verses',
                'table_key'                                 => 'id',
                'entity_key_field'                          => 'verseId',
                'sion_model_class'                          => Model\BibleTable::class,
                'sion_controllers'                          => [Controller\BibleController::class],//BorrowersController::class],
                'controller_services'                       => [

                ],
                'row_processor_function'                    => 'processVerseRow',
//                 'get_object_function'                       => 'getVerses',
//                 'get_objects_function'                      => 'getUnlinkedTexts',
                //                 'format_view_helper'                        => 'formatEvent',
                'required_columns_for_creation'             => [
//                     'title',
//                     'kind',
//                     'inLanguage',
                ],
                'name_field'                                => 'texts',
                'name_field_is_translateable'               => false,
                //                 'country_field'                             => 'country',
                'text_columns'                              => [],
//                 'many_to_one_update_columns'                => [
//                     'email'    => 'contactInfo',
//                     'cell'    => 'contactInfo',
//                 ],
                'report_changes'                            => false,
//                 'index_route'                               => 'events',
//                 'index_template'                            => 'project/events/index',
                'default_route_key'                         => 'verse_id',
//                 'show_a  ction_template'                      => 'project/events/show',
//                 'show_route'                                => 'texts/text',
//                 'show_route_key'                            => 'text_id',
//                 'show_route_key_field'                      => 'textId',
//                 'edit_action_form'                          => Form\BlogForm::class,
//                 'edit_action_template'                      => 'project/events/edit',
//                 'edit_route'                                => 'blog/blog-post/edit',
//                 'edit_route_key'                            => 'text_id',
//                 'edit_route_key_field'                      => 'textId',
//                 'create_action_form'                        => Form\BlogForm::class,
//                 'create_action_valid_data_handler'          => 'blog/blog-post/edit',
//                 'create_action_redirect_route'              => 'blog/blog-post',
//                 'create_action_redirect_route_key'          => 'text_id',
//                 'create_action_redirect_route_key_field'    => 'textId',
//                 'create_action_template'                    => 'project/events/create',
//                 'touch_default_field'                       => 'eventId',
//                 'touch_route_key'                           => 'event_id',
//                 'touch_field_route_key'                     => 'event_id',
//                 'touch_json_route'                          => 'events/event/touch',
//                 'touch_json_route_key'                      => 'event_id',
//                 'database_bound_data_preprocessor'          => 'preprocessText',
//                 'database_bound_data_postprocessor'         => 'postprocessEvent',
//                 'moderate_route'                            => 'events/event/moderate',
//                 'moderate_route_entity_key'                 => 'event_id',
//                 'suggest_form'                              => 'Project\Form\SuggestEventForm',
//                 'enable_delete_action'                      => true,
//                 'delete_action_acl_resource'                => 'event_:id',
//                 'delete_action_acl_permission'              => 'delete',
//                 'delete_action_redirect_route'              => 'blog',
                'update_columns'                            => [
                    'id' => 'id',
                    'translation' => 'translation_id',
                    'verseId' => 'verse_id',
                    'book' => 'book_id',
                    'chapter' => 'chapter',
                    'verse' => 'verse',
                    'text' => 'text',
                ],
            ],
            'bible-book' => [
                'name'                                      => 'bible-book',
                'table_name'                                => 'bib_books',
                'table_key'                                 => 'book_id',
                'entity_key_field'                          => 'bookId',
                'sion_model_class'                          => Model\BibleTable::class,
//                 'sion_controllers'                          => [Controller\BibleController::class],//BorrowersController::class],
                'controller_services'                       => [

                ],
//                 'get_object_function'                       => 'getVerses',
//                 'get_objects_function'                      => 'getUnlinkedTexts',
                'row_processor_function'                    => 'processBookRow',
//                 'format_view_helper'                        => 'formatEvent',
                'required_columns_for_creation'             => [
//                     'title',
//                     'kind',
//                     'inLanguage',
                ],
                'name_field'                                => 'name_en',
                'name_field_is_translateable'               => false,
//                 'country_field'                             => 'country',
                'text_columns'                              => [],
//                 'many_to_one_update_columns'                => [
//                     'email'    => 'contactInfo',
//                     'cell'    => 'contactInfo',
//                 ],
                'report_changes'                            => true,
//                 'index_route'                               => 'events',
//                 'index_template'                            => 'project/events/index',
                'default_route_key'                         => 'verse_id',
//                 'show_a  ction_template'                      => 'project/events/show',
//                 'show_route'                                => 'texts/text',
//                 'show_route_key'                            => 'text_id',
//                 'show_route_key_field'                      => 'textId',
//                 'edit_action_form'                          => Form\BlogForm::class,
//                 'edit_action_template'                      => 'project/events/edit',
//                 'edit_route'                                => 'blog/blog-post/edit',
//                 'edit_route_key'                            => 'text_id',
//                 'edit_route_key_field'                      => 'textId',
//                 'create_action_form'                        => Form\BlogForm::class,
//                 'create_action_valid_data_handler'          => 'blog/blog-post/edit',
//                 'create_action_redirect_route'              => 'blog/blog-post',
//                 'create_action_redirect_route_key'          => 'text_id',
//                 'create_action_redirect_route_key_field'    => 'textId',
//                 'create_action_template'                    => 'project/events/create',
//                 'touch_default_field'                       => 'eventId',
//                 'touch_route_key'                           => 'event_id',
//                 'touch_field_route_key'                     => 'event_id',
//                 'touch_json_route'                          => 'events/event/touch',
//                 'touch_json_route_key'                      => 'event_id',
//                 'database_bound_data_preprocessor'          => 'preprocessText',
//                 'database_bound_data_postprocessor'         => 'postprocessEvent',
//                 'moderate_route'                            => 'events/event/moderate',
//                 'moderate_route_entity_key'                 => 'event_id',
//                 'suggest_form'                              => 'Project\Form\SuggestEventForm',
//                 'enable_delete_action'                      => true,
//                 'delete_action_acl_resource'                => 'event_:id',
//                 'delete_action_acl_permission'              => 'delete',
//                 'delete_action_redirect_route'              => 'blog',
                'update_columns'                            => [
                    'bookId' => 'book_id',
                    'name' => 'name_en',
                    'nameEs' => 'name_es',
                    'nameDe' => 'name_de',
                    'namePt' => 'name_pt',
                    'nameFr' => 'name_fr',
                    'orderJerusalemEn' => 'order_jerusalem_en',
                    'orderJerusalemEs' => 'order_jerusalem_es',
                    'abbreviationJerusalemEn' => 'abbreviation_jerusalem_en',
                    'abbreviationJerusalemEs' => 'abbreviation_jerusalem_es',
                    'isNewTestament' => 'is_new_testament',
                    'genreId' => 'genre_id',
                    'isCanonical' => 'is_canonical',
                    'chapterCount' => 'chapter_count',
                    'oldBookId' => 'old_book_id',
                ],
            ],
            'greek-root' => [
                'name'                                      => 'greek-root',
                'table_name'                                => 'bib_greek_root_words',
                'table_key'                                 => 'root_id',
                'entity_key_field'                          => 'rootId',
                'sion_model_class'                          => Model\BibleTable::class,
                'sion_controllers'                          => [Controller\GreekRootController::class],//BorrowersController::class],
                'controller_services'                       => [

                ],
//                 'get_object_function'                       => 'getVerses',
//                 'get_objects_function'                      => 'getUnlinkedTexts',
                'row_processor_function'                    => 'processGreekRootRow',
//                 'format_view_helper'                        => 'formatEvent',
                'required_columns_for_creation'             => [
                    'root',
                ],
                'name_field'                                => 'root',
                'name_field_is_translateable'               => false,
//                 'country_field'                             => 'country',
                'text_columns'                              => [],
//                 'many_to_one_update_columns'                => [
//                     'email'    => 'contactInfo',
//                     'cell'    => 'contactInfo',
//                 ],
                'report_changes'                            => true,
                'index_route'                               => 'bible/greek',
//                 'index_template'                            => 'project/events/index',
                'default_route_key'                         => 'root_id',
//                 'show_action_template'                      => 'project/events/show',
//                 'show_route'                                => 'texts/text',
//                 'show_route_key'                            => 'text_id',
//                 'show_route_key_field'                      => 'textId',
                'edit_action_form'                          => Form\GreekRootForm::class,
//                 'edit_action_template'                      => 'project/events/edit',
                'edit_route'                                => 'bible/greek/root/edit',
                'edit_route_key'                            => 'root_id',
                'edit_route_key_field'                      => 'rootId',
//                 'create_action_form'                        => Form\GreekRootForm::class,
//                 'create_action_valid_data_handler'          => 'blog/blog-post/edit',
//                 'create_action_redirect_route'              => 'bible/greek',
//                 'create_action_redirect_route_key'          => 'text_id',
//                 'create_action_redirect_route_key_field'    => 'textId',
//                 'create_action_template'                    => 'project/events/create',
//                 'touch_default_field'                       => 'eventId',
//                 'touch_route_key'                           => 'event_id',
//                 'touch_field_route_key'                     => 'event_id',
//                 'touch_json_route'                          => 'events/event/touch',
//                 'touch_json_route_key'                      => 'event_id',
//                 'database_bound_data_preprocessor'          => 'preprocessText',
//                 'database_bound_data_postprocessor'         => 'postprocessEvent',
//                 'moderate_route'                            => 'events/event/moderate',
//                 'moderate_route_entity_key'                 => 'event_id',
//                 'suggest_form'                              => 'Project\Form\SuggestEventForm',
//                 'enable_delete_action'                      => true,
//                 'delete_action_acl_resource'                => 'event_:id',
//                 'delete_action_acl_permission'              => 'delete',
//                 'delete_action_redirect_route'              => 'blog',
                'update_columns'                            => ['rootId' => 'root_id',
                    'root' => 'root',
                    'partOfSpeech' => 'part_of_speech',
                    'firstVerseOccurrence' => 'first_verse_occurrence',
                    'occurrenceCount' => 'occurrence_count',
                    'gender' => 'gender',
                    'paradigmPart1' => 'paradigm_part_1',
                    'paradigmPart2' => 'paradigm_part_2',
                    'paradigmPart3' => 'paradigm_part_3',
                    'paradigmPart4' => 'paradigm_part_4',
                    'formsAvailable' => 'forms_available',
                    'dictionaryEntryId' => 'dictionary_entry_id',
                    'johnOccurrenceCount' => 'john_occurrence_count',
                    'johnFirstVerseOccurrence' => 'john_first_verse_occurrence',
                ],
            ],
            'bible-book-abbreviation' => [
                'name'                                      => 'bible-book-abbreviation',
                'table_name'                                => 'bib_book_abbreviations',
                'table_key'                                 => 'id',
                'entity_key_field'                          => 'abbreviationId',
                'sion_model_class'                          => Model\BibleTable::class,
//                 'sion_controllers'                          => [Controller\BibleController::class],//BorrowersController::class],
                'controller_services'                       => [

                ],
//                 'get_object_function'                       => 'getVerses',
//                 'get_objects_function'                      => 'getUnlinkedTexts',
                'row_processor_function'                    => 'processBookAbbreviationRow',
//                 'format_view_helper'                        => 'formatEvent',
                'required_columns_for_creation'             => [
//                     'title',
//                     'kind',
//                     'inLanguage',
                ],
                'name_field'                                => 'abbreviation',
                'name_field_is_translateable'               => false,
//                 'country_field'                             => 'country',
                'text_columns'                              => [],
//                 'many_to_one_update_columns'                => [
//                     'email'    => 'contactInfo',
//                     'cell'    => 'contactInfo',
//                 ],
                'report_changes'                            => true,
//                 'index_route'                               => 'events',
//                 'index_template'                            => 'project/events/index',
                'default_route_key'                         => 'verse_id',
//                 'show_a  ction_template'                      => 'project/events/show',
//                 'show_route'                                => 'texts/text',
//                 'show_route_key'                            => 'text_id',
//                 'show_route_key_field'                      => 'textId',
//                 'edit_action_form'                          => Form\BlogForm::class,
//                 'edit_action_template'                      => 'project/events/edit',
//                 'edit_route'                                => 'blog/blog-post/edit',
//                 'edit_route_key'                            => 'text_id',
//                 'edit_route_key_field'                      => 'textId',
//                 'create_action_form'                        => Form\BlogForm::class,
//                 'create_action_valid_data_handler'          => 'blog/blog-post/edit',
//                 'create_action_redirect_route'              => 'blog/blog-post',
//                 'create_action_redirect_route_key'          => 'text_id',
//                 'create_action_redirect_route_key_field'    => 'textId',
//                 'create_action_template'                    => 'project/events/create',
//                 'touch_default_field'                       => 'eventId',
//                 'touch_route_key'                           => 'event_id',
//                 'touch_field_route_key'                     => 'event_id',
//                 'touch_json_route'                          => 'events/event/touch',
//                 'touch_json_route_key'                      => 'event_id',
//                 'database_bound_data_preprocessor'          => 'preprocessText',
//                 'database_bound_data_postprocessor'         => 'postprocessEvent',
//                 'moderate_route'                            => 'events/event/moderate',
//                 'moderate_route_entity_key'                 => 'event_id',
//                 'suggest_form'                              => 'Project\Form\SuggestEventForm',
//                 'enable_delete_action'                      => true,
//                 'delete_action_acl_resource'                => 'event_:id',
//                 'delete_action_acl_permission'              => 'delete',
//                 'delete_action_redirect_route'              => 'blog',
                'update_columns'                            => [
                    'abbreviationId' => 'id',
                    'abbreviation' => 'abbreviation',
                    'bookId' => 'book_id',
                    'language' => 'language',
                    'isPreferred' => 'is_preferred',
                ],
            ],
            'dh-page' => [
                'name'                                      => 'dh-page',
                'table_name'                                => 'bib_dh_page',
                'table_key'                                 => 'PageNumber',
                'entity_key_field'                          => 'pageNumber',
                'sion_model_class'                          => Model\DhTable::class,
                'sion_controllers'                          => [Controller\DhController::class],//BorrowersController::class],
                'controller_services'                       => [

                ],
//                 'get_object_function'                       => 'getVerses',
//                 'get_objects_function'                      => 'getUnlinkedTexts',
                'row_processor_function'                    => 'processDhRow',
//                 'format_view_helper'                        => 'formatEvent',
                'required_columns_for_creation'             => [
                    'pageNumber',
                    'fileName',
                ],
                'name_field'                                => 'pageNumber',
                'name_field_is_translateable'               => false,
                'report_changes'                            => false,
                'index_route'                               => 'dh',
//                 'index_template'                            => 'project/events/index',
                'default_route_key'                         => 'page_number',
//                 'show_action_template'                      => 'project/events/show',
                'show_route'                                => 'dh',
                'show_route_key'                            => 'page_number',
                'show_route_key_field'                      => 'pageNumber',
//                 'edit_action_form'                          => Form\BlogForm::class,
//                 'edit_action_template'                      => 'project/events/edit',
//                 'edit_route'                                => 'blog/blog-post/edit',
//                 'edit_route_key'                            => 'text_id',
//                 'edit_route_key_field'                      => 'textId',
//                 'create_action_form'                        => Form\BlogForm::class,
//                 'create_action_valid_data_handler'          => 'blog/blog-post/edit',
//                 'create_action_redirect_route'              => 'blog/blog-post',
//                 'create_action_redirect_route_key'          => 'text_id',
//                 'create_action_redirect_route_key_field'    => 'textId',
//                 'create_action_template'                    => 'project/events/create',
//                 'touch_default_field'                       => 'eventId',
//                 'touch_route_key'                           => 'event_id',
//                 'touch_field_route_key'                     => 'event_id',
//                 'touch_json_route'                          => 'events/event/touch',
//                 'touch_json_route_key'                      => 'event_id',
//                 'database_bound_data_preprocessor'          => 'preprocessText',
//                 'database_bound_data_postprocessor'         => 'postprocessEvent',
//                 'moderate_route'                            => 'events/event/moderate',
//                 'moderate_route_entity_key'                 => 'event_id',
//                 'suggest_form'                              => 'Project\Form\SuggestEventForm',
//                 'enable_delete_action'                      => true,
//                 'delete_action_acl_resource'                => 'event_:id',
//                 'delete_action_acl_permission'              => 'delete',
//                 'delete_action_redirect_route'              => 'blog',
                'update_columns'                            => [
                    'pageNumber' => 'PageNumber',
                    'fileName' => 'FileName',
                    'headerDhNumber' => 'ReferenceNumber',
                    'startDhNumber' => 'StartDhNumber',
                    'endDhNumber' => 'EndDhNumber',
                    'headerText' => 'HeaderText',
                    'widthInPixels' => 'WidthInPixels',
                    'heightInPixels' => 'HeightInPixels',
                    'fullTextFileName' => 'FullTextFileName',
                    'fullText' => 'FullTextOCR',
                ],
            ],
        ],
    ],
    'bjyauthorize' => [
        'rule_providers' => [
            Provider\Rule\SpecialCountryRuleProvider::class => [],
        ],
        'guards' => [
            Route::class => [
                ['route' => 'bible', 'roles' => ['bib_user']],
//                 ['route' => 'bible/translation', 'roles' => ['bib_user']],
                ['route' => 'bible/text', 'roles' => ['bib_user']],
                ['route' => 'bible/search', 'roles' => ['bib_user']],
                ['route' => 'bible/create-greek-reference', 'roles' => ['bib_administrator']],
                ['route' => 'bible/normalize-greek', 'roles' => ['bib_administrator']],
//                 ['route' => 'bible/bnt', 'roles' => ['bib_user']],
//                 ['route' => 'bible/bibleimport', 'roles' => ['bib_administrator']],
                ['route' => 'bible/migrate', 'roles' => ['bib_administrator']],
                ['route' => 'bible/greek', 'roles' => ['bib_user']],
                ['route' => 'bible/greek/root/edit', 'roles' => ['bib_administrator']],
                ['route' => 'dh', 'roles' => ['bib_administrator']],
                ['route' => 'dh/import', 'roles' => ['bib_administrator']],
                ['route' => 'dh/page', 'roles' => ['bib_user']],
                ['route' => 'dh/number', 'roles' => ['bib_user']],
                ['route' => 'todays-reading-audio', 'roles' => ['guest', 'user']],
                ['route' => 'tomorrows-reading-audio', 'roles' => ['guest', 'user']],
                ['route' => 'sundays-reading-audio', 'roles' => ['guest', 'user']],
            ],
        ],
    ],

    'view_manager' => [
        'template_map' => include __DIR__ . '/template_map.config.php',
        'template_path_stack' => [
            __NAMESPACE__ => __DIR__ . '/../view',
        ],
    ],
];
