<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-selectize-markdown.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . "/gen-selectize-markdown-$lang.js");
$form = $this->form;
echo $this->formRow($form->get('libraryId'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('abbreviation'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('callNumberRegex'));
echo $this->formRow($form->get('callNumberHelpText'));
echo $this->formRow($form->get('callNumberExplanation'));
echo $this->formRow($form->get('mainShowDisplay'));
echo $this->formRow($form->get('sortTextFormat'));
echo $this->formRow($form->get('labelLine1'));
echo $this->formRow($form->get('labelLine2'));
echo $this->formRow($form->get('labelLine3'));
echo $this->formRow($form->get('defaultCheckoutTimePeriodInDays'));
echo $this->formRow($form->get('requireCallNumbers'));
echo $this->formRow($form->get('enforceCallNumberRegex'));
echo $this->formRow($form->get('isActive'));
echo $this->formRow($form->get('adminNotes'));
echo $this->formRow($form->get('security'));
echo $this->formRow($form->get('submit'));
?>
