<?php use Zend\Math\Rand;
echo $this->doctype(); ?>

<html lang="<?php echo Locale::getPrimaryLanguage(Locale::getDefault()); ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Schoenstatt Link'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	       ->prependStylesheet($this->basePath() . '/'. $this->asset('css/basic.css'));
//                         ->prependStylesheet($this->basePath('css/style.css'))
//                         ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//                         ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/'. $this->asset('js/basic.js'))
//             ->prependFile($this->basePath('js/bootstrap.min.js'))
//             ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse"
                    	aria-expanded="false" aria-controls=".navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Schoenstatt Link') ?></a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <?php
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav')
                        ->render();
                    ?>
    				<ul class="nav navbar-nav pull-right">
    					<?php $username = $this->zfcUserDisplayName();
    					if (0 != strcmp($this->routeName(), 'assignments/search') &&
    					    0 != strcmp($this->routeName(), 'home')
    					    && $username) :?>
    					<li class="hidden-sm">
    						<form class="navbar-form"
    							action="<?php echo $this->url('assignments/search') ?>" method="get"
    							role="search">
    							<div class="input-group">
    								<input type="text" class="form-control" name="search"
    									placeholder="<?php echo $this->translate("Search", 'Application');?>">
        							<span class="input-group-btn">
        								<button class="btn btn-info" type="submit">
        									<i class="glyphicon glyphicon-search"></i>
        								</button>
        							</span>
    							</div>
    						</form>
    					</li>
    					<?php endif;?>
    					<?php if ($username) : ?>
        					<li><a href="<?php echo $this->url('zfcuser/logout');?>"><?php
        					echo $this->translate("Logout", 'Application');?></a></li>
    					<?php else:?>
        					<li><a href="<?php echo $this->url('zfcuser/login');?>"><?php
        					echo $this->translate("Login", 'Application');?></a></li>
    					<?php endif;?>
    				</ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container" role="main">
        	<div class="row">
            	<div id="langs" class="pull-right" data-toggle="tooltip" data-placement="bottom"
            	data-container="body" data-original-title="<?php echo $this->translate("Current:", 'Application').
    					' '.Locale::getDefault();?>">
    				<?php $en = ['us', 'gb'];
    				      $es = ['ar', 'es', 'cl', 'mx'];
    				      $de = ['de', 'ch'];
    				      $pt = ['pt', 'br'];?>
                	<a href="?lang=en_US"><span class="flag-icon flag-icon-<?php echo $en[Rand::getInteger(0, 1)]; ?>"></span></a>
                	<a href="?lang=es_ES"><span class="flag-icon flag-icon-<?php echo $es[Rand::getInteger(0, 3)]; ?>"></span></a>
                	<a href="?lang=de_DE"><span class="flag-icon flag-icon-<?php echo $de[Rand::getInteger(0, 1)]; ?>"></span></a>
                	<a href="?lang=pt_BR"><span class="flag-icon flag-icon-<?php echo $pt[Rand::getInteger(0, 1)]; ?>"></span></a>
            	</div>
    		</div>
            <?php
    		$flash = $this->flashMessenger();
    		$flash->setMessageOpenFormat('<div%s>
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
             &times;
         </button>
         ')
         ->setMessageSeparatorString('</br>')
         ->setMessageCloseString('</div>');

         echo $flash->render('error',   ['alert', 'alert-dismissable', 'alert-danger']);
         echo $flash->render('info',    ['alert', 'alert-dismissable', 'alert-info']);
         echo $flash->render('default', ['alert', 'alert-dismissable', 'alert-warning']);
         echo $flash->render('success', ['alert', 'alert-dismissable', 'alert-success']);
         echo $this->nowMessenger();

         echo $this->content; ?>
            <hr>
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
})
JS;
 $this->inlineScript()->captureEnd();

 echo $this->inlineScript(); ?>
    </body>
</html>
