<?php use Zend\Math\Rand;
use Zend\Uri\Uri;
echo $this->doctype(); ?>
<html lang="<?php echo Locale::getPrimaryLanguage(Locale::getDefault()); ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Schoenstatt Link'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php //make a link to the canonical (en) page for search engines and alternative links to other languages
        /** @var Uri $canonicalUrl */
        $languages = ['en' => 'en_US', 'es' => 'es_ES', 'de' => 'de_DE', 'pt' => 'pt_BR'];
        $currentLanguage = Locale::getPrimaryLanguage(Locale::getDefault());
        $requestUri = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri();
        foreach ($languages as $languageId => $localeId) {
            $canonicalUrl = $this->localeUrl($localeId);
            $queryParams = $canonicalUrl->getQueryAsArray();
            if (array_key_exists('lang', $queryParams)) {
                unset($queryParams['lang']);
                $canonicalUrl->setQuery($queryParams);
            }
            $canonicalUrl->setScheme($requestUri->getScheme())
            ->setHost($requestUri->getHost())
            ->normalize();
            if ($languageId == 'en') {
                $this->headLink([
                    'href' => $canonicalUrl->toString(),
                    'rel' => 'canonical',
                ], 'PREPEND');
            }
            if ($languageId !== $currentLanguage) {
                $this->headLink([
                    'href' => $canonicalUrl->toString(),
                    'rel' => 'alternate',
                    'hreflang' => $languageId,
                ], 'PREPEND');
            }
        }

        echo $this->headLink()
	       ->prependStylesheet($this->basePath() . '/css/gen-basic.css');
//                         ->prependStylesheet($this->basePath('css/style.css'))
//                         ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//                         ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    	<!-- ****** faviconit.com favicons ****** -->
    	<link rel="shortcut icon" href="/favicon.ico">
    	<link rel="icon" sizes="16x16 32x32 64x64" href="/favicon.ico">
    	<link rel="icon" type="image/png" sizes="196x196" href="/favicon-192.png">
    	<link rel="icon" type="image/png" sizes="160x160" href="/favicon-160.png">
    	<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96.png">
    	<link rel="icon" type="image/png" sizes="64x64" href="/favicon-64.png">
    	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
    	<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png">
    	<link rel="apple-touch-icon" href="/favicon-57.png">
    	<link rel="apple-touch-icon" sizes="114x114" href="/favicon-114.png">
    	<link rel="apple-touch-icon" sizes="72x72" href="/favicon-72.png">
    	<link rel="apple-touch-icon" sizes="144x144" href="/favicon-144.png">
    	<link rel="apple-touch-icon" sizes="60x60" href="/favicon-60.png">
    	<link rel="apple-touch-icon" sizes="120x120" href="/favicon-120.png">
    	<link rel="apple-touch-icon" sizes="76x76" href="/favicon-76.png">
    	<link rel="apple-touch-icon" sizes="152x152" href="/favicon-152.png">
    	<link rel="apple-touch-icon" sizes="180x180" href="/favicon-180.png">
    	<meta name="msapplication-TileColor" content="#FFFFFF">
    	<meta name="msapplication-TileImage" content="/favicon-144.png">
    	<meta name="msapplication-config" content="/browserconfig.xml">
    	<!-- ****** faviconit.com favicons ****** -->
        <!-- Le styles -->

        <!-- Scripts -->
        <?php
        echo $this->headScript()
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/gen-basic.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse"
                    	aria-expanded="false" aria-controls=".navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('welcome') ?>"><?php echo $this->translate('Schoenstatt Link') ?></a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <?php
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav')
                        ->render();
                    $username = $this->zfcUserDisplayName();
                    if (!$username) :?>
                    <form class="navbar-form navbar-right" method="post" action="<?php echo $this->url('zfcuser/login');?>">
                        <div class="form-group">
                          <input name="identity" placeholder="<?php echo $this->translate('Username');?>" class="form-control" type="text">
                        </div>
                        <div class="form-group">
                          <input name="credential" placeholder="<?php echo $this->translate('Password');?>" class="form-control" type="password">
                        </div>
                        <input name="remember_me" value="1" type="hidden">
                        <button type="submit" class="btn btn-success"><?php echo $this->translate('Sign in');?></button>
                    </form>
                    <?php else:?>
    				<ul class="nav navbar-nav pull-right">
    					<?php
    					$routeName = $this->routeName();
    					if (0 != strcmp($routeName, 'assignments/search') &&
					        0 != strcmp($routeName, 'assignments') &&
					        0 != strcmp($routeName, 'publications/search') &&
					        0 != strcmp($routeName, 'publications') &&
					        0 != strcmp($routeName, 'schoenstatt') &&
			                0 != strcmp($routeName, 'welcome')
				        ) :
				            $shouldAddSearch = false;
					        if (false === strpos($routeName, 'publication') &&
				                $this->isAllowed('route/assignments/search')
			                ) {
					            $searchUrl = $this->url('assignments/search');
					            $placeholder = 'Search contacts';
					            $shouldAddSearch = true;
			                } elseif ($this->isAllowed('route/publications/search')) {
					            $searchUrl = $this->url('publications/search');
					            $placeholder = 'Search publications';
					            $shouldAddSearch = true;
    					    }
					       if ($shouldAddSearch):?>
        					<li class="">
        						<form class="navbar-form"
        							action="<?php echo $searchUrl; ?>" method="get"
        							role="search">
        							<div class="input-group">
        								<input type="text" class="form-control" name="search"
        									placeholder="<?php echo $this->translate($placeholder, 'Application');?>">
            							<span class="input-group-btn">
            								<button class="btn btn-info" type="submit">
            									<i class="glyphicon glyphicon-search"></i>
            								</button>
            							</span>
        							</div>
        						</form>
        					</li>
    						<?php endif;
    					endif;?>
    					<li><a href="<?php echo $this->url('zfcuser/logout');?>"><?php
    					echo $this->translate("Logout", 'Application');?></a></li>
    				</ul>
    			<?php endif;?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container" role="main">
        	<div class="row">
            	<div id="langs" class="pull-right" data-toggle="tooltip" data-placement="bottom"
            	data-container="body" data-original-title="<?php echo $this->translate("Current:", 'Application').
    					' '.Locale::getDefault();?>">
    				<?php $en = ['us', 'gb'];
    				      $es = ['ar', 'es', 'cl', 'mx'];
    				      $de = ['de', 'ch'];
    				      $pt = ['pt', 'br'];?>
                	<a href="<?php echo $this->localeUrl('en_US');?>"><span class="flag-icon flag-icon-<?php echo $en[Rand::getInteger(0, 1)]; ?>"></span></a>
                	<a href="<?php echo $this->localeUrl('es_ES');?>"><span class="flag-icon flag-icon-<?php echo $es[Rand::getInteger(0, 3)]; ?>"></span></a>
                	<a href="<?php echo $this->localeUrl('de_DE');?>"><span class="flag-icon flag-icon-<?php echo $de[Rand::getInteger(0, 1)]; ?>"></span></a>
                	<a href="<?php echo $this->localeUrl('pt_BR');?>"><span class="flag-icon flag-icon-<?php echo $pt[Rand::getInteger(0, 1)]; ?>"></span></a>
            	</div>
    		</div>
            <?php
    		$flash = $this->flashMessenger();
    		$flash->setMessageOpenFormat('<div%s>
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
             &times;
         </button>
         ')
         ->setMessageSeparatorString('</br>')
         ->setMessageCloseString('</div>');

         echo $flash->render('error',   ['alert', 'alert-dismissable', 'alert-danger']);
         echo $flash->render('info',    ['alert', 'alert-dismissable', 'alert-info']);
         echo $flash->render('default', ['alert', 'alert-dismissable', 'alert-warning']);
         echo $flash->render('success', ['alert', 'alert-dismissable', 'alert-success']);
         echo $this->nowMessenger();

         echo $this->content; ?>
        	<div class="footer">
        		<hr>
                <p class="text-center">© Schoenstatt Data Initiative 2017 <?php
                if ($this->isAllowed('welcome')):?>
                	| <a href="<?php echo $this->url('welcome')?>"><?php echo $this->translate('About');?></a>
            	<?php endif;?></p>
        	</div>
        </div> <!-- /container -->
<?php
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
})
JS;
 $this->inlineScript()->captureEnd();

 echo $this->inlineScript(); ?>
    </body>
</html>
