<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = 'Create new dictionary entry';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php /** @var \Books\Form\DictionaryEntryForm $form */
$form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
$form->get('locale')->setAttribute('disabled', false);
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', $this->vars);
 echo $this->form()->closeTag();
?>