<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = 'Edit dictionary entry';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url(null, [], [], true));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', $this->vars);
 echo $this->form()->closeTag();
?>
