<?php
$headText = 'Edit book';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
$form->setAttribute('action', $this->url('books/book/edit',
		['book_id' => $this->entityId]));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->partial('fields-partial', $this->vars);
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>