<?php
use Books\Model\DefinedTerm;
use Cake\Utility\Text;
// echo $this->navigation()->breadcrumbs();
?>
<h1><?php $titleFormat = "Fr. Kentenich dictionary German to %s";
echo sprintf($this->translate($titleFormat), $this->translate($this->inLanguageName));?></h1>
<?php
$objects = $this->objects;
foreach ($objects as $entryId => $object) :?>
<p id="<?php echo $this->escapeHtmlAttr($object['slug']);?>"><strong><?php 
    echo $this->formatEntity('dictionary-entry', $object, ['displayAsLink' => false]);?></strong> <?php 
    echo $this->escapeHtml($object['entry']);
    foreach ($object['links'] as $linkSlug) {
        $shortSlug = Text::truncate($linkSlug, 50);
        echo " <a href=\"#$linkSlug\">$shortSlug</a> ";
    }?></p>
<?php endforeach;?>
<script type="application/ld+json">
<?php echo $this->schemata;?>
</script>