<h1>Warning...</h1>
<p><?php echo sprintf(
    $this->translate("The user will be notified of this change. Are you sure you want to change the password of '%s'?"),
    $this->user['username']
); ?></p>
<?php $form = $this->form;
$form->setAttribute('action', $this->url(
    'juser/user/change-password',
    ['user_id' => $this->userId]
));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('userId'));
echo $this->formRow($form->get('newCredential'));
echo $this->formRow($form->get('newCredentialVerify'));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit'));
echo '&nbsp;';
?>
<a class="btn btn-default" href="<?php echo $this->url('juser'); ?>">Cancel</a>
<?php echo $this->form()->closeTag(); ?>
