<?php
$title = 'Create new role';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php $form = $this->form;
$this->form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('parentId'));
echo $this->formRow($form->get('isDefault'));
echo $this->formRow($form->get('security'));
echo $this->formSubmit($form->get('submit')); ?>
