<?php

use JUser\Controller\UsersController;

if ($this->status == UsersController::VERIFICATION_EXPIRED) :?>
<p><?php
echo $this->translate(
    'This verification token has expired. We have just sent you a new verification email, please check your email. '
    . 'If you\'re having problems please contact us'
   );?>: webmaster@schoenstatt.link</p>
<?php elseif ($this->status == UsersController::VERIFICATION_VERIFIED) :?>
<p><?php echo $this->translate('Your email has been verified! Please login to continue.');?></p>
<?php endif;?>