<?php $headTitle = $this->book['name'].' '.$this->chapter;
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headTitle);
?><h2><?php echo $this->escapeHtml($headTitle);?></h2>
<?php
$translationCount = count($this->translations);
$columnInfoByTranslationCount = [
    1 => ['width' => 8, 'offset' => 2],
    2 => ['width' => 5, 'offset' => 1],
    3 => ['width' => 4, 'offset' => 0],
    4 => ['width' => 3, 'offset' => 0],
];
$columnInfo = $columnInfoByTranslationCount[$translationCount];
foreach ($this->verseTranslations as $translations) :
$i = 0;?>
<div class="row">
    <?php foreach ($this->translations as $translation) :
        if (!isset($translations[$translation])) {
            continue;
        }
        $object = $translations[$translation];?>
        <div class="col-md-<?php echo $columnInfo['width'];
        if ($i === 0 && $columnInfo['offset'] > 0) {
            echo ' col-md-offset-'.$columnInfo['offset'];
        }?>">

		<?php echo '<strong>'.$this->escapeHtml($object['verse']).' </strong>'.$this->escapeHtml($object['text']);?>
        </div><?php 
        $i++;
        endforeach;?>
</div><?php endforeach;?>