<?php $headTitle = $this->book['name'].' '.$this->chapter;
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headTitle);
// echo $this->partial('search-bar', ['form' => $this->form]);
?><h2><?php echo $this->escapeHtml($headTitle);?></h2>
<?php
$translationCount = count($this->translations);
$columnInfoByTranslationCount = [
    1 => ['width' => 8, 'offset' => 2],
    2 => ['width' => 5, 'offset' => 1],
    3 => ['width' => 4, 'offset' => 0],
    4 => ['width' => 3, 'offset' => 0],
];
$columnInfo = $columnInfoByTranslationCount[$translationCount];
foreach ($this->verseTranslations as $translations) :
$i = 0;?>
<div class="row">
    <?php $isFirstTranslation = true;
    foreach ($this->translations as $translation) :
        if (!isset($translations[$translation])) {
            continue;
        }
        $object = $translations[$translation];?>
        <div class="col-md-<?php echo $columnInfo['width'];
        if ($i === 0 && $columnInfo['offset'] > 0) {
            echo ' col-md-offset-'.$columnInfo['offset'];
        }?>"<?php if ($isFirstTranslation) {
            echo sprintf(" id=\"%s\"", $this->escapeHtmlAttr($object['verse']));
        }?>>

		<?php echo '<strong>'.$this->escapeHtml($object['verse']).' </strong>'.$this->escapeHtml($object['text']);?>
        </div><?php 
        $i++;
        $isFirstTranslation = false;
        endforeach;?>
</div><?php endforeach;?>