<?php
use Bible\Filter\FromBibleworksMorphosyntacticCode;

$this->headScript()->appendFile($this->basePath() . '/js/gen-bootstrap-sortable.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-bootstrap-sortable.min.css');?>
<div class="row">
<div class="col-md-12">
<p>Found <?php echo count($this->rootWords);?> different greek words.</p>
<div id="word-list" class="table-responsive">
<table class="table sortable">
<thead>
<tr>
<th><?php echo $this->translate('Root');?></th>
<th><?php echo $this->translate('Part of speech');?></th>
<th><?php echo $this->translate('Occurrences');?></th>
<th><?php echo $this->translate('First verse');?></th>
<th><?php echo $this->translate('In John');?></th>
<th><?php echo $this->translate('Forms available');?></th>
</tr>
</thead>
<tbody>
<?php 
$re = '/(\d\d)(\d\d\d)(\d\d\d)/';
$bibleSearchUrl = $this->url('bible/search');
$morphoCodes = FromBibleworksMorphosyntacticCode::getGrammarCodes();
foreach ($this->rootWords as $object) :?>
<tr>
<td><a href="http://www.perseus.tufts.edu/hopper/morph?l=<?php echo urlencode($object['root']);?>&la=greek#lexicon"><?php 
echo $this->escapeHtml($object['root']);?></a></td>
<td><?php echo $this->escapeHtml($object['partOfSpeech']);?></td>
<td><?php echo $this->escapeHtml($object['occurrenceCount']);?></td>
<td><?php echo $this->verseFromId($object['firstVerseOccurrence']);?></td>
<td><?php echo $this->escapeHtml($object['johnOccurrenceCount']);
if (isset($object['johnFirstVerseOccurrence'])) {
    echo ' '.$this->verseFromId($object['johnFirstVerseOccurrence']);
}?></td>
<td><?php foreach ($object['formsAvailable'] as $form) {
    echo sprintf(
        '<a href="%s?search=%s@%s">%s</a> ', 
        $bibleSearchUrl,
        urlencode($object['root']),
        urlencode($form),
        $this->escapeHtml($form)
        );
}?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>
</div>
</div>