<h1><?php echo $this->translate('Translations');?></h1>
<p><a href="<?php echo $this->url('bible/translation', ['translation' => 'nab'])?>">English Bible</a> /
<a href="<?php echo $this->url('bible/translation', ['translation' => 'bnt'])?>">New Testament in Greek</a> /
<a href="<?php echo $this->url('bible/translation', ['translation' => 'lba'])?>">Biblia en español</a></p>
<h1><?php echo $this->translAbbrev[$this->translation];?></h1>
<?php foreach ($this->books as $book) :?>
<h2><?php echo $this->escapeHtml($book['bookName']);?></h2>
<p><?php for ($chapter = 1; $chapter <= $book['lastChapter']; $chapter++) : ?>
<a href="<?php echo $this->url('bible/text',
    ['translation' => $this->translation, 'book' => $book['bookAbbreviation'], 'chapter' => $chapter]
    );?>">
<?php echo $chapter;?></a>
<?php endfor;?></p>

<?php endforeach;?>
