<?php $this->headTitle('Bible'); 
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());?>
<h1><?php echo $this->translate('Bible');?></h1>
<?php foreach ($this->books as $book) :
    if (isset($book['chapterCount'])):?>
<h3><?php echo $this->escapeHtml($lang === 'es' ? $book['nameEs'] : $book['name']);?></h3>
<p><?php for ($chapter = 1; $chapter <= $book['chapterCount']; $chapter++) : ?>
<a href="<?php echo $this->url('bible/text',
    ['book' => $book['bookId'], 'chapter' => $chapter]
    );?>">
<?php echo $chapter;?></a>
<?php endfor;?></p>

<?php endif;
endforeach;?>
