<?php
use Bible\Model\BibleTable;
use Cake\Utility\Text;

echo $this->partial('search-bar', ['form' => $this->form]);

if (isset($this->verses)) : //a search has taken place
    if (empty($this->verses)) :?>
<p><?php echo $this->escapeHtml($this->translate('No results found.'));?></p>
    <?php else :
        foreach ($this->verses as $object) :?>
<h4><a href="<?php
echo $this->url('bible/text', [
    'book' => $object['book'],
    'chapter' => $object['chapter']
]) . '#' . $this->escapeHtml($object['verse']);?>"><?php
echo $this->escapeHtml($this->books[$object['book']]['name']) . ' '
. $this->escapeHtml($object['chapter']) . ',' . $this->escapeHtml($object['verse']);?></a> (<?php
if (is_string($object['translation']) && isset(BibleTable::TRANSLATIONS[$object['translation']])) {
    echo BibleTable::TRANSLATIONS[$object['translation']];
} else {
    echo $this->escapeHtml($object['translation']);
}?>)</h4>
<p><?= Text::highlight($object['text'], $this->search, ['format' => '<mark>\1</mark>']);?></p>
        <?php endforeach;
    endif;
endif;