<?php
/**
 * @param bool $centerOnPage
 * @param \Bible\Form\BibleSearchForm $form
 */

$form = $this->form;
$form->setAttribute('action', $this->url('bible/search'));
$form->prepare();?>
<div class="row search-bar <?php if ($this->centerOnPage) {
    echo "search-bar-center";
                           } ?>">
      <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div id="custom-search-input">
            <?php echo $this->form()->openTag($form); ?>
              <div class="input-group col-md-12">
                    <?php echo $this->formElement($form->get('search'));?>
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>
                      </button>
                  </span>
              </div>
            <?php echo $this->form()->closeTag();?>
          </div>
      </div>
</div>
