<?php
echo $this->simulate;
?>
<table class="table">
<tr><th></th>
<th></th>
<tr>
<tbody><?php $features = $this->features;
foreach ($features as $object) :
    ?><tr>
<td><?php echo $this->escapeHtml($object['name']);?></td>
<td><?php foreach ($object as $key => $value) :
    if ('name' !== $key && 'adminNotes' !== $key) :?>
    <strong><?php echo $this->escapeHtml($key);?></strong>: <?php
    if ($value instanceof \DateTime) {
        echo $this->dateFormat($value, IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE);
    } else {
        echo $this->escapeHtml($value);
    }
    ?><br>
    <?php endif;
    endforeach;?></td>
</tr>
<?php endforeach;?>
</tbody>
</table>
