<?php
$form = $this->form;
$form->setAttribute('action', $this->url('persons/search'));
$form->prepare();?>
<div class="row" style="margin-bottom: 30px;
<?php if ($this->centerOnPage) {
  echo " margin-top: 15%;";} ?>">
      <div class="col-md-6 col-md-offset-3 col-xs-12">
          <div id="custom-search-input">
           <?php echo $this->form()->openTag($form); ?>
              <div class="input-group col-md-12">
                  <?php echo $this->formElement($form->get('search'));?>
                  <span class="input-group-btn">
                      <button class="btn btn-info btn-lg" type="submit">
                          <i class="glyphicon glyphicon-search"></i>
                      </button>
                  </span>
              </div>
            <!-- <div class="row">
            	<div class="col-md-12">
                    <a data-toggle="collapse" data-target="#options" aria-expanded="false" aria-controls="options"><?php
                        echo $this->translate("Advanced options"); ?></a>
                    <?php if ($this->isAllowed('route/advanced-search')):?>
                        &nbsp;&nbsp;<a href="<?php echo $this->url('advanced-search'); ?>"><?php
                        echo $this->translate("Advanced search"); ?></a>
              		<?php endif;?>
            	</div>
            	<div id="options" class= "collapse row">
                    <div class="checkbox col-md-4">
                    	<?php echo $this->formCheckbox($form->get('showPhotos')); ?>
                    </div>
                    <?php if ($this->isAllowed('ex_members')):?>
                    	<div class="checkbox col-md-4">
                    		<?php echo $this->formCheckbox($form->get('exMembers')); ?>
                    	</div>
                    <?php endif;?>
                </div>
            </div> -->
            <?php echo $this->form()->closeTag();?>
          </div>
      </div>
</div>
<?php $this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $("form").submit(function(){
        $("input, select").each(function(index, obj){
            if($(obj).val() == "" || $(obj).val() == "false") {
                $(obj).remove();
            }
        });
    });
});
JS;
$this->inlineScript()->captureEnd();?>