<?php
$headText = 'Schoenstatt Shrines';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php
// echo $this->partial('search-bar', ['form' => $form, 'centerOnPage' => false]);

//separate by countryRegion
$regions = [];
foreach ($this->shrines as $associationId => $object) {
    if (!isset($regions[$object['countryRegion']])) {
        $regions[$object['countryRegion']] = [];
    }
    $regions[$object['countryRegion']][$associationId] = $object;
}
foreach ($regions as $region => $objects) :?>
<h3 id="<?= $region ?>"><?= $this->translate($region);?></h3>
<?php
    echo $this->partial('schoenstatt/associations/shrines-table', [
        'objects' => $objects,
        //     'wrapInPanel' => true,
    //     'showActive' => true,
    //     'showInactive' => false,
    //     'headerText'  => 'Shrines of the world',
    //     'columns'       => ['association'], //'person', 'email', 'telephone'],
    //     'associationFormatOptions' => [
        //         'showLabel' => false,
    //     ],
    ]);
endforeach;?>
<p><?php echo $this->translate('Initial shrine database courtesy of Matías Fortuño.');?></p>
<?php 
$datasets = $this->datasets;
if (isset($datasets) && is_array($datasets) && !empty($datasets)) :?>
<script type="application/ld+json">
<?php $json = json_encode($datasets, JSON_PRETTY_PRINT);
if (false !== $json) {
    echo $json;
}?>
</script>
<?php endif;?>