<?php
$headText = 'Schoenstatt Shrines';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php
// echo $this->partial('search-bar', ['form' => $form, 'centerOnPage' => false]);
$str1 = "Welcome to the Schoenstatt Shrine collaborative database! This database is freely available under the %s Licence so that anyone may use it.  For now, anyone who registers for an account may help keep the information current. Please help us complete the information!";

$str2 = "This data may be accessed directly by any apps or websites who which to receive up-to-date information via the %sREST API%s (application programming interface).";

$str3 = "Until 2019-10-18, this page will be oriented towards data-maintainers and therefore show the columns of pertinent information.";
?>

<p><?= sprintf($this->escapeHtml($this->translate($str1)), '<a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons BY-SA</a>')?></p>
<p><?= sprintf($this->escapeHtml($this->translate($str2)), '<a href="https://schoenstatt.link/en/api/v1/associations/findByKind?kind=sch-shrine" target="_blank">', '</a>')?></p>
<p><?= $this->escapeHtml($this->translate($str3))?></p>
<?php 
//separate by countryRegion
$regions = [];
foreach ($this->shrines as $associationId => $object) {
    if (!isset($regions[$object['countryRegion']])) {
        $regions[$object['countryRegion']] = [];
    }
    $regions[$object['countryRegion']][$associationId] = $object;
}
foreach ($regions as $region => $objects) :?>
<h3 id="<?= $region ?>"><?= $this->translate($region);?></h3>
<?php
$partial = $this->isAllowed('route/associations/association/edit') 
    ? 'schoenstatt/associations/shrines-table'
    : 'schoenstatt/associations/associations-table';
    echo $this->partial($partial, [
        'objects' => $objects,
        //     'wrapInPanel' => true,
    //     'showActive' => true,
    //     'showInactive' => false,
    //     'headerText'  => 'Shrines of the world',
    //     'columns'       => ['association'], //'person', 'email', 'telephone'],
    //     'associationFormatOptions' => [
        //         'showLabel' => false,
    //     ],
    ]);
endforeach;?>
<p><?php echo $this->translate('Initial shrine database courtesy of Matías Fortuño.');?></p>
<?php 
$datasets = $this->datasets;
if (isset($datasets) && is_array($datasets) && !empty($datasets)) :?>
<script type="application/ld+json">
<?php $json = json_encode($datasets, JSON_PRETTY_PRINT);
if (false !== $json) {
    echo $json;
}?>
</script>
<?php endif;?>