<?php
$headText = 'Schoenstatt Shrines';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php
// echo $this->partial('search-bar', ['form' => $form, 'centerOnPage' => false]);
$str1 = "Welcome to the Schoenstatt Shrine collaborative database! This database is freely available under the %s Licence so that anyone may use it.  For now, anyone who registers for an account may help keep the information current. Please help us complete the information!";

$str2 = "This data may be accessed directly by any apps or websites who which to receive up-to-date information via the %sREST API%s (application programming interface).";

$str3 = "Until 2019-10-18, this page will be oriented towards data-maintainers and therefore show the columns of pertinent information.";
?>

<p><?= sprintf($this->escapeHtml($this->translate($str1)), '<a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">Creative Commons BY-SA</a>')?></p>
<p><?= sprintf($this->escapeHtml($this->translate($str2)), '<a href="https://schoenstatt.link/en/api/v1/associations/findByKind?kind=sch-shrine" target="_blank">', '</a>')?></p>
<p><?= $this->escapeHtml($this->translate($str3))?></p>
<?php 
//separate by countryRegion
$regions = [];
$regionStats = [];
foreach ($this->shrines as $associationId => $object) {
    if (!isset($regions[$object['countryRegion']])) {
        $regions[$object['countryRegion']] = [];
    }
    if (!isset($regionStats[$object['countryRegion']])) {
        $regionStats[$object['countryRegion']] = [
            'id' => $object['countryRegion'].'-progress-bar',
            'maxScore' => 0,
            'score' => 0,
        ];
    }
    $regions[$object['countryRegion']][$associationId] = $object;
    $regionStats[$object['countryRegion']]['maxScore'] += 10;
    $regionStats[$object['countryRegion']]['score'] += $object['dataScore'];
}
foreach ($regions as $region => $objects) :?>
<h3 id="<?= $region ?>"><?= $this->translate($region);?></h3>
<?php if ($regionStats[$region]['score'] > 0 && $regionStats[$region]['maxScore'] > 0):
$percent = floor($regionStats[$region]['score'] / $regionStats[$region]['maxScore'] * 100);
$regionStats[$region]['percent'] = $percent;?>
<div class="progress">
  <div id="<?= $regionStats[$region]['id']?>" class="progress-bar" role="progressbar" aria-valuenow="<?= $percent?>" aria-valuemin="0" aria-valuemax="100">
    <?= $percent.$this->translate('% Complete')?>
  </div>
</div>
<?php
else:
    unset($regionStats[$region]);
endif;
$partial = $this->isAllowed('route/associations/association/edit') 
    ? 'schoenstatt/associations/shrines-table'
    : 'schoenstatt/associations/associations-table';
    echo $this->partial($partial, [
        'objects' => $objects,
        //     'wrapInPanel' => true,
    //     'showActive' => true,
    //     'showInactive' => false,
    //     'headerText'  => 'Shrines of the world',
    //     'columns'       => ['association'], //'person', 'email', 'telephone'],
    //     'associationFormatOptions' => [
        //         'showLabel' => false,
    //     ],
    ]);
endforeach;?>
<p><?php echo $this->translate('Initial shrine database courtesy of Matías Fortuño.');?></p>
<?php 
$datasets = $this->datasets;
if (isset($datasets) && is_array($datasets) && !empty($datasets)) :?>
<script type="application/ld+json">
<?php $json = json_encode($datasets, JSON_PRETTY_PRINT);
if (false !== $json) {
    echo $json;
}?>
</script>
<?php endif;

//code to set the width json of the progress bars. Must be done by javascript because
//CSP doesn't allow us to use inline-styles
$regionJson = json_encode($regionStats);
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
  var regions = $regionJson;
  Object.keys(regions).forEach(function(k){
    percent = regions[k]["percent"]+"%";
    $('#'+regions[k]["id"]).css("width", percent);
  });
});
JS;
$this->inlineScript()->captureEnd();
?>