<?php
$headText = 'Submitting photos';
$this->headTitle($headText);
$text = [
    'en' => <<<MD
## Submitting photos

By initiative of Alberto León, creator of the "Schoenstatt Shrines" app, we began showing images of the shrines in July 2019. If you have photos to contribute please follow these instructions. Please note: only send us photos that are in the Public Domain, ones you have personally taken (you give us permission to publish without attribution), or photos for which you already have permission to publish on schoenstatt.link.

### File naming

Files are named by the identifier of the shrine.

1. Open the page of the shrine for which you wish to submit a photo.
2. Look at the URL on the top of the browser window. For example, the original shrine is located at https://schoenstatt.link/en/SL10319A/original-schoenstatt-shrine, where "**SL10319A**" is the identifier for that shrine.
3. The file name for photo should then be SL10319A.jpg (or SL10319A.png)

If you would like to send more than one photo, the primary photo should be an outdoor photo of the front of the shrine, named as shown above. **Additional photos** should add an incremental two-digit number separated by a dash:

SL10319A.jpg  (*outdoor photo*)

SL10319A-01.jpg

SL10319A-02.jpg

SL10319A-03.jpg

#### File types

We are currently accepting files in jpg and png format.

#### Sending photos

Please email photos to webmaster@schoenstatt.link where they should be uploaded to the website within a day.

**Thanks for the help!**
MD
,
    'es' => <<<MD
## Enviando fotos
    
Por iniciativa de Alberto León, creador de la "Santuarios de Schoenstatt" app, comenzamos mostrando fotos de los santuarios en julio del 2019. Si tienes fotos que quieres compartirnos, por favor sigue estas instrucciones. Nota bene: solo envíanos fotos que están en el dominio público, fotos que han sacado personalmente (nos dan permiso de publicarlas sin atribución), o fotos por las cuales ya tienes permiso de publicar en schoenstatt.link.

### Nombre de los archivos
    
Los archivos llevan por nombre al identificador del santuario.

1. Abre la página del santuario donde debe aparecer tu foto nueva.
2. Fíjate en el URL arriba en la ventana del browser. Por ejemplo, el Santuario Original está ubicado en https://schoenstatt.link/es/SL10319A/santuario-original-de-schoenstatt, donde "**SL10319A**" es el identificador de ese santuario.
3. El nombre del archivo entonces debe ser SL10319A.jpg (o SL10319A.png)
    
Si te gustaría enviarnos más de una foto para un santuario, la foto principal debe ser una sacada desde afuera mirando la puerta del santuario, y debe llevar el nombre como mostramos arriba (SL10319A.jpg). A las **fotos adicionales** se debe agregar un número incremental de dos dígitos, separado por un guión:
    
SL10319A.jpg  (*foto afuera del santuario, mirando de frente*)
    
SL10319A-01.jpg
    
SL10319A-02.jpg
    
SL10319A-03.jpg
    
#### Formatos de foto

Actualmente, aceptamos archivos en formato jpg y png.
    
#### Enviando las fotos

Por favor, envía las fotos a webmaster@schoenstatt.link donde se deberían subir a la página web dentro de un día.

**¡Gracias por la ayuda!**
MD
];
$locale = \Locale::getDefault();
if ($locale === 'es_ES') {
    echo $this->markdown($text['es']);
} else {
    echo $this->markdown($text['en']);
}
