<?php
$headText = 'Schoenstatt Wayside Shrines';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php

$str2 = "This data may be accessed directly by any apps or websites which wish to receive up-to-date information via the %sREST API%s (application programming interface).";
$str4 = "Do you have shrine photos to submit? See our %sphoto submission process%s.";
$photosUrl = $this->url('shrines/submitting-photos');
?>

<p><?= sprintf($this->escapeHtml($this->translate($str2)), '<a href="https://schoenstatt.link/en/api/v1/associations/findByKind?kind=sch-wayside-shrine" target="_blank">', '</a>')?></p>
<p><?= sprintf($this->escapeHtml($this->translate($str4)), "<a href=\"$photosUrl\">", "</a>");?>
<?php
$isModerator = $this->isAllowed('route/association-edit');

if ($isModerator) :
    $totalPercent = $this->totalPercent;?>
<p><strong><?= $this->translate('Total shrine progress')?>:</strong></p>
<div class="progress">
  <div id="total-progress-bar" class="progress-bar" role="progressbar" aria-valuenow="<?= $totalPercent?>" aria-valuemin="0" aria-valuemax="100">
    <?= $totalPercent . $this->translate('% Complete')?>
  </div>
</div>
    <?php
endif;
$partial = $isModerator
    ? 'schoenstatt/associations/shrines-table'
    : 'schoenstatt/associations/associations-table';
foreach ($this->regions as $region => $objects) :?>
<h3 id="<?= $region ?>"><?= $this->translate($region);?></h3>
    <?php if ($isModerator) :?>
<div class="progress">
  <div id="<?= $this->regionStats[$region]['id']?>" class="progress-bar" role="progressbar" aria-valuenow="<?= $this->regionStats[$region]['percent']?>" aria-valuemin="0" aria-valuemax="100">
        <?= $this->regionStats[$region]['percent'] . $this->translate('% Complete')?>
  </div>
</div>
        <?php
    endif;
    echo $this->partial($partial, [
        'objects' => $objects,
        //     'wrapInPanel' => true,
    //     'showActive' => true,
    //     'showInactive' => false,
    //     'headerText'  => 'Shrines of the world',
    //     'columns'       => ['association'], //'person', 'email', 'telephone'],
    //     'associationFormatOptions' => [
        //         'showLabel' => false,
    //     ],
    ]);
endforeach;?>
<p><?= $this->translate('Initial shrine database courtesy of Matías Fortuño, Vínculo Magazine and schoenstatt.org.')?></p>
<?php
$datasets = $this->datasets;
if (isset($datasets) && is_array($datasets) && ! empty($datasets)) :?>
<script type="application/ld+json">
    <?php $json = json_encode($datasets, JSON_PRETTY_PRINT);
    if (false !== $json) {
        echo $json;
    }?>
</script>
<?php endif;

//code to set the width json of the progress bars. Must be done by javascript because
//CSP doesn't allow us to use inline-styles
$regionJson = json_encode($this->regionStats);
$totalPercent = '"' . $totalPercent . '%"';
$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
  $('#total-progress-bar').css("width", $totalPercent);
  var regions = $regionJson;
  Object.keys(regions).forEach(function(k){
    percent = regions[k]["percent"]+"%";
    $('#'+regions[k]["id"]).css("width", percent);
  });
});
JS;
$this->inlineScript()->captureEnd();
?>