<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = 'New blog post';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>

<?php $form = $this->form;
$form->setAttribute('action', $this->url('blog/create'));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->form()->closeTag();
?>