<?php /** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = $this->translate($this->entity['title']);
$this->headTitle($headText);
$object = $this->entity;?>
<h1><?php echo $this->escapeHtml($headText);?></h1>

<p><i class="fa fa-user"></i> <?php echo sprintf($this->translate('by %s'), $object['createdByUsername']);
?>  <i class="fa fa-calendar"></i> <?php echo $this->translate('Posted');?> <?php echo $this->diffForHumans($this->entity['updatedOn']);?></p>
<p><i class="fa fa-tags"></i> <?php echo $this->translate('Tags');?>: <?php 
foreach ($object['tags'] as $tag) : ?>
<a href=""><span class="badge badge-info"><?php echo $this->escapeHtml($tag); //@todo translate this later?></span></a> 
<?php endforeach;?></p>
<hr>
<?php
$parsedown = new \Parsedown();
$parsedown->setSafeMode(true);
$translatedText = $parsedown->text($this->translate($this->entity['markdownText']));
echo $translatedText;?>
<hr>
    <!-- the comment box -->
<?php if (isset($this->commentForm)) {
    echo $this->partial('sion-model/comments/create', [
        'form' => $this->commentForm,
    ]);
}
echo $this->partial('sion-model/comments/comments-list', [
    'comments' => $this->comments,
]);

if (isset($this->schema)) {
    /** @var \Spatie\SchemaOrg\BlogPosting $schema */
    $schema = $this->schema;
    $thisUrl = $this->serverUrl().$this->url(null, [], [], true);
    $schema->setProperty('url', $thisUrl);
    echo $schema->toScript();
}?>
