<?php /** @var \Zend\View\Renderer\PhpRenderer $this */
$headText = $this->translate($this->entity['title']);
$this->headTitle($headText);
$object = $this->entity;?>
<h1><?php echo $this->escapeHtml($headText);?></h1>
<?= $this->partial('_front-matter', ['entity' => $this->entity]);?>
<hr>
<?php
$parsedown = new \Parsedown();
$parsedown->setSafeMode(true);
$translatedText = $parsedown->text($this->translate($this->entity['markdownText']));
echo $translatedText;?>
<hr>
    <!-- the comment box -->
<?php if (isset($this->commentForm)) {
    echo $this->partial('sion-model/comments/create', [
        'form' => $this->commentForm,
    ]);
}
echo $this->partial('sion-model/comments/comments-list', [
    'comments' => $this->comments,
]);

if (isset($this->schema)) {
    /** @var \Spatie\SchemaOrg\BlogPosting $schema */
    $schema = $this->schema;
    $thisUrl = $this->serverUrl() . $this->url(null, [], [], true);
    $schema->setProperty('url', $thisUrl);
    echo $schema->toScript();
}?>
