<?php /** @var \Zend\View\Renderer\PhpRenderer $this */
$object = $this->entity;?>
<h1><?php echo $this->escapeHtml($this->entity['title']);?></h1>

<p><i class="fa fa-user"></i> <?php echo sprintf($this->translate('by %s'), $object['createdByUsername']);
?>  <i class="fa fa-calendar"></i> <?php echo $this->translate('Posted');?> <?php echo $this->diffForHumans($this->entity['updatedOn']);?></p>
<p><i class="fa fa-tags"></i> <?php echo $this->translate('Tags');?>: <?php 
foreach ($object['tags'] as $tag) : ?>
<a href=""><span class="badge badge-info"><?php echo $this->escapeHtml($tag); //@todo translate this later?></span></a> 
<?php endforeach;?></p>
<hr>
<?php
echo $this->entity['htmlText'];?>
<hr>
    <!-- the comment box -->
<?php if (isset($this->commentForm)) {
    echo $this->partial('sion-model/comments/create', [
        'form' => $this->commentForm,
    ]);
}
echo $this->partial('sion-model/comments/comments-list', [
    'comments' => $this->comments,
]);?>
