<div class="alert alert-warning hide" role="alert" id="timer"></div>
<?php
$headText = $this->person['fullFriendlyName'];
$this->headTitle()->setTranslatorEnabled(false);
$this->headTitle($headText);
$libraries = [];
foreach ($this->entities as $checkoutId => $object) {
    if (!isset($libraries[$object['book']['libraryId']]) &&
        $this->isAllowed($object['book']['library']['resourceId'], 'administrate')
    ) {
        $libraries[$object['book']['libraryId']] = $object['book']['library'];
    }
}?>
<h1><?php echo $this->escapeHtml($headText);?></h1>
<?php $personId = $this->person['personId'];
if (!empty($libraries)):?>
<p><?php foreach ($libraries as $libraryId => $library) :?><a href="<?php
echo $this->url('libraries/library/send-book-notices', ['library_id' => $libraryId], ['query' => ['borrowers' => [$personId], 'onlyOverdueBorrowers' => '0']]);?>" class="btn btn-primary"><?php
        echo sprintf($this->translate('Send email regarding %s books'), $library['name']);?></a> <?php
    endforeach;?></p><?php
endif;
echo $this->partial('books/checkouts/checkout-list', [
    'entities' => $this->entities,
    'columns' => ['library', 'book', 'checkedOutOn', 'dueOn', 'checkedInOn'],
]);
$timerText = $this->translate('This page will redirect in {0} seconds.');
$jsScript= <<<JS
var count = 15;
var redirect = "/libraries/3";
var timerTextTranslations = {
    "en": "This page will redirect in {0} seconds.",
    "es": "Esta página será redireccionada en {0} segundos.",
};
var lang = $('html')[0].lang;
var timerText = $timerText;
\$timer = $("#timer");
// First, checks if it isn't implemented yet.
if (!String.prototype.format) {
  String.prototype.format = function() {
    var args = arguments;
    return this.replace(/{(\d+)}/g, function(match, number) {
      return typeof args[number] != 'undefined'
        ? args[number]
        : match
      ;
    });
  };
}
countDown();

function countDown() {
    if(count > 0){
        count--;
        \$timer.show();
        \$timer.html(timerText.format(count));
        setTimeout("countDown()", 1000);
    }else{
        window.location.href = redirect;
    }
}
JS;

$this->inlineScript()->captureStart();
echo $jsScript;
$this->inlineScript()->captureEnd();
?>
