<?php

declare(strict_types=1);

namespace JTranslate\Console\Command;

use JTranslate\Migration\MigrationRunner;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Throwable;

use function count;
use function is_string;
use function str_replace;
use function var_export;

/**
 * Brings the translation database up to what this version of the library expects.
 *
 * Three modes, because the deployment this was written for cannot use only one:
 *
 * - default — apply pending migrations with the application's own credentials. Right
 *   for a development capsule and for any host whose database user has DDL rights.
 * - `--pretend` — print the SQL and change nothing. **This is the production path
 *   for the schema migration**, because the web application's database user
 *   deliberately lacks DDL rights; the output goes to whoever holds an account that
 *   does not.
 * - `--mark-applied=NAME` — record a migration as applied without running it, for
 *   after somebody has run the printed SQL by hand, and for declaring the tables an
 *   existing installation already has as migration 001.
 *
 * `--status` reports without changing anything.
 */
final class MigrateCommand extends Command
{
    public function __construct(private readonly MigrationRunner $runner)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('jtranslate:migrate')
            ->setDescription('Apply JTranslate database migrations')
            ->addOption('status', null, InputOption::VALUE_NONE, 'Show what is applied and what is pending')
            ->addOption(
                'pretend',
                null,
                InputOption::VALUE_NONE,
                'Print the SQL instead of running it — the production path, since the web DB user has no DDL rights'
            )
            ->addOption(
                'mark-applied',
                null,
                InputOption::VALUE_REQUIRED,
                'Record a migration as applied without running it, after someone ran the SQL by hand'
            );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $markApplied = $input->getOption('mark-applied');
        if (is_string($markApplied) && '' !== $markApplied) {
            return $this->markApplied($io, $markApplied);
        }

        if ($input->getOption('status')) {
            return $this->status($io);
        }

        return $input->getOption('pretend') ? $this->pretend($io) : $this->apply($io);
    }

    private function status(SymfonyStyle $io): int
    {
        $applied = $this->runner->applied();
        $rows    = [];
        foreach ($this->runner->migrations() as $migration) {
            $name     = $migration->name();
            $rows[][] = $name;
            $rows[count($rows) - 1][] = isset($applied[$name]) ? 'applied ' . $applied[$name] : 'PENDING';
            $rows[count($rows) - 1][] = $migration->describe();
        }
        $io->table(['migration', 'state', 'what it does'], $rows);

        if ([] === $applied) {
            $io->note(
                'Nothing is recorded as applied. On an installation that predates this command that is expected '
                . 'rather than alarming: the tables exist, they were created by hand. Run with --pretend to see '
                . 'what would run, then --mark-applied=001-create-phrase-tables to record reality.'
            );
        }

        return self::SUCCESS;
    }

    private function pretend(SymfonyStyle $io): int
    {
        $pending = $this->runner->pending();
        if ([] === $pending) {
            $io->success('Nothing pending.');

            return self::SUCCESS;
        }

        $io->writeln('-- JTranslate migrations, generated by `jtranslate:migrate --pretend`.');
        $io->writeln('-- Nothing below has been run. Parameters are shown as SQL comments;');
        $io->writeln('-- substitute them, or run this command without --pretend where DDL is permitted.');
        $io->writeln('');
        $io->writeln($this->runner->trackingTableSql() . ';');
        $io->writeln('');

        foreach ($pending as $migration) {
            $io->writeln('-- ' . $migration->name() . ' — ' . $migration->describe());
            foreach ($this->runner->preview($migration) as $statement) {
                $io->writeln(str_replace("\n", "\n", $statement['sql']) . ';');
                if ([] !== $statement['parameters']) {
                    $io->writeln('--   parameters: ' . var_export($statement['parameters'], true));
                }
            }
            $io->writeln('');
            $io->writeln(
                "INSERT INTO `" . MigrationRunner::TRACKING_TABLE . '` (`migration`, `applied_on`) '
                . "VALUES ('" . $migration->name() . "', UTC_TIMESTAMP());"
            );
            $io->writeln('');
        }

        return self::SUCCESS;
    }

    private function apply(SymfonyStyle $io): int
    {
        $pending = $this->runner->pending();
        if ([] === $pending) {
            $io->success('Nothing pending.');

            return self::SUCCESS;
        }

        foreach ($pending as $migration) {
            try {
                $count = $this->runner->apply($migration);
            } catch (Throwable $e) {
                $io->error($migration->name() . ' failed: ' . $e->getMessage());
                //Stop rather than continue. Migrations are ordered because later ones
                //assume earlier ones; running 002 after 001 failed would report a
                //second, confusing failure about a table that does not exist.
                return self::FAILURE;
            }
            $io->writeln($migration->name() . ': ' . $count . ' statement(s)');
        }

        $io->success('Applied ' . count($pending) . ' migration(s).');
        $io->note(
            'Compiled catalogs are not written by this command. Run jtranslate:export-catalogs to render the '
            . 'seeded translations to disk, or the site will keep serving what is already there.'
        );

        return self::SUCCESS;
    }

    private function markApplied(SymfonyStyle $io, string $name): int
    {
        $known = [];
        foreach ($this->runner->migrations() as $migration) {
            $known[] = $migration->name();
        }
        if (! in_array($name, $known, true)) {
            $io->error('No migration is called "' . $name . '". Known: ' . implode(', ', $known));

            return self::FAILURE;
        }

        try {
            $this->runner->markApplied($name);
        } catch (Throwable $e) {
            $io->error($e->getMessage());

            return self::FAILURE;
        }

        $io->success($name . ' recorded as applied. Nothing was run.');

        return self::SUCCESS;
    }
}
