<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JUser\Controller\UsersController'     => __DIR__ . '/src/JUser/Controller/UsersController.php',
    'JUser\Entity\Role'                    => __DIR__ . '/src/JUser/Entity/Role.php',
    'JUser\Entity\User'                    => __DIR__ . '/src/JUser/Entity/User.php',
    'JUser\Form\ChangeOtherPasswordForm'   => __DIR__ . '/src/JUser/Form/ChangeOtherPasswordForm.php',
    'JUser\Form\CreateRoleForm'            => __DIR__ . '/src/JUser/Form/CreateRoleForm.php',
    'JUser\Form\DeleteUserForm'            => __DIR__ . '/src/JUser/Form/DeleteUserForm.php',
    'JUser\Form\EditUserForm'              => __DIR__ . '/src/JUser/Form/EditUserForm.php',
    'JUser\Model\User'                     => __DIR__ . '/src/JUser/Model/User.php',
    'JUser\Model\UserTable'                => __DIR__ . '/src/JUser/Model/UserTable.php',
    'JUser\Module'                         => __DIR__ . '/src/JUser/Module.php',
    'JUser\Service\CreateRoleFormFactory'  => __DIR__ . '/src/JUser/Service/CreateRoleFormFactory.php',
    'JUser\Service\EditUserFormFactory'    => __DIR__ . '/src/JUser/Service/EditUserFormFactory.php',
    'JUser\Service\MailMessageFactory'     => __DIR__ . '/src/JUser/Service/MailMessageFactory.php',
    'JUser\Service\MailTransportFactory'   => __DIR__ . '/src/JUser/Service/MailTransportFactory.php',
    'JUser\Service\UsersControllerFactory' => __DIR__ . '/src/JUser/Service/UsersControllerFactory.php',
    'JUser\Service\UserTableFactory'       => __DIR__ . '/src/JUser/Service/UserTableFactory.php',
);
