<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JUser\Service\ConfigServiceFactory'              => __DIR__ . '/src/JUser/Service/ConfigServiceFactory.php',
    'JUser\Service\UsersControllerFactory'            => __DIR__ . '/src/JUser/Service/UsersControllerFactory.php',
    'JUser\Service\CreateRoleFormFactory'             => __DIR__ . '/src/JUser/Service/CreateRoleFormFactory.php',
    'JUser\Service\EditUserFormFactory'               => __DIR__ . '/src/JUser/Service/EditUserFormFactory.php',
    'JUser\Service\UserTableFactory'                  => __DIR__ . '/src/JUser/Service/UserTableFactory.php',
    'JUser\Entity\User'                               => __DIR__ . '/src/JUser/Entity/User.php',
    'JUser\Entity\Role'                               => __DIR__ . '/src/JUser/Entity/Role.php',
    'JUser\Controller\UsersController'                => __DIR__ . '/src/JUser/Controller/UsersController.php',
    'JUser\Model\PersonValueOptionsProviderInterface' => __DIR__ . '/src/JUser/Model/PersonValueOptionsProviderInterface.php',
    'JUser\Model\UserTable'                           => __DIR__ . '/src/JUser/Model/UserTable.php',
    'JUser\Model\User'                                => __DIR__ . '/src/JUser/Model/User.php',
    'JUser\Form\ChangeOtherPasswordForm'              => __DIR__ . '/src/JUser/Form/ChangeOtherPasswordForm.php',
    'JUser\Form\EditUserForm'                         => __DIR__ . '/src/JUser/Form/EditUserForm.php',
    'JUser\Form\CreateRoleForm'                       => __DIR__ . '/src/JUser/Form/CreateRoleForm.php',
    'JUser\Form\DeleteUserForm'                       => __DIR__ . '/src/JUser/Form/DeleteUserForm.php',
    'JUser\Module'                                    => __DIR__ . '/src/JUser/Module.php',
    'JUser\View\Helper\UserWithIp'                    => __DIR__ . '/src/JUser/View/Helper/UserWithIp.php',
    'JUser\View\Helper\IpPlace'                       => __DIR__ . '/src/JUser/View/Helper/IpPlace.php',
    'JUser\View\RedirectionStrategy'                  => __DIR__ . '/src/JUser/View/RedirectionStrategy.php',
);
