#!/usr/bin/env bash
#
# Records the application's schema, into database/base-schema.sql.
#
#     ./tools/schema-dump.sh            # rewrite the recording
#     ./tools/schema-dump.sh --check    # regenerate into a temp file and diff, exit 1 on drift
#
# WHY THIS EXISTS: `database/` holds incremental migrations and, until now, no schema to
# apply them to. Of the 48 tables the capsule holds, 34 are created by some migration in
# `database/`; the other 14 only ever existed on a server — twelve from the 2016 one, and
# `jtranslate_migration` and `trans_translations_history`, which belong to JTranslate's own
# PHP migration runner rather than to `database/*.sql`. So nothing in this repository could
# build a database, which is why the capsule cannot be rebuilt (CLAUDE.md says so), why a
# contributor cannot run the suite, and why CI skips 37 test classes on a connection
# failure rather than on a missing row.
#
# This is DDL: no rows, no personal data, publishable. The 26 column and table comments it
# carries are schema documentation and are kept deliberately — they are the only place some
# of these columns are explained at all.
#
# WHAT IS DELIBERATELY NOT IN IT:
#
#   · `sch_migration`. tools/migrate.sh creates the ledger itself with CREATE TABLE IF NOT
#     EXISTS, and which migrations an environment has applied is that environment's state,
#     not the application's schema. It is absent from the capsule for the same reason.
#   · AUTO_INCREMENT counters. mysqldump writes the next value for every table, which leaks
#     the magnitude of the row counts and, worse, changes on every write — a recording that
#     differs whenever anyone uses the site cannot be diffed, and --check would be noise.
#   · The dump header's server version and host, and the two comment lines naming the
#     database. Those move with the container image and the environment, not with our
#     schema — and dropping them makes the round-trip below exact: a database built FROM
#     this file re-dumps to this file, byte for byte.
#
# So a diff against this file is a schema change and nothing else, which is what makes
# `--check` a usable gate. Same arrangement as tools/sql-surface.sh and tools/acl-table.php:
# a tool that writes a reviewed artefact, because capturing needs the capsule and a
# reviewed artefact is what a human can actually read.
#
# Regenerate it whenever a migration changes the schema, and READ THE DIFF: a changed line
# is a column the application will meet in production, not something to accept because the
# tool printed it.
set -uo pipefail

cd "$(dirname "$0")/.."

OUT=database/base-schema.sql
# Overridable so the recording can be re-dumped from a database built FROM it — the
# round-trip ci-local runs — and so CI can point this at its own service container.
DB=${SCHEMA_DUMP_DB:-ourlink_db1}
DB_USER=${SCHEMA_DUMP_USER:-schoenstatt}
DB_PASS=${SCHEMA_DUMP_PASS:-schoenstatt}
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [ $# -gt 0 ] && [ "${1:-}" != "--check" ]; then
    printf 'usage: %s [--check]\n' "$0" >&2
    exit 2
fi

# --no-data is the whole point; --routines/--triggers/--events cost nothing today (the
# capsule has none of each) and mean a future one cannot go missing silently.
# --single-transaction keeps the read off the site's locks.
generate() {
    cat <<'HEADER'
-- The application's schema, with no rows in it.
--
-- Generated by tools/schema-dump.sh from the capsule; `./tools/schema-dump.sh --check`
-- fails when it no longer matches. Do not hand-edit: a schema change belongs in a
-- database/*.sql migration, and this file is regenerated after that migration runs.
--
-- AUTO_INCREMENT counters and the dump's server/host header are stripped on purpose, so a
-- diff here is a schema change and nothing else. `sch_migration` is absent because
-- tools/migrate.sh creates the ledger itself and what an environment has applied is its
-- own state.

HEADER
    docker compose exec -T db mysqldump \
        -u"$DB_USER" -p"$DB_PASS" \
        --no-data --routines --triggers --events \
        --skip-dump-date --single-transaction \
        "$DB" 2>/dev/null \
    | sed -E \
        -e 's/ AUTO_INCREMENT=[0-9]+//g' \
        -e '/^-- MariaDB dump /d' \
        -e '/^-- Host: /d' \
        -e '/^-- Server version/d' \
        -e '/enable the sandbox mode/d' \
        -e "/^-- Dumping (events|routines) for database /d"
}

TMP=$(mktemp "${TMPDIR:-/tmp}/base-schema-XXXXXX.sql")
trap 'rm -f "$TMP"' EXIT

generate > "$TMP"
STATUS=$?

# An empty or truncated dump must never overwrite a good recording, and must not pass
# --check either. mysqldump exits 0 on some partial reads, so judge the content.
TABLES=$(grep -c '^CREATE TABLE' "$TMP")
if [ "$STATUS" -ne 0 ] || [ "$TABLES" -lt 40 ]; then
    printf 'schema-dump: mysqldump produced %s tables (expected at least 40). Is the capsule up?\n' \
        "$TABLES" >&2
    exit 1
fi

if [ "$CHECK" -eq 1 ]; then
    if diff -u "$OUT" "$TMP"; then
        printf 'schema-dump: %s matches the capsule (%s tables)\n' "$OUT" "$TABLES"
        exit 0
    fi
    printf '\nschema-dump: %s is stale. Regenerate with ./tools/schema-dump.sh and read the diff.\n' \
        "$OUT" >&2
    exit 1
fi

cp "$TMP" "$OUT"
printf 'schema-dump: wrote %s (%s tables, %s bytes)\n' "$OUT" "$TABLES" "$(wc -c < "$OUT")"
