<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$headText = 'Add new composition';
$this->headTitle($headText); ?>
<h1><?php echo $this->translate($headText);?></h1>
<?php $form = $this->form;
// var_dump($form);
$form->setAttribute('action', $this->url(null, [], [], true));
$form->prepare();
echo $this->form()->openTag($form);
//don't include
echo $this->partial('fields-partial', [
    'form' => $form,
]);
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
