<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$this->headLink()->appendStylesheet($this->basePath() . '/css/gen-selectize-markdown-jquery-ui.css');
$lang = \Locale::getPrimaryLanguage(\Locale::getDefault());
$this->headScript()->appendFile($this->basePath() . "/js/gen-validate-selectize-markdown-$lang.js");
/** @var \Books\Form\CompositionForm $form */
$form = $this->form;
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('disambiguatingDescription'));
// echo $this->formRow($form->get('slug'));
$this->formSelect()->setTranslatorEnabled(false);
echo $this->formRow($form->get('inLanguage'));
echo $this->formRow($form->get('country'));
echo $this->formRow($form->get('yearPublished'));
echo $this->formRow($form->get('composersAll'));
echo $this->formRow($form->get('lyricistsAll'));
echo $this->formRow($form->get('openLicenseUrl'));
echo $this->formRow($form->get('copyrightInfo'));
echo $this->formRow($form->get('copyrightContactEmail'));
echo $this->formRow($form->get('tags'));
echo $this->formRow($form->get('derivedFromCompositionId'));
echo $this->formRow($form->get('chordProSpec'));
echo $this->formRow($form->get('lyrics'));
echo $this->formRow($form->get('lilyPondSpec'));
// echo $this->formRow($form->get('musicalKey'));
// echo $this->formRow($form->get('alternateKey'));
// echo $this->formRow($form->get('alternateKeyLabel'));
$this->formSelect()->setTranslatorEnabled(true);
echo $this->formRow($form->get('url1'));
echo $this->formRow($form->get('url1Label'));
echo $this->formRow($form->get('url2'));
echo $this->formRow($form->get('url2Label'));
echo $this->formRow($form->get('url3'));
echo $this->formRow($form->get('url3Label'));

echo $this->formRow($form->get('security'));
$jsScript = <<<JS
$("select[name='tags[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='country']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='composersAll[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='lyricistsAll[]']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='derivedFromCompositionId']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='inLanguage']").selectize({
    create: false,
    sortField: 'text'
});
$("select[name='url1Label']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='url2Label']").selectize({
    create: true,
    sortField: 'text'
});
$("select[name='url3Label']").selectize({
    create: true,
    sortField: 'text'
});
JS;

$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
