<p class="pull-right"><a class="btn btn-primary" href="<?= $this->url('music/create-composition')?>"><?= $this->translate('Add new composition')?></a></p>
<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$currentLanguage = '';
foreach ($this->objects as $object) :
if ($currentLanguage !== $object['inLanguage']) :
$currentLanguage = $object['inLanguage'];?>
<h2><?= $this->languageNames[$object['inLanguage']]?></h2>
<?php endif;?>
<p><?= $this->formatEntity('composition', $object);?></p>
<?php endforeach;