<div class="jumbotron">
  <div class="container">
    <h1><?php echo $this->translate("We need your help!");?></h1>
    <p><?php echo sprintf($this->translate("Schoenstatt Link hopes to facilitate communication by dramatically increasing and improving Schoenstatt's web presence. We use the %s to help internet users find the Schoenstatt communities and shrines nearby, as well information on Schoenstatt books and material. Please help us centralize this information by the end of 2018!"),
        sprintf('<a href="%s">%s</a>', $this->translate('https://en.wikipedia.org/wiki/Knowledge_Graph'), $this->translate('Google Knowledge Graph'))); ?></p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> -->
  </div>
</div>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2><?php echo $this->translate("Are you a Kentenich scholar?");?></h2>
      <p><?php echo $this->translate("Probably the greatest challenge for our generation is transmitting the wisdom and charism of our Father and Founder. Help us by completing our bibliography of Fr. Kentenich and writing brief book summaries.");?></p>
      <p><a class="btn btn-default" href="mailto:webmaster@schoenstatt.link" role="button"><?php echo $this->translate('Contact us');?> »</a></p>
    </div>
    <div class="col-md-4">
      <h2><?php echo $this->translate("Are you bilingual?");?></h2>
      <p><?php echo $this->translate("Schoenstatt is an international movement which requires to provide information in many languages. Help us make our site accessible to the whole world!");?></p>
      <p><a class="btn btn-default" href="mailto:webmaster@schoenstatt.link" role="button"><?php echo $this->translate('Contact us');?> »</a></p>
   </div>
    <div class="col-md-4">
      <h2><?php echo $this->translate('Are you a developer?');?></h2>
      <p><?php echo $this->translate("About half of the work to maintain a reliable, centralized source of information depends on programmers who can provide the easy-to-use tools to submit and access the data.");?></p>
      <p><a class="btn btn-default" href="mailto:webmaster@schoenstatt.link" role="button"><?php echo $this->translate('Contact us');?> »</a></p>
    </div>
  </div>
</div>