<?php  $text = <<<EOT
### What is Schoenstatt Link?

Schoenstatt Link is effectively a database for anything related to the Schoenstatt Movement. We hope to encourage the creation of new widely-featured phone applications. We provide a structure for wide, multi-lingual data collection projects. Anyone who creates an account here can help update information!

### Who are we reaching out to?

We have three main audiences that we wish to serve:

1. **Schoenstatt Movement leaders**. By modeling Schoenstatt's organizational structure, we hope to provide a dynamic way to maintain movement contacts throughout the world while respecting everyone's privacy.
2. **Schoenstatt academics**. Hundreds of thousands of hours have gone into researching our founder, Fr. Joseph Kentenich, yet it is often difficult to access these resources. We hope provide a comprehensive list of [Schoenstatt-related literature](/literature) published, especially academic papers. This list links to digital copies of materials and [library catalogue entries](/libraries) where physical copies may be found.
3. **Web and phone application developers**. Our [REST APIs](https://docs.google.com/spreadsheets/d/1yht-M2D9kM-Y-LU84LO2CBZuHGrkIYOCbjJY59FKl7M/edit?usp=sharing) expose direct access to our database. We hope this will encourage programmers to innovate and invest in new Schoenstatt applications.

### How can I help?

1. **Data**. Is your [shrine information](/shrines) up-to-date? [Create an account](/user/register) to update it.
2. **Translation**. We try to keep this website and its data available in 5 languages: English, Spanish, German, Portuguese, and Italian. Please email [webmaster@schoenstatt.link](webmaster@schoenstatt.link) if you can help.
3. **Programming**. The schoenstatt.link web application is written in PHP in the [Laminas framework](https://getlaminas.org/). Our codebase is hosted on bitbucket. Please email [webmaster@schoenstatt.link](webmaster@schoenstatt.link) if you can help.

EOT;
?>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<?php echo $this->markdown($text);?>
</div></div>