<?php
// $this->inlineScript()->appendFile('/js/Chart.bundle.min.js', 'text/javascript', ['nonce' => $GLOBALS['inline-nonce']]);
// $schCounts = $this->changeCounts['schoenstatt'];
// $pubCounts = $this->changeCounts['publications'];
// $transCounts = $this->changeCounts['translations'];
// $untranslatedMonths = array_keys($schCounts);
// $months = [];
// foreach ($untranslatedMonths as $value) {
//     $months[] = '"'.$this->translate($value, 'default').'"';
// }
?>
<div class="jumbotron">
  <div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1><?php echo $this->translate("We need your help!");?></h1>
            <p><?php echo sprintf(
                $this->translate("Schoenstatt Link hopes to facilitate communication by dramatically increasing and improving Schoenstatt's web presence. We use the %s to help internet users find the Schoenstatt communities and shrines nearby, as well information on Schoenstatt books and material. Please help us centralize this information by the end of 2018!"),
                sprintf('<a href="%s" target="_blank">%s</a>', $this->translate('https://en.wikipedia.org/wiki/Knowledge_Graph'), $this->translate('Google Knowledge Graph'))
            ); ?></p>
            <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> -->
        </div>
        <div class="col-md-4">
        <!--<img src="/img/home.png" class="img-responsive center-block" alt="Schoenstatt Link">
            <canvas id="myChart" width="100%" height="100%"></canvas>
            
            ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
-->
<?php
/*
$vars = [
    'months' => $months,
    'schLabel' => $this->translate('schoenstatt edits'),
    'schCounts' => $schCounts,
    'pubLabel' => $this->translate('publication edits'),
    'pubCounts' => $pubCounts,
    'tranLabel' => $this->translate('translation edits'),
    'tranCounts' => $schCounts,
];
$varEncoded = json_encode($vars);
$jsScript = <<<JS
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: vars['month'],
        datasets: [{
            label: vars['schLabel'],
            data: vars['schCounts'],
            backgroundColor:
                'rgba(75, 192, 192, 0.2)',
            borderColor:
                'rgba(75, 192, 192,1)',
            borderWidth: 1
        },
        {
            label: vars['pubLabel'],
            data: vars['pubCounts'],
            backgroundColor:
                'rgba(54, 162, 235, 0.2)',
            borderColor:
                'rgba(54, 162, 235, 1)',
            borderWidth: 1
        },
        {
            label: vars['tranLabel'],
            data: vars['tranCounts'],
            backgroundColor:
                'rgba(255, 206, 86, 0.2)',
            borderColor:
                'rgba(255, 206, 86, 1)',
            borderWidth: 1
        },
        ]
    },
    options: {
        scales: {
            xAxes: [{
                stacked: true
            }],
            yAxes: [{
                stacked: true,
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
JS;

$this->inlineScript()->captureStart();
echo <<<JS
$(function () {
var vars = $varEncoded;
$jsScript
});
JS;
$this->inlineScript()->captureEnd();
*/
?>
        </div>
    </div>
  </div>
</div>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2><?php echo $this->translate("Latest blog posts");?></h2>
<?php
if (isset($this->blogPosts) && is_array($this->blogPosts)) :
    foreach ($this->blogPosts as $post) :?>
      <p><strong><a href="<?php echo $this->url('blog/blog-post', ['sw_id' => $post['identifier'], 'slug' => $post['slug']]);?>"><?php echo $this->translate($post['title']);?></a></strong></p>
        <?php
    endforeach;
endif;?>
      <!-- <p><a class="btn btn-default" href="mailto:webmaster@schoenstatt.link" role="button"><?php echo $this->translate('Contact us');?> »</a></p> -->
    </div>
    <div class="col-md-4">
      <h2><?php echo $this->translate("Are you bilingual?");?></h2>
      <p><?php echo $this->translate("Schoenstatt is an international movement which requires to provide information in many languages. Help us make our site accessible to the whole world!");?></p>
      <p><a class="btn btn-default" href="mailto:webmaster@schoenstatt.link" role="button"><?php echo $this->translate('Contact us');?> »</a></p>
   </div>
    <div class="col-md-4">
      <h2><?php echo $this->translate('Are you a developer?');?></h2>
      <p><?php echo $this->translate("About half of the work to maintain a reliable, centralized source of information depends on programmers who can provide the easy-to-use tools to submit and access the data.");?></p>
      <p><a class="btn btn-default" href="<?php echo $this->url('developers');?>" role="button"><?php echo $this->translate('Learn more');?> »</a></p>
    </div>
  </div>
</div>