<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
/**
 * Display a panel with a files table for an entity
 * @param $panelTitle autotranslated
 * @param $changes
 * @param $maxRows
 */
$title = isset($this->panelTitle) ? $this->panelTitle : 'Associated Files';
?>
<div class="row"> <!-- row -->
<div class="col-md-12">
<div class="panel panel-default" id="files">
<div class="panel-heading">
    <h3 class="panel-title"><?php echo $this->translate($title);?></h3>
</div>
<div class="panel-body">
    <?php if (! empty($this->files)) {
        echo $this->partial('books/files/list-files', [
            'files' => $this->files,
            'columns' => $this->columns
        ]);
    } else {
        echo '<p>' . $this->translate('No files found.') . '</p>';
    }?>
</div>
</div> <!-- panel -->
</div> <!-- column 12 -->
</div> <!-- row -->