<table>
<thead>
<tr>
<th>pageNumber</th>
<th>widthInPixels</th>
<th>heightInPixels</th>
<th>headerText</th>
<th>fullTextFileName</th>
<th>result</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->results as $result) :?>
<tr>
<td><?php echo $this->escapeHtml($result['pageNumber']);?></td>
<td><?php echo $this->escapeHtml($result['widthInPixels']);?></td>
<td><?php echo $this->escapeHtml($result['heightInPixels']);?></td>
<td><?php echo $this->escapeHtml($result['headerDhNumber']);?></td>
<td><?php echo $this->escapeHtml($result['fullTextFileName']);?></td>
<td><?php echo $this->escapeHtml($result['result']);?></td>
</tr>
<?php endforeach;?>
</tbody>

</table>