<?php $title = 'DH, theology tool';
$this->headTitle($title);?>
<h1><?php echo $this->translate($title);?></h1>
<?php
//@todo search bar, bottom or middle

//description
$description = "The author of this book has created a solid reference tool at the service of a deep life of " .
    "faith. We wish to make this tool more accessible; not to replace the possession of a " .
    "physical copy, but instead to allow students to make hyperlinks to specific documents while " .
    "studying the history of the Church. We count on the good faith of our users.";?>
<p class="lead"><?php echo $this->escapeHtml($this->translate($description));?></p>
<h3><?php echo $this->translate('Essential documents');?></h3>
<?php
//list of important documents
$docs = [
    'Concilio I de Nicea' => 125,
    'Concilio I de Constantinopla' => 150,
    'Concilio de Éfeso' => 250,
    'Concilio de Calcedonia' => 300,
    'Sínodo de Letrán contra los monotelitas' => 500,
    'Concilio II de Constantinopla' => 550,
    'Concilio II de Nicea' => 600,
    'Confesión de fe de Berengario de Tours' => 700,
    'Concilio IV de Letrán' => 800,
    'Constitución “Benedictus Deus” de Benedicto XII' => 1000,
    'Concilio de Florencia' => 1300,
    'Concilio de Trento' => 1500,
    'Constitución “Cum occasione” contra Comelio Jansen' => 2001,
    'Decreto contra los errores de los laxistas' => 2101,
    'Decreto contra los errores de los jansenistas' => 2301,
    'Constitución “Auctores fidei” contra los errores del Sínodo de Pistoya' => 2600,
    'Bula “Ineffabilis Deus” sobre la concepción inmaculada de María' => 2800,
    'Concilio Vaticano I' => 3000,
    'Decreto “Lamentabili” contra los errores de los modernistas' => 3401,
    'Encíclica “Casti connubii” sobre el matrimonio cristiano' => 3700,
    'Constitución “Munificentissimus Deus” sobre la Asunción de María' => 3900,
    'Concilio Vaticano II' => 4001,
];?>
<ul class="list-unstyled">
<?php foreach ($docs as $document => $dhNumber) :
    $text = $document . ' (DH' . $dhNumber . ')';?>
<li><a href="<?php echo $this->url('dh/number', ['dh_number' => $dhNumber]);?>"><?php
echo $this->escapeHtml($text);?></a></li>
<?php endforeach;?>
</ul>