<?php
use Bible\Model\DhTable;

$pageNumber = is_numeric($this->entity['pageNumber']) ? (int)$this->entity['pageNumber'] : null;
$previousPage = null;
$nextPage = null;
if (isset($pageNumber)) {
    $previousPage = $pageNumber - 1;
    if ($previousPage <= 0) {
        $previousPage = null;
    }
    $nextPage = $pageNumber + 1;
    if ($nextPage > DhTable::LAST_PAGE_NUMBER) {
        $nextPage = null;
    }
}?>
<p><span><?php
if (isset($previousPage)) :
    ?><a href="<?php echo $this->url('dh/page', ['page_number' => $previousPage]);?>"><?php
    echo $this->translate('Previous page');?></a><?php
else :
    echo $this->translate('Previous page');
endif;?></span>
<span class="pull-right"><?php
if (isset($nextPage)) :
    ?><a href="<?php echo $this->url('dh/page', ['page_number' => $nextPage]);?>"><?php
    echo $this->translate('Next page');?></a><?php
else :
    echo $this->translate('Next page');
endif;?></span></p>