<?php 
use Bible\Model\DhTable;

$pageNumber = is_numeric($this->entity['pageNumber']) ? (int)$this->entity['pageNumber'] : null;
$previousPage = null;
$nextPage = null;
if (isset($pageNumber)) {
    $previousPage = $pageNumber-1;
    if ($previousPage <= 0) {
        $previousPage = null;
    }
    $nextPage = $pageNumber+1;
    if ($nextPage > DhTable::LAST_PAGE_NUMBER) {
        $nextPage = null;
    }
}
?>
<div class="row">
<div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
<p><span><?php 
if (isset($previousPage)):
?><a href="<?php echo $this->url('dh/page', ['page_number' => $previousPage]);?>"><?php 
    echo $this->translate('Previous page');?></a><?php 
else:
    echo $this->translate('Previous page');
endif;?></span>
<span class="pull-right"><?php 
if (isset($nextPage)):
?><a href="<?php echo $this->url('dh/page', ['page_number' => $nextPage]);?>"><?php 
    echo $this->translate('Next page');?></a><?php 
else:
    echo $this->translate('Next page');
endif;?></span></p>
<a href="<?php 
echo $this->escapeHtmlAttr($this->entity['fileUrl']);
?>"><img height="<?php echo $this->escapeHtmlAttr($this->entity['heightInPixels']);
?>" width="<?php echo $this->escapeHtmlAttr($this->entity['widthInPixels']);
?>" src="<?php echo $this->escapeHtmlAttr($this->entity['fileUrl']);?>" alt="DH page <?php 
echo $this->escapeHtmlAttr($this->entity['pageNumber']);?>" class="img-responsive"/></a>
</div>
</div>