<div class="row">
<div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
<?php echo $this->partial('page-header', $this->vars);?>
<a href="<?php 
echo $this->escapeHtmlAttr($this->entity['fileUrl']);
?>"><img height="<?php echo $this->escapeHtmlAttr($this->entity['heightInPixels']);
?>" width="<?php echo $this->escapeHtmlAttr($this->entity['widthInPixels']);
?>" src="<?php echo $this->escapeHtmlAttr($this->entity['fileUrl']);?>" alt="DH page <?php 
echo $this->escapeHtmlAttr($this->entity['pageNumber']);?>" class="img-responsive"/></a>
<?php echo $this->partial('page-header', $this->vars);?>
</div>
</div>